### ISSUE TITLE
Read inbox items not being handle correctly

### ISSUE THREAD

**Issue by grrrrr** [QuantumBadger/RedReader#101]
Precursor: this may not be a RedReader issue but I only see this happening wen using this mobile client

What happens:
1. I get a new message or reply to comment which goes to my inbox.
2. use Red Reader to read the inbox messages.
3. Go to Reddit via browser, no new messages in inbox.
4. receive a new message.
5. Go to reddit via browser, inbox shows both the message at step 1 and step 4 as new.

What should happen:
1. I get a new message or reply to comment which goes to my inbox.
2. use Red Reader to read the inbox messages.
3. Go to Reddit via browser, no new messages in inbox.
4. receive a new message.
5. Go to reddit via browser, inbox shows only the message at step 4 as new.

**Comment by QuantumBadger** [comment]
Fixed in v1.8.7.8, which has an option for marking all messages as read.
