### ISSUE TITLE
Redgifs no longer open in app

### ISSUE THREAD

**Issue by smital12** [QuantumBadger/RedReader#1019]
Redgifs links no longer open in-app. Instead they open in external browser with error "Could not download image metadata. Trying web browser".

Example URL (NSFW)
[snipped]

**Comment by QuantumBadger** [comment]
Thanks for the report, will investigate. I'll snip the example URL out of your comment so we don't violate any GitHub policies :)

**Comment by QuantumBadger** [comment]
I think they changed their API and then reverted the change for now. RedGIFs have now been in touch to say the old API will be cut off on August 30th.

**Comment by QuantumBadger** [comment]
As of Alpha 320 we're now using the latest version of the API.

**Comment by polyzen** [comment]
Please make a new release.

**Comment by QuantumBadger** [comment]
@polyzen Currently planning to release v1.20 tomorrow (it's been a long time coming!)

**Comment by QuantumBadger** [comment]
Everything's mostly done for the release, just waiting for Google's review process now.
