### ISSUE TITLE
Self text not shown when post also links image

### ISSUE THREAD

**Issue by Bodertz** [QuantumBadger/RedReader#1028]
Reddit supports self text posts which also link to an image.  RedReader does not support this, however, showing only the image.

In RedReader, if you bring up the context menu for the post (either by pressing and holding on the post or by tapping the three dots menu under the post) you can see that the post has a URL property as well as a self text property.  This is the only way to read the self text in RedReader.

I do not know if this is an issue for all posts which link URLs or only for posts which link URLs on i.reddit.it.

The below URL is a post which contains self text and also links to an image.

https://www.reddit.com/r/SteamDeck/comments/x5dw5e/ughi_hate_the_world_right_now/

**Comment by monochrony** [comment]
Same issue just popped up for me with this post:
[818585](https://www.reddit.com/r/MovieDetails/comments/13n6jpc/vegas_vacation_1997/)

**Comment by nascentt** [comment]
Apparently effects video posts too

https://reddit.com/comments/14pi2ex
