### ISSUE TITLE
Logcat said connected failed

### ISSUE THREAD

**Issue by RiShinku** [QuantumBadger/RedReader#1050]
Sometimes logcat will record an error that connected failed if I open the window for creating accounts. the detailed record was 'Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)'

**Comment by Ikenshith** [comment]
I also found some errors below:
Access denied finding property "persist.device_config.runtime_native.use_app_image_startup_cache"
LoadAppImageStartupCache enabled : 1
Fail to acquire dataAnalyzerService
parse speed value length error
they occur when opening the app sometimes.

**Comment by Ikenshith** [comment]
And error 'Error downloading announcements: status null, type 1' may be caused by some download error, my Redreader said it can not complete the download successfully.

**Comment by QuantumBadger** [comment]
Thanks for the report, however logcat is full of errors like this, mostly from the Android system and associated libraries, so it's nothing to worry about!
