### ISSUE TITLE
[Bug] RedReader does not handle Imgur subdomains

### ISSUE THREAD

**Issue by nerstak** [QuantumBadger/RedReader#1051]
Currently, RedReader does not seems to distinguish which Imgur subdomains it should load an image from. It may lead to the wrong image being loaded.

For example, in this [comment](https://www.reddit.com/r/howdidtheycodeit/comments/lfjjqa/eco_global_survival_is_voxelbased_but_on_a/gmmeydl/), it should load and display the following image: [https://i.stack.imgur.com/Lzzv0.jpg](https://i.stack.imgur.com/Lzzv0.jpg). However, it does load this one instead (warning: NSFW) [https://i.imgur.com/Lzzv0.jpg](https://i.imgur.com/Lzzv0.jpg).

RedReader Version used: 1.20

**Comment by QuantumBadger** [comment]
Thanks for reporting this! I have a fix which will be in the next alpha.
