### ISSUE TITLE
$500 usd "bug bounty" for fast tracking Lemmy support

### ISSUE THREAD

**Issue by Footsiefat** [QuantumBadger/RedReader#1064]
"Bug bounty" will be paid in Monero

**Comment by QuantumBadger** [comment]
I'm in favour of Lemmy (and similar) support being added to the app and it's generous for people to offer bounties for this, but I'd like to avoid a situation where people rush to submit a poor quality implementation to get the bounty, so people should bear in mind that I will only accept PRs that are up to an acceptable standard! (both in terms of UX and code quality)

Also, I should make it clear to everyone that I'm not affiliated with @Footsiefat and don't endorse this post in any way, or know that any bounty will actually be paid out.

**Comment by Footsiefat** [comment]
Fully understood, closing issue
