### ISSUE TITLE
Issue: Self-text not showing if the post is a link post

### ISSUE THREAD

**Issue by Brodesto** [QuantumBadger/RedReader#1071]
![Screenshot_20230619_112448_rif is fun golden platinum](https://github.com/QuantumBadger/RedReader/assets/137105251/0458fab3-d0da-473a-bf40-283de6fa03a1)

I ran into this issue and wanted to share an example of RIF (on the left) and RedReader (on the right). You can see the self-text is missing when the post itself is a link type post.

**Comment by nascentt** [comment]
This still sends to be an issue. Reported here:  https://reddit.com/comments/151io75

**Comment by QuantumBadger** [comment]
This has been fixed in the code, but won't be released to production until v1.22.
