### ISSUE TITLE
[Feature request] "Submitted comments" in "user items"

### ISSUE THREAD

**Issue by KaKi87** [QuantumBadger/RedReader#1073]
Hello,

Just like "user items" includes "submitted posts", it would be nice to include "submitted comments".

Thanks

**Comment by nascentt** [comment]
That's already there.  
My Profile in main menu, then View Comments

**Comment by KaKi87** [comment]
Yes, but as you say, it's in a menu, i.e. requires two clicks.

Meanwhile, I'm requesting that it could be added in the user section of the homepage, i.e. accessible in a single click.

Thanks
