### ISSUE TITLE
Upper-case schemes in URLs do not open in external browser

### ISSUE THREAD

**Issue by Sophira** [QuantumBadger/RedReader#1099]
In RedReader, URLs that appear in a comment (and likely a post as well) do not have the scheme filtered to lower-case (`https://` vs. `HTTPS://`). This is a problem as many apps do not receive intents where the URL scheme is in upper-case, resulting in RedReader opening the link in its own internal browser instead of the user's defined default browser, even if the app is set to open all links in an external browser. This may be undesirable because, for example:

* The internal browser will not be running extensions such as ad blockers,
* Any app designed to be an intermediary between apps and browsers (such as the excellent [URLCheck](https://github.com/TrianguloY/UrlChecker/)) will not catch the intent (though I've also opened [a feature request](https://github.com/TrianguloY/UrlChecker/issues/258) to allow URLCheck, at least, to catch these).

As an example, [this Reddit comment contains a link to `HTTPS://join-Lemmy.org`](https://www.reddit.com/r/ActLikeYouBelong/comments/14retl7/ractlikeyoubelong_needs_moderators_and_is/jqsi8bo/)). When opened in RedReader 1.21.1 with the "Behaviour->Use internal browser" option disabled, it fails to open the link in an external browser, and opens the link in its internal browser.

As schemes are defined as lower-case with a recommendation for programs to treat upper-case as if it was lower-case[1][2], I believe RedReader should automatically convert schemes in URLs to lower-case before opening the URL. (In this example, the link would be converted to `https://join-Lemmy.org` before attempting to open it.)

[1] https://www.rfc-editor.org/rfc/rfc1738#section-2.1
[2] https://www.rfc-editor.org/rfc/rfc3986#section-3.1

**Comment by Cguy7777** [comment]
Currently working on this.
