### ISSUE TITLE
permission denied error on video playback

### ISSUE THREAD

**Issue by sihorrocks** [QuantumBadger/RedReader#1114]
Any video playback within the app is reporting a permission denied error, using Android, Samsung S10 plus

Gif playback unaffected

Screenshot below
![Screenshot_20230729-091851_RedReader](https://github.com/QuantumBadger/RedReader/assets/138950187/163106bb-2f36-4eb1-a838-e776aaa91f17)

**Comment by Packjackisback** [comment]
Install the most recent update, and make sure your error hasn't already been reported

**Comment by sihorrocks** [comment]
Guessing the roll out hasn't quite reached NZ yet, still 1.21.2 here, I did scroll down issues on GitHub, but couldn't see it, so thought it might just be me. I'll sub to the subreddit too for future.

**Comment by Packjackisback** [comment]
Ah app stores will always be behind, download from github.

**Comment by QuantumBadger** [comment]
Thanks for the report, fixed in v1.22!
