### ISSUE TITLE
Twitch clips not playing after 3 seconds in the app browser

### ISSUE THREAD

**Issue by zeinterrupter** [QuantumBadger/RedReader#1120]
Every time I open a clip from twitch in the app I get to see till 0:03 and then it just stops with no way to continue.
If I open the link in the browser everything works great.

Is this maybe just a me issue? Would someone confirm please?
Here is an example link https://clips.twitch.tv/YawningTameOysterBuddhaBar-QLIJuBBL8norCpZO

**Comment by nascentt** [comment]
I haven't used the internal browser in years, but I posted a link and comment of https://clips.twitch.tv/YawningTameOysterBuddhaBar-QLIJuBBL8norCpZO and it plays the entire clip for me with the internal browser without issue.

You probably need to update your webview.

**Comment by zeinterrupter** [comment]
So it seems i was using chrome's webview instead of android and since i haven't updated chrome in a long while it was causing the problem, got solved when i updated chrome
