### ISSUE TITLE
Videos are not playing

### ISSUE THREAD

**Issue by EmmanuelMess** [QuantumBadger/RedReader#1121]
Phone: Nokia 2.4
Android: 12
Version 1.22

Videos are not playing unless I open them in a browser.

**Comment by nascentt** [comment]
Any example posts?  Not seen any issues

**Comment by polyzen** [comment]
IIRC imgur vids are the ones that didn't work for me. Had noted the vid, but accidentally copied the imgur link and not the Reddit link, which afaik you can't open with RedReader.

**Comment by EmmanuelMess** [comment]
This was fixed already.
