### ISSUE TITLE
New reddit thread sharing links don't work

### ISSUE THREAD

**Issue by lol768** [QuantumBadger/RedReader#1122]
These have the form of `https://reddit.com/r/<subreddit>/s/<shareCode>` and appear to be generated by the iOS app. If you send it a HEAD request, you'll be redirected to `https://www.reddit.com/r/<subreddit>/s/<shareCode>` and then the `Location` header in _that_ response (i.e. the `wwww.` prefixed req.) will be set to the actual real thread URI.

I don't know if only posts can be shared in this way, or if whole subreddits can be shared too.

Redreader does not handle these well at present and you just get a black screen. `RedditURLParser.parse` seems to just return back null

Logs show: 
```
wm_on_create_called: [28321549,org.quantumbadger.redreader.activities.LinkDispatchActivity,performCreate]
wm_add_to_stopping: [0,28321549,org.quantumbadger.redreader/.activities.LinkDispatchActivity,completeFinishing]
wm_restart_activity: [0,222850074,19049,org.quantumbadger.redreader/.activities.LinkDispatchActivity]
wm_set_resumed_activity: [0,org.quantumbadger.redreader/.activities.LinkDispatchActivity,minimalResumeActivityLocked - onActivityStateChanged]
wm_create_activity: [0,11381031,19049,org.quantumbadger.redreader/.activities.LinkDispatchActivity,android.intent.action.VIEW,NULL,https://reddit.com/...,268435456]
wm_pause_activity: [0,222850074,org.quantumbadger.redreader/.activities.LinkDispatchActivity,userLeaving=true,resumeTopActivity]
wm_finish_activity: [0,222850074,19049,org.quantumbadger.redreader/.activities.LinkDispatchActivity,app-request]
wm_on_create_called: [222850074,org.quantumbadger.redreader.activities.LinkDispatchActivity,performCreate]
wm_add_to_stopping: [0,222850074,org.quantumbadger.redreader/.activities.LinkDispatchActivity,completeFinishing]
wm_restart_activity: [0,11381031,19049,org.quantumbadger.redreader/.activities.LinkDispatchActivity]
wm_set_resumed_activity: [0,org.quantumbadger.redreader/.activities.LinkDispatchActivity,minimalResumeActivityLocked - onActivityStateChanged]
wm_create_activity: [0,220585280,19049,org.quantumbadger.redreader/.activities.LinkDispatchActivity,android.intent.action.VIEW,NULL,https://reddit.com/...,268435456]
wm_pause_activity: [0,11381031,org.quantumbadger.redreader/.activities.LinkDispatchActivity,userLeaving=true,resumeTopActivity]
wm_finish_activity: [0,11381031,19049,org.quantumbadger.redreader/.activities.LinkDispatchActivity,app-request]
wm_on_create_called: [11381031,org.quantumbadger.redreader.activities.LinkDispatchActivity,performCreate]
wm_add_to_stopping: [0,11381031,org.quantumbadger.redreader/.activities.LinkDispatchActivity,completeFinishing]
```

**Comment by lol768** [comment]
Example: https://www.reddit.com/r/RedReader/s/uUT0qRlGc8

**Comment by nascentt** [comment]
So many posts within Reddit now are share links. It's essentially rendering redreader unable 1/2 the time, especially if you frequent subs that are primarily sharing posts from within Reddit such as r/subredditdrama

I've had to switch back to relay as that handles share links properly.

**Comment by lol768** [comment]
@nascentt They're increasingly prevalent, I agree - not sure it's really RedReader's fault though. These got introduced without any sort of consultation just so that Reddit could track users and what they share in more detail.

You can build the branch in my pull request if you want to continue to be able to use RedReader before a new release: https://github.com/QuantumBadger/RedReader/pull/1123

**Comment by mkatsevVR** [comment]
Can you please push the updated version to Google Play? This bug makes it very hard to use the app currently
