### ISSUE TITLE
Issue: New style short links don't work

### ISSUE THREAD

**Issue by shr1k** [QuantumBadger/RedReader#1138]
Hello 👋,

I've realised over the last few days that the new short links don't work correctly in the app -- it just opens up to a blank screen.

Example links:

- https://reddit.com/r/MadeMeSmile/s/MemRBHqOnN

- https://reddit.com/r/unitedkingdom/s/LZWV6lsD2l

- https://reddit.com/r/LinkedInLunatics/s/O9mhE6dI4e

To clarify, clicking these links opens the app as I'd expect, so the URL handling is alright, just that the app opens up to a blank screen and doesn't load any content. Screenshot below:

![Screenshot_20231014-073021](https://github.com/QuantumBadger/RedReader/assets/927606/787e5fd1-e803-4c22-a667-c805713c4e68)

I suspect these are short links generated by sharing via the official app?

(This is my first issue in this repo, my apologies if I've done something wrong, please correct me!)

**Comment by QuantumBadger** [comment]
Thanks for the report! We've recently merged in a fix for this, thanks to @lol768:

https://github.com/QuantumBadger/RedReader/pull/1123

If you'd like to try it out, it should be in the latest alpha version:

https://redreader.org/alpha/

**Comment by shr1k** [comment]
Oh so sorry, I thought I'd searched for the issue but had clearly gone horribly wrong somewhere. Thanks so much!
