### ISSUE TITLE
Legacy menu

### ISSUE THREAD

**Issue by nascentt** [QuantumBadger/RedReader#1142]
I've started using the alpha as apparently it's finally fixed the fact that a large portion of Reddit doesn't work due to new share links.

However I find I'm struggling with the new menus a bit.  I'm not sure if it's the new shape or the fact the menu item font is smaller.

But getting an option to show the legacy menus would be a good idea.  If not possible, maybe a menu font size option would help.

I find I mispress menu items a lot with the new menu, which has never happened with the old menu.

**Comment by QuantumBadger** [comment]
At some point soon I'm planning to redesign the long-press menus entirely, and will make the text bigger and add icons. I'm not sure if I'll get around to this before the next version though.

**Comment by nascentt** [comment]
Font size was fixed in one of the recent alphas.  
QuantumBadger re-confirmed [he can't easily restore the legacy menu](https://reddit.com/comments/18jwmod/comment/kds1gon?context=3)

**Comment by nascentt** [comment]
Happy for this to be closed now that the font size and padding have been fixed.
