### ISSUE TITLE
need advice on how to build this or change the code

### ISSUE THREAD

**Issue by JunkyardCat** [QuantumBadger/RedReader#1144]
im still using 1.20 and its still working and have no intention to move to 1.22 since it makes you accept the new reddit policy. was wondering what i should change in the code to make the video play on 1.20? can you tell me what i need to change in 1.20 to make this work?

**Comment by JunkyardCat** [comment]
is this not possible?

**Comment by QuantumBadger** [comment]
I understand the concern but, to be clear, accessing Reddit's API using any app, RedReader or otherwise, means agreeing to their API terms. v1.22 is just the first version to explicitly show a prompt saying this.
