### ISSUE TITLE
Could not log in. Access Token error

### ISSUE THREAD

**Issue by garrthes** [QuantumBadger/RedReader#1148]
Title: Unknown Error
Message: Could not log in.
HTTP Status: 500
URL: https://www.reddit.com/api/v1/access_token

RedReader v1.22

Only when logged in with my account. Anonymous account is working fine.
Tried signing out and in again to no avail.

**Comment by Spark4000** [comment]
Having same issue, http status 500. https://oauth.reddit.com/r/adguard/new/.json

**Comment by QuantumBadger** [comment]
I'm seeing this too, it must be an issue on Reddit's end. I'll get in touch with them now.

**Comment by mvdan** [comment]
Appears to be a known outage: https://www.redditstatus.com/incidents/6mjlx463qsj6

I also see issues with the web interface.

**Comment by QuantumBadger** [comment]
Thanks @mvdan, yes I'm also seeing issues accessing Reddit via web (with both the old and the new interface).
