### ISSUE TITLE
Option to save Image 

### ISSUE THREAD

**Issue by s0mt0chukwu** [QuantumBadger/RedReader#1151]
I recently notices one can't save Images from the app to local storage, sincerely hope you would fix this please :⁠'⁠(

**Comment by QuantumBadger** [comment]
Thanks the report -- the option should still be there, but you may need to scroll down as the menu theme has changed.

**Comment by nascentt** [comment]
Seems like a few recent issues revolve around the usability if these new scrolling menus.  Shame these weren't held back until the proposed nesting was complete
