### ISSUE TITLE
Subreddit Title Bug

### ISSUE THREAD

**Issue by ramy-att** [QuantumBadger/RedReader#1180]
Device Info: Used Pixel 4A, android version 2024010900
Version tested: V1.23.1 stable
Stacktrace: Bug does not cause a crash
Duplicate: None

# How to reproduce:
Launch app
Open any subreddit and go to a post without links
Displays (self.subredditName)

# Actual Behavior:
![image](https://github.com/QuantumBadger/RedReader/assets/83047251/cebe0a27-1348-46d7-8e62-4c3a454b5c31)

# Expected Behavior:
If there is a link: display the link as a source link
If there is no link: should not display anything

![image](https://github.com/QuantumBadger/RedReader/assets/83047251/cab783ce-2162-4981-ab7c-a9886e9f8b93)
![image](https://github.com/QuantumBadger/RedReader/assets/83047251/3932b0a9-56b2-45cc-9b30-def23d4cb5d7)

**Comment by QuantumBadger** [comment]
There's no bug here -- `self.subredditName` is the domain Reddit shows for self posts.
