### ISSUE TITLE
[Feature Request] View all subscribed subreddits together 

### ISSUE THREAD

**Issue by justeepin** [QuantumBadger/RedReader#1190]
Could an option to view all subscribed subreddits together be added?  I miss that from the official Reddit app along with being able to get notifications for specific subreddits.

**Comment by ParitoshKumarTripathi** [comment]
well this is now available in the latest update but i don't know why this issue is yet not closed.

**Comment by QuantumBadger** [comment]
This has been available since the first release of RedReader, in the "Front Page" option. I've renamed this to "Subscribed Posts" in the next version (for logged-in users) for clarity.

**Comment by justeepin** [comment]
> This has been available since the first release of RedReader, in the "Front Page" option. I've renamed this to "Subscribed Posts" in the next version (for logged-in users) for clarity.

I meant, view all your subreddits together not just a list. On the official Reddit when I open it, it shows all the newest posts from all my subreddits in chronological order.

**Comment by QuantumBadger** [comment]
Yes, that's the behaviour of the "Front Page" option at the top of the main menu. It's shows recent/popular posts from your subscribed subreddits.

**Comment by justeepin** [comment]
I don't see a front page option in Red Reader.

**Comment by QuantumBadger** [comment]
Not sure what you mean -- unless you've explicitly disabled it in the settings, "Front Page" is the first item in the main menu.
