### ISSUE TITLE
Change "Self Text" to "Text" in post submit activity

### ISSUE THREAD

**Issue by jidanni** [QuantumBadger/RedReader#1192]
Do not say "self text". Nobody knows what you're talking about. It's not proper English. 
![Screenshot_20240525_202733_RedReader](https://github.com/QuantumBadger/RedReader/assets/1230959/a8d0b944-4f4f-4b37-88ad-afd96637ad1a)

**Comment by QuantumBadger** [comment]
"Self text" has historically been Reddit's terminology for the text associated with a "self post". They seem to have moved towards "text post", so I have no objection to us renaming this field to just "text".

**Comment by jidanni** [comment]
In fact the word "self" splattered all over the place. 

![Screenshot_20240527_130223_RedReader.jpg](https://github.com/QuantumBadger/RedReader/assets/1230959/b834d236-68bb-45bd-808e-e02cccb45cfc)

But I've never noticed it when using their official products. 

In fact it looks like some kind of object oriented coding internal error if you ask me. 

So you might want to go through all your code looking for every instance of it. Thanks.

**Comment by QuantumBadger** [comment]
That's incorrect. As I say above, it's terminology directly from Reddit itself. In fact the text you circled in red is displayed exactly as it's returned from the Reddit API.

Explanation from a former Reddit employee:

https://old.reddit.com/r/help/comments/2bmy3l/what_does_the_self_in_for_example_selfhelp_refer/

RedReader isn't written in a language that uses `self` as a keyword.

**Comment by jidanni** [comment]
Well OK, but one doesn't want raw API::names coming in direct contact with users... Let's not be **self**ish :-)

**Comment by QuantumBadger** [comment]
The Reddit site has historically shown the same `self` label, in the post domain as shown above (and still does on `old.reddit.com`) -- it's not just some internal API string. In any case I've updated the submit activity field label, it'll be in the next release.
