### ISSUE TITLE
Long pressing to bring up the context menu on items in the new drid layout has no vibration feedback

### ISSUE THREAD

**Issue by nascentt** [QuantumBadger/RedReader#1220]
Long pressing to bring up the context menu on items in the new grid layout has no vibration feedback

**Comment by QuantumBadger** [comment]
Thanks for the report. It seems with Compose we have to manually call `haptic.performHapticFeedback(HapticFeedbackType.LongPress)` in every long click handler...

**Comment by QuantumBadger** [comment]
I ended up adding a `combinedClickableWithHaptics` extension function to do this automatically.

**Comment by nascentt** [comment]
Seems good on v357
