### ISSUE TITLE
Reddit is down

### ISSUE THREAD

**Issue by UnoNYC** [QuantumBadger/RedReader#1243]
Everytime I try to click on a link, regardless of whether I am logged into my account or Anonymous, I get this error:

![Screenshot_20240919-153121_RedReader.jpg](https://github.com/user-attachments/assets/54006d1a-c564-4e79-be5f-69860a31061f)

When I clicked on the details button, I got this result.

![Screenshot_20240919-153141_RedReader.jpg](https://github.com/user-attachments/assets/fec295bd-0c9b-414c-a7e9-3e1941bb6c7d)

I had the same issue when I was using the previous version and when I updated it, thinking that it would fix the issue, it still didn't work.

**Comment by acidstout** [comment]
I confirm the issue. Just checked with the latest version. No subreddit is accessible any more.

**Comment by CunTrump** [comment]
Same - I assumed that I got banned again. Apparently, maybe not. 

Right after 15:00 EST, while using app, started getting same error message.

**Comment by QuantumBadger** [comment]
The whole of Reddit is down: https://www.redditstatus.com/

Seems to be partially resolved for me, none of the pages were loading a few minutes ago.

**Comment by QuantumBadger** [comment]
Seems to be resolved.
