### ISSUE TITLE
[feature request] support for multis

### ISSUE THREAD

**Issue by echo743** [QuantumBadger/RedReader#127]
It would be great if someone could create a "multireddits" section above or below the "subreddits" section.

http://www.reddit.com/dev/api#section_multis

**Comment by travisfw** [comment]
The v2 branch hasn't been touched for a while. I'm still hoping for this feature. News?
I'm a Java programmer with very little Android experience, but I'm willing to help.

**Comment by QuantumBadger** [comment]
I've abandoned the v2 branch and the new stuff is gradually making its way into master.

I'll look into adding this in the next release (v1.9.0).

**Comment by tapir** [comment]
any news?

**Comment by QuantumBadger** [comment]
> any news?

Not yet, sorry.

**Comment by r00tbox** [comment]
I would also love this Feature, because most of the time this is how i use reddit :)

**Comment by QuantumBadger** [comment]
Added in the latest alpha.
