### ISSUE TITLE
[feature request] Orbot / Tor compatibility

### ISSUE THREAD

**Issue by kb100** [QuantumBadger/RedReader#144]
Are there any plans for RedReader to support connections through Tor / Orbot or any other proxy? I would appreciate this feature.

**Comment by manwesulimo2004** [comment]
I would also be interested in this feature.

**Comment by DistantParadox** [comment]
Interested here as well.

**Comment by QuantumBadger** [comment]
This has been added and will be in v1.9.4. Unfortunately there's a bug where page loads will sometimes return 403.
