### ISSUE TITLE
[Feature request] - Direct gfycat links to HTML5 video

### ISSUE THREAD

**Issue by CarbonFixer** [QuantumBadger/RedReader#153]
Currently clicking on a link from gfycat.com (see http://www.reddit.com/r/gfycats) directs you to a page where you need to choose between the HTML5 video and the gif.
Having to make one less click would be great.
Ideally I think a reddit client should direct to the HTML5 video, as that is the whole point of using gfycat, but directing to the gif would still be better than having to choose.

**Comment by QuantumBadger** [comment]
Done in v1.9.1.
