### ISSUE TITLE
Tables are not rendered

### ISSUE THREAD

**Issue by huonw** [QuantumBadger/RedReader#163]
E.g. http://www.reddit.com/r/sandboxtest/comments/2gc96p/table/ has source:

```
X | Y | Z
-|-|-
1 | 2 | 3
4 | 5 | 6
7 | 8 | 9
```

and is just rendered as that, not as a proper table like the website.

**Comment by Symbian9** [comment]
> My current plan

Any news on table rendering in RedReader?

P.S.: There are some open-source Android apps for Markdown editing that render tables well. Maybe it's possible fork their code for render tables?

**Comment by QuantumBadger** [comment]
I haven't started work on this myself, but would gladly merge in a pull request implementing this, and would be happy to help out of necessary.

**Comment by hyiltiz** [comment]
This really is the only substantial feature that I think would be missing from RR compared to Slide. It it follows MCV or similar models, then wouldn't it be simple to plug in a markdown+html capable renderer?

**Comment by Syntax3rr0r** [comment]
So I'd like to try and take a swing at this bug if it is still not fixed. any advice where I can start?

**Comment by QuantumBadger** [comment]
Fixed in https://github.com/QuantumBadger/RedReader/commit/46852d0a95aa89e7dac8219f9b2ccec481f118b5 (alpha 198).
