### ISSUE TITLE
[Feature Request] Material Design

### ISSUE THREAD

**Issue by sphaerophoria** [QuantumBadger/RedReader#173]
I know it seems shallow, but a lot of what I'm looking for when I download an app is that it does what it it's supposed while looking good. Material design would attract a lot of users I think.

**Comment by Hund** [comment]
+1

**Comment by QuantumBadger** [comment]
This is in progress (in a local branch).

**Comment by Hund** [comment]
That's good news! I'm really looking forward to it. :)

**Comment by QuantumBadger** [comment]
Added in v1.9.4.

**Comment by Hund** [comment]
Cool! I'm really looking forward to this! :)
