### ISSUE TITLE
Don't allow voting/commenting on archived posts

### ISSUE THREAD

**Issue by QuantumBadger** [QuantumBadger/RedReader#176]

**Comment by ajs124** [comment]
This is one of the most annoying bugs in RedReader for me and I'm trying to fix it, but I'm kind of stuck. 

From what I could gather, this _should_ be fixable somewhere in [RedditAPI.findFailureType()](https://github.com/QuantumBadger/RedReader/blob/master/src/main/java/org/quantumbadger/redreader/reddit/RedditAPI.java#L485), but apparently voting on archived content doesn't result in a failure?

**Comment by QuantumBadger** [comment]
I've just tested this, and it seems to be possible to vote on archived content through the API.

If I try and vote on a 2 year old comment on the website, I get an error, but if I vote on the same comment in the app, it's successful and the vote is reflected after refreshing the website.

**Comment by ajs124** [comment]
So… what you're saying is that this is actually a bug in reddit?

**Comment by QuantumBadger** [comment]
Looks like it :)

https://www.reddit.com/r/bugs/comments/28oy3r/possible_api_error_i_can_vote_on_archived_posts/

So I suppose we can either:

* Compare the local time to the post creation time to find out how old it is, and show an warning if it's older than 6 months. This could cause problems if the user's clock is incorrectly set.
* Ignore the problem until reddit fix their broken API :)

**Comment by DogPawHat** [comment]
Submitted a fix with #223

**Comment by DogPawHat** [comment]
This can be closed now
