### ISSUE TITLE
option to always refresh...

### ISSUE THREAD

**Issue by Adolflow** [QuantumBadger/RedReader#18]
I like that it keeps cached copies, but can there be an option to always refresh? Usually I load up a sub then always have to refresh posts...

**Comment by QuantumBadger** [comment]
Finally done :)

**Comment by engelju** [comment]
Is this in Alpha 86? Because the only setting I see is under Cache --> "Refresh posts if cache older than...", but no option to toggle "always refresh".

**Comment by QuantumBadger** [comment]
> Refresh posts if cache older than

Yep, that's the new option :) If you open a post list, and the cached copy is older than the specified time, the app will redownload the list rather than using the cache.

If 1 hour is too long, I could add an "Every time" value to the menu?

**Comment by engelju** [comment]
> If 1 hour is too long, I could add an "Every time" value to the menu?

That would be awesome! 😄

**Comment by QuantumBadger** [comment]
Added here:

https://github.com/QuantumBadger/RedReader/commit/f71f410cce95fc312dc83464c20351cd2806ebf9

Should be in Alpha 87 in a few moments :)

**Comment by engelju** [comment]
> Should be in Alpha 87 in a few moments :)

Works like a charm, thanks!
