### ISSUE TITLE
scrolling

### ISSUE THREAD

**Issue by Zuko** [QuantumBadger/RedReader#19]
scrolling is not fluent even on phone with four cores ;/ [nexus 4]
maybe some "jobs" could be moved to separate threads?

**Comment by QuantumBadger** [comment]
This is a lot better as of v1.9.0, but there's still some room for improvement.

**Comment by QuantumBadger** [comment]
Scrolling is very smooth now, and will get better in future when the post list switches to a RecyclerView.
