### ISSUE TITLE
Feature: Allow imgur links to be opened over https

### ISSUE THREAD

**Issue by BasioMeusPuga** [QuantumBadger/RedReader#194]
Hey,

Full disclosure: I'm from India and my government, in its infinite wisdom, has decided to block http access to imgur. Is there a possibility that RedReader might allow http imgur links to redirect to https ones instead? 
I can't think of any kind of negative side effect from this sort of change. Also, no other reddit client in the entire play store does this, so it would certainly help RR stand out whenever another representative of the people takes away muh cat photos

**Comment by QuantumBadger** [comment]
Done!

https://github.com/QuantumBadger/RedReader/commit/621d87eed0155cdb53da56d0bc22c1767bf10c8d

Also, I've added a "Use HTTPS" menu option to the internal web browser.

https://github.com/QuantumBadger/RedReader/commit/53f7dca89927fe36399e752058096dbb3834729b

These should be in v1.8.7.5, which will hopefully be released today. Please let me know if it works!

**Comment by eeque** [comment]
So the update hit my devices ~5 minutes ago. As far as I can tell, everything is working as intended. Single images are opening without extra intervention. Albums that open in the internal browser load fine once you select use HTTPS from the Overflow menu.

Thank you SO much! I only regret that I have but one rating to give RR.
