### ISSUE TITLE
[Enhancement] Navigation directly to user profiles.

### ISSUE THREAD

**Issue by ghost** [QuantumBadger/RedReader#197]
Hello, I would like to hear thoughts regarding the ability to directly navigate to user profiles.

My use case is: I have some users that I like to check in on now and again. Right now, it's cumbersome to go to their profiles; I have to either check a subreddit I know they frequently post in or navigate to "reddit.com/u/<username>" in my browser and select "Open with RedReader".

Functionality wise, I envision this working similarly to the ability to navigate to a custom subreddit (or possibly a modified version of the "My Profile" feature). There would be a button - I'm not quite sure how it would be worded yet - that would allow you to enter a username. Upon success, it would bring up the usual UserProfileDialog which would function exactly as it does now.

If this idea is found to be acceptable, after some discussion and clarification, I would be happy to submit a pull request for this.

**Comment by QuantumBadger** [comment]
Thanks! I agree this would be a useful feature. It could be implemented as follows:

* An extra item in the main menu, similar to "Custom Subreddit", as you suggested. To avoid cluttering up the main menu, this should be toggleable using a preference (similar to the user-specific menu items).
* Or, an extra item in the action-bar menu, present in every activity, called "Go to URL" (or similar). This would just call LinkHandler.onLinkClicked() for the URL the user enters. So, typing "/u/QuantumBadger" would open up my profile, or "/r/aww" would open up that subreddit, etc (the prompt text could provide a simple example of each). This would allow users to use the feature without returning to the main menu. See [OptionsMenuUtility.java](https://github.com/QuantumBadger/RedReader/blob/master/src/main/java/org/quantumbadger/redreader/activities/OptionsMenuUtility.java).

I would be more than happy to accept either (or both) of the above as a pull request :) Let me know if you have any questions.

**Comment by bitbrit** [comment]
Thank you for your great comment and for the OptionsMenuUtility pointer. After some thought, I think that I'm going to focus on the second option listed for now - integrating this functionality into the action bar menu.

I'm still not sure about the wording, but the "Go to URL" phrase that you have suggested is being used right now, though I'm hoping we'll be able to come up with something that more accurately describes this functionality as a standalone interface item. I'll have a think about this and get back to you with possible suggestions.

In regard to questions, thank you; though I have none at this point. Just wanted to commend you, as well as other contributors to the project, for having a codebase that's so easy for new contributors to dive into.

**Comment by QuantumBadger** [comment]
This was added in the last release :)
