### ISSUE TITLE
Pull to refresh

### ISSUE THREAD

**Issue by klenje** [QuantumBadger/RedReader#199]
Hello, I find very useful the pull to refresh gesture, as an alternative to the refresh button. What is your opinion on it? Thanks for your work!

**Comment by QuantumBadger** [comment]
Thanks for the suggestion -- this is something I'm planning to add, but only once the new ListView code is done.

**Comment by engelju** [comment]
Do you have any news on how the new ListView is getting along? I really miss this feature and wouldn't mind helping to implement it :blush:.

**Comment by QuantumBadger** [comment]
> Do you have any news on how the new ListView is getting along?

Since getting rid of HoloEverywhere (and making a few optimisations) the performance is now a lot better, so my ListView rewrite isn't necessary any more :) If you'd like to implement this that would be great -- please let me know if you have any questions.

**Comment by QuantumBadger** [comment]
Done here:

https://github.com/QuantumBadger/RedReader/commit/f27cfaf5ccbfc9f671e3a44e720ee2eb1b226b1b

Should be in Alpha 56, and v1.9.5 :)

**Comment by engelju** [comment]
Yeees, thank you! 😄

**Comment by philipwhiuk** [comment]
Does this work in the Inbox too - on 1.9.4 there's no way to refresh the Inbox without backing out to the menu.

**Comment by QuantumBadger** [comment]
> Does this work in the Inbox too

Posts and comments only I'm afraid. Because the inbox never uses the cache, I didn't think a refresh button was necessary.

Feel free to open a ticket for one if you'd find it useful though :)
