### ISSUE TITLE
Issues with /r/random

### ISSUE THREAD

**Issue by dylanrees** [QuantumBadger/RedReader#200]
I noticed that entering random into the custom subreddit bar produces pecular behavior.  It appears that the app polls /r/random once for the content and once for the title banner.  The result is that the banner and the content wind up coming from two entirely different subreddits.

**Comment by laurencemeynell** [comment]
Also whenever you sort a random subreddit by HOT, NEW etc it seems to grab a completely new random subreddit.

**Comment by daggerstab** [comment]
I'm investigating fixing this and perhaps adding some other randomness-related features, e.g. a "random subreddit" option in the main menu.

**Comment by QuantumBadger** [comment]
@daggerstab -- thanks! There's a half-finished pull request here:

https://github.com/QuantumBadger/RedReader/pull/232

Please let me know if you have any questions about the code :)

**Comment by Weishaupt** [comment]
Same behavior applies to randnsfw.
