### ISSUE TITLE
Very high data usage in background (while on 3G)

### ISSUE THREAD

**Issue by Lesik** [QuantumBadger/RedReader#212]
I feel like I've seen this issue reported here in the past already, but couldn't find it. Maybe I err.

So anyways, I've installed RedReader, **did not modify any settings**, I think I just logged in and that's it. Later I became a SMS from my network operator notifying me that I have reached my data plan **for the month**. 126MB used in the background on 3G connection, that's a whole lot! Caching, preloading and everything is turned off in settings! What could cause this, any ideas?

![hgy6i55](https://cloud.githubusercontent.com/assets/2021487/7168672/7b12404e-e3bf-11e4-810f-ae06d1c6b210.png)

Edit: Vordergrund means foreground, Hintergrund means background.

**Comment by QuantumBadger** [comment]
Which version of RedReader are you using, and which version of Android?

There have been some problems on Android 5.0 detecting WiFi vs 3G, which I assume is the problem.

**Comment by QuantumBadger** [comment]
Assuming you're on Android 5.0, if I gave you the source (or an apk) to a simple app which would debug this, would you be able to provide me with the logcat output?

**Comment by Lesik** [comment]
Sorry I didn't mention the Android version, I thought you could see in the picture. It's CyanogenMod 11, based on Android 4.4.4. I also have a second phone running 4.4.4 (I refuse to update) and have never seen this behaviour in the long time I've been using RedReader.
I am running RedReader 1.8.7.6, which is the latest version available in F-Droid.

What do you mean with being able to provide logcat output? I do have the ability to do so, but the problem stopped occuring. It just occured once, I took a screenshot, and not again (yet).

**Comment by QuantumBadger** [comment]
Just to clarify, you said that precaching was off in the settings, but you also say you haven't changed the settings. Precaching is on by default (for WiFi, and disabled for 3G) -- is this the case?

**Comment by Lesik** [comment]
Yeah, that's what I meant to say.

I do not remember what settings were turned on back then, but I remember that I didn't change any settings so if that's the default then it was like this.

**Comment by QuantumBadger** [comment]
I've put in a fix for this in v1.9.2 -- there was an issue with the precaching preference.
