### ISSUE TITLE
Remove embedded Roboto font

### ISSUE THREAD

**Issue by abn-volk** [QuantumBadger/RedReader#216]
It seems that the app uses an outdated version of Roboto for some elements but uses the device's default font for others. The embedded fonts should be removed.
![demo](https://cloud.githubusercontent.com/assets/1829147/7683927/7fdd5620-fdac-11e4-94f4-c089cb5f65f9.png)

**Comment by QuantumBadger** [comment]
The version of Roboto which is shipped is Roboto-Light. Given that there's no guarantee that a similar "light" font will be on the system, it wouldn't be possible to remove it without potentially breaking the app's design on some phones.

I would be in favour of:

1. Updating the embedded copy of Roboto to the newer version.
2. Embedding all fonts used in the app.
3. Making the choice of font customisable in the settings.

I'll bear (2) and (3) in mind during the current UI rewrite.

**Comment by abn-volk** [comment]
Great, thanks!
