### ISSUE TITLE
ListView bouncing

### ISSUE THREAD

**Issue by Rroia** [QuantumBadger/RedReader#218]
If you scroll up fast enough you can be bounced back down.
https://vid.me/Embl

This happens in both the post list and the comment list.

**Comment by QuantumBadger** [comment]
Very confusing, although it's almost certainly Google's fault :(

v1.9.0 (coming soon) will start to phase in the new v2 ListViews, which shouldn't have this problem.

**Comment by mvdan** [comment]
This happens in other apps too, not RedReader's fault.

**Comment by QuantumBadger** [comment]
From v1.9.5 onwards, the app uses a RecyclerView for the post list. Please re-open if this continues to occur.
