### ISSUE TITLE
Links to comments don't properly direct to the comment

### ISSUE THREAD

**Issue by rschuetzler** [QuantumBadger/RedReader#22]
For example, when browsing /r/bestof on the website, the comment linked pops up to the top. When browsing /r/bestof in RedReader, only the thread pops up. If the linked comment is not the top comment, I have to scroll through a bunch of comments to find the linked comment, if I can find it at all.

**Comment by QuantumBadger** [comment]
Added a while ago :)

**Comment by ptman** [comment]
Yes it was. Thanks!
