### ISSUE TITLE
Character encoding issue in sidebars

### ISSUE THREAD

**Issue by klenje** [QuantumBadger/RedReader#226]
Hi, there are some encoding issues in the sidebar display. This can be seen in /r/france/ and /r/italy/. The issues is with characters like "è", which are not displayed correctly. I don't see any option relative to UTF-8 or similar in the Settings

**Comment by QuantumBadger** [comment]
Fixed:

https://github.com/QuantumBadger/RedReader/commit/eaaac48730759c758698437a574f66d645069a5c
