### ISSUE TITLE
Some gifs not loading properly

### ISSUE THREAD

**Issue by rschuetzler** [QuantumBadger/RedReader#23]
I've had this happen a couple times now. Not sure what causes it to break, but occasionally gifs I load are obscured on the bottom half. The gif will play all the way through with what looks like static in the bottom half. This is on my GS3.

![Screenshot_2013-04-09-08-17-09](https://f.cloud.github.com/assets/600775/357545/815804b4-a129-11e2-8e89-045ed9bfa259.png)

**Comment by QuantumBadger** [comment]
In v1.9.0/1, mp4 files are used instead of GIFs for imgur/gfycat/streamable, and there's a preference for choosing an alternative GIF viewer.
