### ISSUE TITLE
Collapse comment tree via touch gesture

### ISSUE THREAD

**Issue by lightonflux** [QuantumBadger/RedReader#230]
Sorry for the somewhat misleading title. 

The new beta of the mobile reddit site has nice little arrows that allow the user to collapse a comment tree very fast. The same task is somewhat cumbersome in RedReader.

Mobile Beta image: 

![bildschirmfoto vom 2015-08-02 16 31 25](https://cloud.githubusercontent.com/assets/1377943/9026574/18f7bc52-3934-11e5-96f0-d1bf744a3571.png)

In my opinion RedReader should implement the same/similar feature. 

A second level comment has enough space left to it. So i propose that tapping this space will collapse the tree, just like long pressing and choosing the option in the menu would do.

Tapping area highlighted in red: 

![mvrm5pt](https://cloud.githubusercontent.com/assets/1377943/9026588/02dbb508-3935-11e5-94fc-dfe4c2309450.png)

**Comment by QuantumBadger** [comment]
Under Settings > Behaviour > Comment Tap Action, there's an option "Toggle Collapse". If you select this, you can collapse a comment by clicking anywhere on it. Long-clicking will bring up the menu :)
