### ISSUE TITLE
Share comment links use "oauth.reddit.com" domain

### ISSUE THREAD

**Issue by mdaniel** [QuantumBadger/RedReader#245]
Steps:

1. Long-press on a post in the list view
1. Choose "Share comments"
1. Choose a share target (I used Google Keep, but I bet any will do)
1. Observe that the URL is `oauth.reddit.com`

Expected outcome:

The shared link will use `www.reddit.com`

**Comment by QuantumBadger** [comment]
Thanks for the report -- I've put a fix into v1.9.1.

**Comment by mdaniel** [comment]
No, thank _you_ for RedReader; I love it and I appreciate you looking into this!
