### ISSUE TITLE
Music paused when watching gifs with newest beta

### ISSUE THREAD

**Issue by ajs124** [QuantumBadger/RedReader#246]
Hey,

I'm running cyanogenmod 12.1 nightlies on my nexus 5 and since 1.9.0 my music is paused when looking at gifs.

**Comment by QuantumBadger** [comment]
I'm not sure there's anything I can do -- the app uses a VideoView to play GIFs now, and I think Google Play Music detects VideoViews playing anywhere on the system, and pauses the music.

If anyone has any suggestions, please let me know.

**Comment by QuantumBadger** [comment]
Looks like it's necessary to reimplement the VideoView to avoid this:

https://stackoverflow.com/questions/28119955/disable-androids-videoview-requestaudiofocus-when-playing-a-video

**Comment by ajs124** [comment]
I'm using cyanogenmod's built-in player, not google music, but it seems to come down to the same thing.

Sucks that there is no easy solution to this problem… I really like the new GIF viewer much better than the old one.

**Comment by noughtmare** [comment]
[Slide](https://github.com/ccrama/Slide) doesn't pause music when playing gifs. Is it possible to copy their way of playing gifs?

**Comment by QuantumBadger** [comment]
> Slide doesn't pause music when playing gifs. Is it possible to copy their way of playing gifs?

It looks like they've reimplemented the VideoView here:

https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/Views/MediaVideoView.java

The license for Slide is the same as RedReader (GPL v3), so yes, it should be possible to make use of the above code :)

https://github.com/ccrama/Slide/blob/master/license.txt

**Comment by QuantumBadger** [comment]
Fixed in [alpha 46](https://redreader.org/alpha/) thanks to @noughtmare.
