### ISSUE TITLE
External browser is not enforced

### ISSUE THREAD

**Issue by MauroMombelli** [QuantumBadger/RedReader#249]
I've set up the preferences so it should always use external browser for link, ingae,video, and so everything. Sometimes it still open imugr with internal browser.

**Comment by Hund** [comment]
I have the same issue with Imgur. I always forget it so I have to load the image(s) twice. Not that great on a smaller data plan. :(

**Comment by Hund** [comment]
So.. Yeah. Not much has happened here. :/

**Comment by QuantumBadger** [comment]
> So.. Yeah. Not much has happened here. :/

Well, there are over 100 open tickets, and I work on the app unpaid in my free time, so I can't be expected to implement everything :)

The external browser preference is designed for web pages only, and deliberately doesn't affect images/albums/etc. A second preference should be added for those, and it needs to disable image precaching/etc along with the changes to LinkHandler.

**Comment by Hund** [comment]
I know how it works and I do appreciate the work you put into it. But I'd be pleased with just a simple label (like you just did) so it at least got acknowledged. :)

**Comment by QuantumBadger** [comment]
Added -- will be in v1.9.4 :)

**Comment by Hund** [comment]
Great! I'm looking forward to it. :)
