### ISSUE TITLE
"You are doing that too quickly" error treated as success

### ISSUE THREAD

**Issue by greenrd** [QuantumBadger/RedReader#255]
Sometimes my comments do not appear. On the reddit website, aa red error message appears when this happens, saying "you are doing that too fast. Try again in 7 minutes" (the time varies). But in RedReader, the comment posting appears to succeed, but when I refresh or look at my comment history, the comment is not there.

**Comment by QuantumBadger** [comment]
Thanks for the report -- the fix for this will be in v1.9.2.
