### ISSUE TITLE
notification icon on Android 5 appears like a white square instead of an R

### ISSUE THREAD

**Issue by moshpirit** [QuantumBadger/RedReader#262]

**Comment by QuantumBadger** [comment]
I think this is because the "R" in the inverted icon is black, when it should be transparent:

https://github.com/QuantumBadger/RedReader/blob/master/src/main/res/drawable-xhdpi/icon_inv.png

Should be a fairly simple fix hopefully :)

**Comment by moshpirit** [comment]
Cool thanks :)

**Comment by QuantumBadger** [comment]
Fixed a while ago (I forgot to close the ticket :))

**Comment by moshpirit** [comment]
Yeah, thanks! :)
