### ISSUE TITLE
Automatically collapse comments below a certain threshold

### ISSUE THREAD

**Issue by QuantumBadger** [QuantumBadger/RedReader#268]
On reddit.com, a comment is collapsed (and its children hidden) if its score is -4 or lower. The app should do something similar.

**Comment by TheSonAlsoRises** [comment]
Note that the -4 value for comments and submissions can be changed in your reddit account's preferences. Not everyone has it set to the default value.

**Comment by QuantumBadger** [comment]
It looks like the preference value can be accessed via the reddit API:

https://www.reddit.com/dev/api#GET_api_v1_me_prefs

Unfortunately doing this means that the app would regularly have to download the user's reddit prefs, and any changes wouldn't take effect until the next download. So I think the best way would be to add a new local preference to the app.

**Comment by ishults** [comment]
I took a stab at implementing this.  Please let me know if anything needs to be changed/updated (and obviously feel free to make any changes).

**Comment by QuantumBadger** [comment]
Thanks again! Some minor improvements added here: https://github.com/QuantumBadger/RedReader/commit/c7f33f530ed0a639fb3e943389a96f055cbe0475
