### ISSUE TITLE
When viewing/scrolling through an imgur album, playing songs are paused

### ISSUE THREAD

**Issue by jgkamat** [QuantumBadger/RedReader#274]
I'm not sure what would cause this, I'm new to android development...

How to Reproduce:
1. Play a song using google music
2. Open an imgur link
3. Song playing will be paused, as if a video had started playing

I like listening to music while browsing reddit, and I don't want to have it paused every so often.

I'm using the latest version on fdroid

**Comment by ajs124** [comment]
In case you only experience this when looking at gifs, this is probably a duplicate of issue #246

**Comment by jgkamat** [comment]
I'm seeing this when I'm seeing an imgur album, not a gif. It might be the same underlying problem though, I'm running CM as well. Is no one else seeing this?

**Comment by QuantumBadger** [comment]
Thanks for the report. In theory this should only be for GIFs (due to the VideoView). I have no idea why an album would cause this -- do you mean that just bringing up the album listing causes the video to be paused?

**Comment by jgkamat** [comment]
Whoops, this is actually a duplicate of #246, this was actually a gif, it was a very subtle animation. Sorry for wasting you time...

**Comment by QuantumBadger** [comment]
No problem, thanks for the update :)
