### ISSUE TITLE
Intent filter does not pick up subreddit links

### ISSUE THREAD

**Issue by Septolum** [QuantumBadger/RedReader#275]
Whenever there's just a subreddit link (eg Reddit.com/r/all), the only options available to me are browsers, but if it's a comment link then it works fine

**Comment by QuantumBadger** [comment]
That's odd -- it may be that the rules [here](https://github.com/QuantumBadger/RedReader/blob/master/src/main/AndroidManifest.xml#L69) mean that a trailing slash is required. Needs some investigation :)

**Comment by Septolum** [comment]
Just checked, that seems to be the case

**Comment by ishults** [comment]
Removed trailing slashes.  PR is up.

**Comment by QuantumBadger** [comment]
Merged -- thanks!
