### ISSUE TITLE
Error: Comment is no longer visible

### ISSUE THREAD

**Issue by Briscoooe** [QuantumBadger/RedReader#277]
Whenever I vote on a comment within a post, the "Toggle collapse" feature does not work for that comment and a toast is displayed with the message "Error: Comment is no longer visible". For clarification, the comment is visible at all times. When this occurs, only the comment previously voted on cannot be collapsed, all others work fine. If I go back and return to the thread, the original comment can be collapsed successfully.

I often encounter this error at random when attempting to collapse comments, but it is almost a certainty to happen when attempting to toggle a comment that I have voted on.

**Comment by QuantumBadger** [comment]
This is probably fixed by the Material Design changes, which will be in a future release.

**Comment by QuantumBadger** [comment]
The Material Design changes are in master and part of the recent Alpha releases:

https://redreader.org/alpha/
