### ISSUE TITLE
No Way To Reply To Inbox Messages

### ISSUE THREAD

**Issue by nikfrei** [QuantumBadger/RedReader#278]
Clicking, double clicking and long clicking on a PM in inbox does nothing.

Also there are no ways to check sent messages, nor possible to send messages to a username.

**Comment by QuantumBadger** [comment]
Duplicate of https://github.com/QuantumBadger/RedReader/issues/259, but this has more detail, so I'll close the other one :)

**Comment by QuantumBadger** [comment]
Added ability to send PMs to username, and reply to inbox messages.

I'll open a new issue to cover the list of sent messages.
