### ISSUE TITLE
Make it possible to disable inbox replies when commenting

### ISSUE THREAD

**Issue by QuantumBadger** [QuantumBadger/RedReader#286]

**Comment by fhtagn** [comment]
Hey, is this helpful?

- [Reddit post](https://www.reddit.com/r/redditdev/comments/383dy9/way_to_disable_inbox_replies_when_submitting_a/) on how to use the API for that
- [API documentation](https://www.reddit.com/dev/api#POST_api_sendreplies)

**Comment by Clubfan22** [comment]
I'm working on this btw, but I have to tidy it up in the next days before I will commit it.
