### ISSUE TITLE
v.1.9.3, cached subreddit versions don't show up in "Past versions"

### ISSUE THREAD

**Issue by aproposnix** [QuantumBadger/RedReader#288]
[I'm copying this from Reddit - It affects me as well
Issue: No cache available when offline]

> Redreader 1.9.3, cached subreddit versions don't show up in Past versions.
> Also Front Page and All Subreddits. If I downgrade to 1.9.2 without uninstalling some cached versions from 1.9.3 show up and any new cached versions show up correctly.
> This happens with a clean install as well so its not a settings issue.
> Cached comments show up correctly.

**Comment by QuantumBadger** [comment]
Fixed in v1.9.3.1 (which I'll release in the next few hours).
