### ISSUE TITLE
Post author is no longer highlighted

### ISSUE THREAD

**Issue by ishults** [QuantumBadger/RedReader#301]
This makes it tough for AMAs, etc. to keep track of the post author's responses.

The problem appears to be that line 227 in `CommentListingFragment.java`:

`mPost != null ? mPost.src.getAuthor() : "");`

`mPost` is always `null`.

**Comment by QuantumBadger** [comment]
Is this not still an issue in master? I think it's a regression for all the Material Design stuff I added.

**Comment by ishults** [comment]
Oh it may be.  I closed it because I had forgotten I was running master locally and didn't want to log it in case things may still change. I can check and reopen later today.

**Comment by ishults** [comment]
Ok, yep, still an issue in master.

**Comment by QuantumBadger** [comment]
Fixed :)
