### ISSUE TITLE
LinkDetailsView intended consequence

### ISSUE THREAD

**Issue by veyndan** [QuantumBadger/RedReader#320]
I've been looking into converting `LinkDetailsView` into xml, but have a  question on the intended outcome of overriding `onInterceptTouchEvent()`. It appears that when you click on it the border highlights blue and when you come back from the link, it stays blue. However as it is in a `RecyclerView` it reverts back to the default grey colour when you scroll down and up again. So is this supposed to just be like a `selector` where you highlight the box on button hold and then reverts back, or something else? The method in question is [here](https://github.com/QuantumBadger/RedReader/blob/master/src/main/java/org/quantumbadger/redreader/views/LinkDetailsView.java#L86).

**Comment by QuantumBadger** [comment]
> So is this supposed to just be like a selector where you highlight the box on button hold and then reverts back

Yes -- when you release your finger it's supposed to stop being blue. In my experience it rarely does :)

**Comment by veyndan** [comment]
A selector shouldn't be too hard to implement then, and that class can be converted to pure xml (I believe).

**Comment by veyndan** [comment]
What's your opinion on ditching the highlighted blue border around the view and just use the standard ripple effect instead?

**Comment by QuantumBadger** [comment]
> What's your opinion on ditching the highlighted blue border around the view and just use the standard ripple effect instead?

Sounds good to me :)
