### ISSUE TITLE
Language setting override does not always work

### ISSUE THREAD

**Issue by ajs124** [QuantumBadger/RedReader#336]
The very useful feature that was tracked in #40 and is available since version 1.7 is sadly not consistent in every view.

My device is set to German and RedReader to English, which works most of the time, but sadly not always.

Sometimes some of the the dialogs and menus are seemingly randomly displayed in German. I'm suspecting that it might be related to using mutliple accounts and switching between them, but I have not done enough structured testing to be certain about that.

**Comment by QuantumBadger** [comment]
Just a guess, but maybe this is due to some string lookups using the Application context rather than the Activity context? If so this shouldn't be too hard to fix.

**Comment by QuantumBadger** [comment]
I can't reproduce this locally unfortunately, but I have seen this in the past.

I've put a potential fix into the latest alpha (28) -- please let me know if the issue still occurs with that!

https://redreader.org/alpha/

**Comment by ajs124** [comment]
The error still occurs, see here: 
![m6mosxg](https://cloud.githubusercontent.com/assets/1229027/16333089/b1bb36fa-39f9-11e6-8ca1-7523f70f8dee.png)
![yr3piug](https://cloud.githubusercontent.com/assets/1229027/16333090/b1bfcb52-39f9-11e6-861f-19a906813e20.png)

Plus I can't submit comments with the newest alpha and there seems to be an off by one related to the "more comments" thing: https://i.imgur.com/aR5T9wh.png. Should I create separate issues for those?

**Comment by QuantumBadger** [comment]
I think this is just due to the translations being incomplete, which is sadly unavoidable as they're community-sourced.
