### ISSUE TITLE
Using a [foss] translation website to manage translations.

### ISSUE THREAD

**Issue by DistantParadox** [QuantumBadger/RedReader#337]
I found that using [Weblate](https://weblate.org/en/) worked very well for translating another open source app (Red Moon, also on F-Droid).  This could work well for Red Reader too, since it greatly simplifies the translation process instead of doing everything manually.  It also allows sign-in with your Github account, is [free, open source software](https://docs.weblate.org/en/latest/license.html) itself, and has free continuous translation hosting for free software.  If there is interest, project hosting can be requested [here](https://hosted.weblate.org/hosting/) after your account has been created or linked with github.

**Comment by QuantumBadger** [comment]
Thanks, this seems like a good idea! I'll look into this.

**Comment by TheLastProject** [comment]
I maintain Weblate for the AsteroidOS project (as in, set things up on the Hosted instance for them) and also use it for translations for my own desktop app (Pext). Feel free to message me if you need any help with using or setting up Weblate or just if you have questions about it, I'd be happy to help :)

**Comment by QuantumBadger** [comment]
Thanks, I've just sent off a hosting request.

**Comment by QuantumBadger** [comment]
All set up now, and added to the README :)

https://hosted.weblate.org/projects/redreader/strings/
