### ISSUE TITLE
Update app in Google Play

### ISSUE THREAD

**Issue by veyndan** [QuantumBadger/RedReader#338]
Though I build the app from source, the Google Play listing hasn't been updated for quite awhile. This can be beneficial as bugs in the app will become more apparent with more users.

**Comment by DistantParadox** [comment]
Last time it was updated was April 2nd, so I'd agree that it's due for an update.

**Comment by QuantumBadger** [comment]
Yep, well aware of this! I only put releases on Google Play/F-Droid when they're fully stable, with no known regressions. But due to the Material Design changes there are lots of things still to fix.

**Comment by QuantumBadger** [comment]
v1.9.4 released :)
