### ISSUE TITLE
Misreporting of disk space problems

### ISSUE THREAD

**Issue by dylanrees** [QuantumBadger/RedReader#339]
I notice that when RedReader is trying to load content but the phone is out of disk space, it will throw several notifications of "parse error - Reddit sent some information I couldn't understand" before finally correctly reporting that the phone has run out of disk space.

**Comment by QuantumBadger** [comment]
You can get a full stack trace by tapping the error message -- if you see this again please could you open the stack trace and send me a screenshot?

**Comment by dylanrees** [comment]
Just got it again.  Here's the stack trace: 

Exception: java.io.IOException write failed: ENOSPC (No space left on device) libcore.io.IoBridge.write(IoBridge.java:455) java.io.FileOutputStream.write(FileOutputStream.java:187) java.io.BufferedOutputStream.write(BufferedOutputStream.java:174) java.io.FilterOutputStream.write(FilterOutputStream.java:129) java.io.FilterOutputStream.write(FilterOutputStream.java:114) org.quantumbadger.redreader.cache.CachingInputStream.read(CachingInputStream.java:80) java.io.InputStream.read(InputStream.java:162) java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142) java.io.BufferedInputStream.read(BufferedInputStream.java:288) com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:207) com.fasterxml.jackson.core.base.ParserBase.loadMoreGuaranteed(ParserBase.java:505) com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2449) com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2429) com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getValueAsString(UTF8StreamJsonParser.java:334) org.quantumbadger.redreader.jsonwrap.JsonValue.<init>(JsonValue.java:200) org.quantumbadger.redreader.jsonwrap.JsonValue.<init>(JsonValue.java:67) org.quantumbadger.redreader.jsonwrap.JsonBufferedObject.buildBuffered(JsonBufferedObject.java:53) org.quantumbadger.redreader.jsonwrap.JsonBuffered.build(JsonBuffered.java:118) org.quantumbadger.redreader.jsonwrap.JsonValue.buildInThisThread(JsonValue.java:238) org.quantumbadger.redreader.jsonwrap.JsonBufferedArray.buildBuffered(JsonBufferedArray.java:52) org.quantumbadger.redreader.jsonwrap.JsonBuffered.build(JsonBuffered.java:118) org.quantumbadger.redreader.jsonwrap.JsonValue.buildInThisThread(JsonValue.java:238) org.quantumbadger.redreader.jsonwrap.JsonBufferedObject.buildBuffered(JsonBufferedObject.java:60) org.quantumbadger.redreader.jsonwrap.JsonBuffered.build(JsonBuffered.java:118) org.quantumbadger.redreader.jsonwrap.JsonValue.buildInThisThread(JsonValue.java:238) org.quantumbadger.redreader.jsonwrap.JsonBufferedObject.buildBuffered(JsonBufferedObject.java:60) org.quantumbadger.redreader.jsonwrap.JsonBuffered.build(JsonBuffered.java:118) org.quantumbadger.redreader.jsonwrap.JsonValue.buildInThisThread(JsonValue.java:238) org.quantumbadger.redreader.jsonwrap.JsonBufferedObject.buildBuffered(JsonBufferedObject.java:60) org.quantumbadger.redreader.jsonwrap.JsonBuffered.build(JsonBuffered.java:118) org.quantumbadger.redreader.jsonwrap.JsonValue.buildInThisThread(JsonValue.java:238) org.quantumbadger.redreader.jsonwrap.JsonBufferedArray.buildBuffered(JsonBufferedArray.java:52) org.quantumbadger.redreader.jsonwrap.JsonBuffered.build(JsonBuffered.java:118) org.quantumbadger.redreader.jsonwrap.JsonValue.buildInThisThread(JsonValue.java:238) org.quantumbadger.redreader.jsonwrap.JsonBufferedObject.buildBuffered(JsonBufferedObject.java:60) org.quantumbadger.redreader.jsonwrap.JsonBuffered.build(JsonBuffered.java:118) org.quantumbadger.redreader.jsonwrap.JsonValue.buildInThisThread(JsonValue.java:238) org.quantumbadger.redreader.jsonwrap.JsonBufferedObject.buildBuffered(JsonBufferedObject.java:60) org.quantumbadger.redreader.jsonwrap.JsonBuffered.build(JsonBuffered.java:118) org.quantumbadger.redreader.jsonwrap.JsonValue.buildInThisThread(JsonValue.java:238) org.quantumbadger.redreader.cache.CacheDownload$2.onSuccess(CacheDownload.java:178) org.quantumbadger.redreader.http.okhttp.OKHTTPBackend$1.executeInThisThread(OKHTTPBackend.java:110) org.quantumbadger.redreader.cache.CacheDownload.performDownload(CacheDownload.java:130) org.quantumbadger.redreader.cache.CacheDownload.doDownload(CacheDownload.java:85) org.quantumbadger.redreader.cache.CacheDownloadThread.run(CacheDownloadThread.java:36) Caused by: Exception: libcore.io.ErrnoException write failed: ENOSPC (No space left on device) libcore.io.Posix.writeBytes(Native Method) libcore.io.Posix.write(Posix.java:202) libcore.io.BlockGuardOs.write(BlockGuardOs.java:197) libcore.io.IoBridge.write(IoBridge.java:450) java.io.FileOutputStream.write(FileOutputStream.java:187) java.io.BufferedOutputStream.write(BufferedOutputStream.java:174) java.io.FilterOutputStream.write(FilterOutputStream.java:129) java.io.FilterOutputStream.write(FilterOutputStream.java:114) org.quantumbadger.redreader.cache.CachingInputStream.read(CachingInputStream.java:80) java.io.InputStream.read(InputStream.java:162)

**Comment by QuantumBadger** [comment]
Resolved with the SAF changes and FAT files-per-directory workaround.
