### ISSUE TITLE
Drop "Beta" from the name

### ISSUE THREAD

**Issue by mvdan** [QuantumBadger/RedReader#344]
I was just wondering - why is Beta still in the name? It's clearly not beta software to me. Sure it's missing some features other clients have, but it's by no means an unfinished or unstable app.

I worry that some users might prefer other apps thinking that this one isn't ready for regular use.

**Comment by QuantumBadger** [comment]
Agreed -- I'm considering removing it in the next version.

**Comment by reddit-is-fun** [comment]
Beta tag shiuld stay as long asediting self posts isn't possible.

**Comment by mvdan** [comment]
@reddit-is-fun There will always be features that the web UI and API offers that RedReader may not have yet. This is no reason to keep the beta. Following your logic, all apps should be pre-release until all features and enhancements are done.

**Comment by QuantumBadger** [comment]
Removed -- it'll be gone in v1.9.5. I've also removed it from the Google Play store listing.

@mvdan -- is there anything to do from F-Droid's perspective, or will the name change automatically be detected?

**Comment by QuantumBadger** [comment]
Closing as v1.9.5 is now released with "Beta" gone.
