### ISSUE TITLE
Toolbar/ActionBar is wrong size

### ISSUE THREAD

**Issue by mateoeh** [QuantumBadger/RedReader#345]
https://material.google.com/layout/metrics-keylines.html#metrics-keylines-keylines-spacing

Commit 319398e overrode `attr/actionBarSize` and set it to 48dp, but Toolbars should be 56dp tall according to design guidelines. The Toolbar ends up looking awkwardly small compared to other applications.

**Comment by QuantumBadger** [comment]
Thanks for the report. This is intentional, mainly as a workaround for Android sometimes failing to resize the action bar when the orientation changes -- the current size works in both portrait and landscape. I also find the Material action bar too big in general! (and too small in landscape)
