### ISSUE TITLE
Music is paused when playing gifs

### ISSUE THREAD

**Issue by noughtmare** [QuantumBadger/RedReader#348]
I like to browse reddit while listening to music, but my music gets paused everytime I open a gif in redreader.

**Comment by abn-volk** [comment]
The developer said that it's not possible to fix this because the app uses VideoView to play GIF and by default Android pauses music when it detects a video is running: #246

**Comment by QuantumBadger** [comment]
It's possible, but it requires a huge amount of work (to reimplement the VideoView manually).

Closing as a duplicate.
