### ISSUE TITLE
Padding around EditText is too small

### ISSUE THREAD

**Issue by abn-volk** [QuantumBadger/RedReader#349]
The EditText in Custom Subreddit dialogue should have more horizontal padding (probably 16dp):
![screenshot_20160713-175912_1](https://cloud.githubusercontent.com/assets/1829147/16801228/9d788e66-4923-11e6-944f-facb944e2ee0.jpg)

See Google Drive's dialogue for example: 
![screenshot_20160713-175243_1](https://cloud.githubusercontent.com/assets/1829147/16801161/49dd4940-4923-11e6-9c65-df5b68db890c.jpg)

**Comment by QuantumBadger** [comment]
Agreed!
