### ISSUE TITLE
Add ripple effect to post and comment items

### ISSUE THREAD

**Issue by abn-volk** [QuantumBadger/RedReader#350]
Posts and comments should have a ripple effect like the items in the subreddit list. This could be done by setting `android:background` or `android:foreground` to `"?attr/selectableItemBackground"`, which will show the effect on Lollipop and above.

**Comment by QuantumBadger** [comment]
I prefer a non-animated, immediate change of background colour (similar to how the post list is now). The Material ripple feels laggy and unresponsive by comparison.
