### ISSUE TITLE
clarification of preference: behaviour/minimum comment score

### ISSUE THREAD

**Issue by jawz101** [QuantumBadger/RedReader#357]
The setting defaults to negative 4 (-4).  Then says that a value of zero disables the function.

If I want to hide all comments with less than 5 votes do I set the preference to 5 or -5?

**Comment by jawz101** [comment]
... I don't understand the reasoning or purpose of having a negative integer as a default value.  The maths should be 0 and higher, but not negatives.

**Comment by QuantumBadger** [comment]
It's not the number of votes, it's the total score :)

So if a comment has 4 upvotes and 10 downvotes, it has a score of -6. This is below the default threshold of -4, so it will be hidden.

**Comment by jawz101** [comment]
So if I did put it at 5, if the total score is a 3 it will be hidden, correct?  Thanks

**Comment by QuantumBadger** [comment]
> So if I did put it at 5, if the total score is a 3 it will be hidden

Yes, that's correct :)
