### ISSUE TITLE
New custom subreddit field breaks swipe keyboards

### ISSUE THREAD

**Issue by Riotism** [QuantumBadger/RedReader#359]
In version 1.9.4, the custom subreddit field from the default front page disallows any spaces. Since swipe keyboards automatically insert spaces after words (by default), the field behavior forces swipe keyboard users to manually type words instead of swiping. This is not a problem for users only typing out one word, since swipe keyboards do not insert a space after the first word unless another word is inputted. I think it's better to revert back to the old behavior where spaces are allowed, but automatically stripped on submission.

**Comment by QuantumBadger** [comment]
What happens when you try to enter words -- does the text just not appear?

In theory it shouldn't have any effect -- the spaces should just be removed whenever the text changes:

					@Override
					public void afterTextChanged(Editable s) {
						if (s.toString().contains(" ")) {
							String result = s.toString().replaceAll(" ", "");

							editText.setText(result);
							editText.setSelection(result.length());
						}
					}

**Comment by Riotism** [comment]
Yes - the text doesn't appear. I have tried this with the AOSP google keyboard and also with the samsung keyboard. The google keyboard cannot type any word after the first but the samsung keyboard types out every second word. So I don't think it has to do with spaces but keyboard behavior

**Comment by Riotism** [comment]
Fixed in 1.9.6.
