### ISSUE TITLE
[feature request] Sort user posts and comments like subbreddits (New, top, controversial)

### ISSUE THREAD

**Issue by japanesephundroid** [QuantumBadger/RedReader#362]

**Comment by japanesephundroid** [comment]
Thanks QuantumBadger :), I tested this now, however as gaudecker says at the start of #440, this partially fixes this, it only fixes sorting posts.

Comments cannot be sorted. I can open a new issue if you want.

**Comment by QuantumBadger** [comment]
Sorry, I didn't realise this ticket had been closed (I think GitHub did it automatically). I'll re-open for the comment sorting.

**Comment by japanesephundroid** [comment]
>Sorry, I didn't realise this ticket had been closed (I think GitHub did it automatically). I'll re-open for the comment sorting.

No need to be sorry man, I just thought you missed the comment sorting part.

On a site note I have dealt with or watched interactions with developers and you are by far the nicest, almost too nice :)

**Comment by QuantumBadger** [comment]
Thanks :D

@gaudecker has just submitted a PR for comment sorting, which should be merged soon.

**Comment by japanesephundroid** [comment]
>@gaudecker has just submitted a PR for comment sorting, which should be merged soon.

👍

**Comment by QuantumBadger** [comment]
Closed for good this time :) Should be in Alpha 109 in a few minutes.

**Comment by japanesephundroid** [comment]
Thanks, I tested it now, it works :)
