### ISSUE TITLE
[feature request] Delete images and videos from cache

### ISSUE THREAD

**Issue by japanesephundroid** [QuantumBadger/RedReader#366]
I use your app a lot and the cache usage in android goes up to 1-1,5 GB. I want to clean it sometimes but I don't because I want to keep the cached posts/listings. An option in the settings in the cache section for this would be great.

Sorry for posting all of these feature requests at once, [I posted most of them on the subreddit](https://www.reddit.com/r/RedReader/comments/4nje7r/feature_requests_4_small_features_i_have_been/) about a month ago but you probably missed that post :)

**Comment by QuantumBadger** [comment]
> Sorry for posting all of these feature requests at once

Not a problem, I lose track of all these requests unless they're on here :)
