### ISSUE TITLE
[Feature Request] Chrome Custom Tabs

### ISSUE THREAD

**Issue by Septolum** [QuantumBadger/RedReader#368]
Add the option to use chrome custom tabs instead of the internal browser if chrome is installed

**Comment by Cj-Malone** [comment]
I'm currently writing a patch to do this, it seems to be working fine with Firefox I've not tested Chrome but I expect it should work. I suspect one hiccup is that when no custom tab applications are installed it would launch an external browser and not fall back on WebViewActivity. Although I'm pretty sure Google requires OEMs to ship Chrome, so I don't know how many users wont have one installed.

```
diff --git a/src/main/java/org/quantumbadger/redreader/common/LinkHandler.java b/src/main/java/org/quantumbadger/redreader/common/LinkHandler.java
index 8dc82d3..3cd5aee 100644
--- a/src/main/java/org/quantumbadger/redreader/common/LinkHandler.java
+++ b/src/main/java/org/quantumbadger/redreader/common/LinkHandler.java
@@ -26,6 +26,8 @@ import android.content.Intent;
 import android.content.SharedPreferences;
 import android.content.pm.ResolveInfo;
 import android.net.Uri;
+import android.os.Build;
+import android.os.Bundle;
 import android.os.Handler;
 import android.os.Parcelable;
 import android.preference.PreferenceManager;
@@ -168,9 +170,20 @@ public class LinkHandler {
 				}
 
 				case INTERNAL_BROWSER: {
-					final Intent intent = new Intent(activity, WebViewActivity.class);
-					intent.putExtra("url", url);
-					intent.putExtra("post", post);
+					final Intent intent = new Intent();
+					if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
+						intent.setAction(Intent.ACTION_VIEW);
+						intent.setData(Uri.parse(url));
+						intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
+
+						Bundle bundle = new Bundle();
+						bundle.putBinder("android.support.customtabs.extra.SESSION", null);
+						intent.putExtras(bundle);
+					} else {
+						intent.setClass(activity, WebViewActivity.class);
+						intent.putExtra("url", url);
+						intent.putExtra("post", post);
+					}
 					activity.startActivity(intent);
 					return;
 				}
@@ -238,9 +251,21 @@ public class LinkHandler {
 			}
 		}
 
-		final Intent intent = new Intent(activity, WebViewActivity.class);
-		intent.putExtra("url", url);
-		intent.putExtra("post", post);
+		final Intent intent = new Intent();
+		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
+			intent.setAction(Intent.ACTION_VIEW);
+			intent.setData(Uri.parse(url));
+			intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
+
+			Bundle bundle = new Bundle();
+			bundle.putBinder("android.support.customtabs.extra.SESSION", null);
+			intent.putExtras(bundle);
+		} else {
+			intent.setClass(activity, WebViewActivity.class);
+			intent.putExtra("url", url);
+			intent.putExtra("post", post);
+		}
+
 		activity.startActivity(intent);
 	}
 
 ```

**Comment by QuantumBadger** [comment]
Thank you! I didn't realise custom tabs would work with Firefox too. Couple of points:

* It would be good to have a preference for this, so users can disable it if needed
* The current internal browser destroys cookies when it closes -- is there a way to have the custom tabs session open in "private mode"?
* Also, the current internal browser has some options in the three-dots menu in the top corner (enable HTTPS, share, etc) -- are these available with custom tabs?

**Comment by Cj-Malone** [comment]
Yeah, Firefox 57+ can do custom tabs, I've only heard of it and Chrome implementing it, but it's possible there are more browsers out there.

1. A preference wouldn't be to hard, I've not got that much Android experience but I could do that.
2. I don't think so, unless it's undocumented. It also get added to Firefox history (can't comment on Chrome)
3. Share could be added easily, open the **original** link as https could be added but RedReader wouldn't get any future URLs when the user changes page.

There is also a support library that builds the intent for us, I think it's a bit excessive when we can do it so easily, but I'll leave that up to you.

**Comment by Cguy7777** [comment]
@QuantumBadger Since this has been added, we can probably close this.
