### ISSUE TITLE
Pinned subreddits are sorted by date added

### ISSUE THREAD

**Issue by japanesephundroid** [QuantumBadger/RedReader#372]
Is this intended behaviour? Sort by name seems like a better option.

**Comment by QuantumBadger** [comment]
PR merged in.

**Comment by japanesephundroid** [comment]
Is the fix in **Alpha 71*? I tested it and the bug is still there.

**Comment by QuantumBadger** [comment]
Nope, but I've just triggered Alpha 72, which has it in :)

**Comment by QuantumBadger** [comment]
And Alpha 73 will be here in a few moments with a bugfix :P

**Comment by japanesephundroid** [comment]
Thanks, Alpha 73 works for me :)

**Comment by Symbian9** [comment]
I still has issue with sorting of [pinned subreddits](https://github.com/QuantumBadger/RedReader/issues/568) in alphabetical order in *RedReader* `v1.9.10`.

It still sorted in by date pinned.
