### ISSUE TITLE
Add option to disable pull-to-refresh (or just remove it)

### ISSUE THREAD

**Issue by ShadowNinja** [QuantumBadger/RedReader#379]
I often refresh things accidentally when simply scrolling up.  The refresh button is easy to access, so I don't personally find pull-to-refresh particularly useful anyways.

**Comment by ajs124** [comment]
I like the feature… So I'm against removal, but an option is obviously no problem for me.

**Comment by QuantumBadger** [comment]
I'll add an option :)

**Comment by QuantumBadger** [comment]
Added here: https://github.com/QuantumBadger/RedReader/commit/e17dab7144b039b18c9cde726c793c13443e6732
