### ISSUE TITLE
Force close since 2016-09-09 Reddit update

### ISSUE THREAD

**Issue by L-P** [QuantumBadger/RedReader#384]
Using RedReader 1.9.5.1 from F-Droid.

Reddit update: https://www.reddit.com/r/changelog/comments/51u5gj/reddit_change_new_thumbnail_art_expando_art_and/

Steps to reproduce:
1. Try to browse any subreddit or /r/all
2. Crash

Exception:
```
E/AndroidRuntime(14646): FATAL EXCEPTION: Request Handler Thread
E/AndroidRuntime(14646): Process: org.quantumbadger.redreader, PID: 14646
E/AndroidRuntime(14646): java.lang.IllegalArgumentException: unexpected url: image
E/AndroidRuntime(14646): 	at com.squareup.okhttp.Request$Builder.url(Request.java:163)
E/AndroidRuntime(14646): 	at org.quantumbadger.redreader.http.okhttp.OKHTTPBackend.prepareRequest(OKHTTPBackend.java:91)
E/AndroidRuntime(14646): 	at org.quantumbadger.redreader.cache.CacheDownload.<init>(CacheDownload.java:65)
E/AndroidRuntime(14646): 	at org.quantumbadger.redreader.cache.PrioritisedDownloadQueue.add(PrioritisedDownloadQueue.java:41)
E/AndroidRuntime(14646): 	at org.quantumbadger.redreader.cache.CacheManager$RequestHandlerThread.queueDownload(CacheManager.java:405)
E/AndroidRuntime(14646): 	at org.quantumbadger.redreader.cache.CacheManager$RequestHandlerThread.handleRequest(CacheManager.java:374)
E/AndroidRuntime(14646): 	at org.quantumbadger.redreader.cache.CacheManager$RequestHandlerThread.run(CacheManager.java:337)
```

**Comment by jeetsee** [comment]
I am also seeing this with 1.9.5.1 on Android 6.0.1 (CM13) as of 2016-09-08.   My RedReader is set up to proxy through Tor using OrBot's per app Transparent Proxying (rooted) rather than the built in option in RedReader, though I did test without Tor and it was same issue.

I had been browsing /r/all with no problems for maybe 30 minutes when I suddenly get the `Unfortunately RedReader has stopped` error.   I restarted RedReader and any time I tried to browser `all` or `front page` it would crash.    I switched to anonymous user and I could browse both fine, I switched back to my account and I could browse both for maybe 2 minutes and then it started to crash again. 

* I cleared app cache and the issue persisted
* I cleared app data and could browse frontpage as anonymous but the issue persisted for all
* I re-added my account and the issue persisted for both frontpage and all

output from `CatLog`

    09-08 15:31:21.313 I/ActivityManager(2109): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.quantumbadger.redreader/.activities.MainActivity bnds=[810,1368][1080,1692] (has extras)} from uid 10094 on display 0
    09-08 15:31:21.402 I/ActivityManager(2109): Start proc 12726:org.quantumbadger.redreader/u0a83 for activity org.quantumbadger.redreader/.activities.MainActivity
    09-08 15:31:21.592 W/System  (12726): ClassLoader referenced unknown path: /data/app/org.quantumbadger.redreader-1/lib/arm
    09-08 15:31:21.596 I/RedReader(12726): Application created.
    09-08 15:31:21.893 I/RedditChangeDataIO(12726): Running initial read...
    09-08 15:31:21.908 I/RedditChangeDataIO(12726): Data file at '/data/user/0/org.quantumbadger.redreader/files/rr_change_data.dat'
    09-08 15:31:21.909 I/RedditChangeDataManager(12726): Reading from stream...
    09-08 15:31:21.909 I/RedditChangeDataManager(12726): 2 users to read.
    09-08 15:31:21.909 I/RedditChangeDataManager(12726): Reading 111 entries for user 'MYNICKNAME'
    09-08 15:31:21.911 I/RedditChangeDataManager(12726): Getting account...
    09-08 15:31:21.913 E/AlarmManagerService(2109): Unable to set alarm to 1473401700.000000000: Invalid argument
    09-08 15:31:21.921 I/RedditChangeDataManager(12726): Finished inserting entries for user 'MYNICKNAME'
    09-08 15:31:21.922 I/RedditChangeDataManager(12726): Reading 0 entries for user ''
    09-08 15:31:21.922 I/RedditChangeDataManager(12726): Getting account...
    09-08 15:31:21.922 I/RedditChangeDataManager(12726): Finished inserting entries for user ''
    09-08 15:31:21.922 I/RedditChangeDataManager(12726): All entries read from stream.
    09-08 15:31:21.922 I/RedditChangeDataIO(12726): Initial read successful.
    09-08 15:31:21.922 I/RedditChangeDataManager(12726): Pruning for all users...
    09-08 15:31:21.922 I/RedditChangeDataManager(12726): Pruning complete.
    09-08 15:31:21.935 I/RedReader(12726): Checking for new messages.
    09-08 15:31:22.003 I/AppCompatViewInflater(12726): app:theme is now deprecated. Please move to using android:theme instead.
    09-08 15:31:22.105 D/OpenGLRenderer(12726): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
    09-08 15:31:22.183 I/Adreno-EGL(12726): <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, xxxxxxx, xxxxxxxxxx
    09-08 15:31:22.194 I/OpenGLRenderer(12726): Initialized EGL, version 1.4
    09-08 15:31:22.303 I/CacheManager(12726): Pruning 0 files
    09-08 15:31:22.381 I/ActivityManager(2109): Displayed org.quantumbadger.redreader/.activities.MainActivity: +991ms
    09-08 15:31:23.586 D/AudioService(2109): Stream muted, skip playback
    09-08 15:31:23.590 I/ActivityManager(2109): START u0 {dat=https://oauth.reddit.com/... cmp=org.quantumbadger.redreader/.activities.PostListingActivity} from uid ZZZZZ on display 0
    09-08 15:31:23.627 I/AppCompatViewInflater(12726): app:theme is now deprecated. Please move to using android:theme instead.
    09-08 15:31:23.777 I/PostListingFragment(12726): Precaching images: ON
    09-08 15:31:23.778 I/PostListingFragment(12726): Precaching comments: ON
    09-08 15:31:23.835 I/ActivityManager(2109): Displayed org.quantumbadger.redreader/.activities.PostListingActivity: +230ms
    09-08 15:31:23.894 D/OpenGLRenderer(12726): endAllStagingAnimators on 0xaee04d80 (ListView) with handle 0x9ee3e4d0
    09-08 15:31:24.182 I/getImgurImageInfo(12726): Image 6FeqMy9: trying API v3 with auth
    09-08 15:31:24.190 I/getImgurImageInfo(12726): Image SAkZ0C4: trying API v3 with auth
    09-08 15:31:24.199 I/PostListingFragment(12726): Successfully precached https://oauth.reddit.com/comments/51t35x/.json?sort=confidence
    09-08 15:31:24.241 I/getImgurImageInfo(12726): Image w3BxNHe: trying API v3 with auth
    09-08 15:31:24.284 I/getImgurImageInfo(12726): Image SfinHsk: trying API v3 with auth
    09-08 15:31:24.321 W/System.err(12726): java.lang.IllegalArgumentException: unexpected url: image
    09-08 15:31:24.321 W/System.err(12726): 	at com.squareup.okhttp.Request$Builder.url(Request.java:163)
    09-08 15:31:24.321 W/System.err(12726): 	at org.quantumbadger.redreader.http.okhttp.OKHTTPBackend.prepareRequest(OKHTTPBackend.java:91)
    09-08 15:31:24.321 W/System.err(12726): 	at org.quantumbadger.redreader.cache.CacheDownload.<init>(CacheDownload.java:65)
    09-08 15:31:24.321 W/System.err(12726): 	at org.quantumbadger.redreader.cache.PrioritisedDownloadQueue.add(PrioritisedDownloadQueue.java:41)
    09-08 15:31:24.321 W/System.err(12726): 	at org.quantumbadger.redreader.cache.CacheManager$RequestHandlerThread.queueDownload(CacheManager.java:405)
    09-08 15:31:24.321 W/System.err(12726): 	at org.quantumbadger.redreader.cache.CacheManager$RequestHandlerThread.handleRequest(CacheManager.java:374)
    09-08 15:31:24.321 W/System.err(12726): 	at org.quantumbadger.redreader.cache.CacheManager$RequestHandlerThread.run(CacheManager.java:337)
    09-08 15:31:24.323 I/getImgurImageInfo(12726): Image VQxJ4hM: trying API v3 with auth
    09-08 15:31:24.338 E/AndroidRuntime(12726): FATAL EXCEPTION: Request Handler Thread
    09-08 15:31:24.338 E/AndroidRuntime(12726): Process: org.quantumbadger.redreader, PID: 12726
    09-08 15:31:24.338 E/AndroidRuntime(12726): Theme: themes:{}
    09-08 15:31:24.338 E/AndroidRuntime(12726): java.lang.IllegalArgumentException: unexpected url: image
    09-08 15:31:24.338 E/AndroidRuntime(12726): 	at com.squareup.okhttp.Request$Builder.url(Request.java:163)
    09-08 15:31:24.338 E/AndroidRuntime(12726): 	at org.quantumbadger.redreader.http.okhttp.OKHTTPBackend.prepareRequest(OKHTTPBackend.java:91)
    09-08 15:31:24.338 E/AndroidRuntime(12726): 	at org.quantumbadger.redreader.cache.CacheDownload.<init>(CacheDownload.java:65)
    09-08 15:31:24.338 E/AndroidRuntime(12726): 	at org.quantumbadger.redreader.cache.PrioritisedDownloadQueue.add(PrioritisedDownloadQueue.java:41)
    09-08 15:31:24.338 E/AndroidRuntime(12726): 	at org.quantumbadger.redreader.cache.CacheManager$RequestHandlerThread.queueDownload(CacheManager.java:405)
    09-08 15:31:24.338 E/AndroidRuntime(12726): 	at org.quantumbadger.redreader.cache.CacheManager$RequestHandlerThread.handleRequest(CacheManager.java:374)
    09-08 15:31:24.338 E/AndroidRuntime(12726): 	at org.quantumbadger.redreader.cache.CacheManager$RequestHandlerThread.run(CacheManager.java:337)
    09-08 15:31:24.345 W/ActivityManager(2109):   Force finishing activity org.quantumbadger.redreader/.activities.PostListingActivity
    09-08 15:31:24.353 I/getImgurImageInfo(12726): Image SGjJ2tG: trying API v3 with auth
    09-08 15:31:24.384 I/getImgurImageInfo(12726): Image s2lj7bI: trying API v3 with auth
    09-08 15:31:24.394 I/getImgurImageInfo(12726): Image hBfQspf: trying API v3 with auth
    09-08 15:31:24.432 I/OpenGLRenderer(2109): Initialized EGL, version 1.4
    09-08 15:31:25.014 W/SurfaceFlinger(223): couldn't log to binary event log: overflow.
    09-08 15:31:25.793 D/AudioService(2109): Stream muted, skip playback
    09-08 15:31:25.797 I/Process (12726): Sending signal. PID: 12726 SIG: 9
    09-08 15:31:25.817 D/OpenGLRenderer(2109): endAllStagingAnimators on 0x9ab37a00 (RippleDrawable) with handle 0x9b3f8fa0
    09-08 15:31:25.839 W/InputDispatcher(2109): channel '34256d8 org.quantumbadger.redreader/org.quantumbadger.redreader.activities.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
    09-08 15:31:25.839 E/InputDispatcher(2109): channel '34256d8 org.quantumbadger.redreader/org.quantumbadger.redreader.activities.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
    09-08 15:31:25.842 D/GraphicsStats(2109): Buffer count: 11
    09-08 15:31:25.842 I/WindowState(2109): WIN DEATH: Window{34256d8 u0 org.quantumbadger.redreader/org.quantumbadger.redreader.activities.MainActivity}
    09-08 15:31:25.842 W/InputDispatcher(2109): Attempted to unregister already unregistered input channel '34256d8 org.quantumbadger.redreader/org.quantumbadger.redreader.activities.MainActivity (server)'
    09-08 15:31:25.853 I/ActivityManager(2109): Process org.quantumbadger.redreader (pid 12726) has died
    09-08 15:31:25.853 W/ActivityManager(2109): Force removing ActivityRecord{11ed666 u0 org.quantumbadger.redreader/.activities.MainActivity t202}: app died, no saved state
    09-08 15:31:25.933 W/InputMethodManagerService(2109): Got RemoteException sending setActive(false) notification to pid 12726 uid 10083
    09-08 15:31:25.996 W/AppOps  (2109): Finishing op nesting under-run: uid BBBB pkg android code 24 time=0 duration=0 nesting=0
    09-08 15:31:26.491 W/OpenGLRenderer(2752): Incorrectly called buildLayer on View: fh, destroying layer...
    09-08 15:31:26.491 W/OpenGLRenderer(2752): Incorrectly called buildLayer on View: fh, destroying layer...
    09-08 15:31:27.819 I/ActivityManager(2109): START u0 {act=com.android.systemui.recents.SHOW_RECENTS flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity} from uid YYYYY on display 0

**Comment by engelju** [comment]
This is most likely issue #383, which was resolved in 1.9.5.2 -- I'd advise you all to update to that version and see if the problem still persists.

**Comment by L-P** [comment]
Seems like it was fixed in 0539603b510e5f4fad1a12c2cd2ab8640d6fd8a4, I'll wait for it to appear on F-Droid before closing the issue to avoid other duplicates.

**Comment by QuantumBadger** [comment]
F-Droid usually update within 24 hours of me tagging a commit, so shouldn't be too long :)

**Comment by QuantumBadger** [comment]
@mvdan -- I put in an emergency fix for this issue early yesterday, but as far as I can see, F-Droid hasn't rebuilt the app yet. Is there some way to trigger it manually?

**Comment by mvdan** [comment]
There hasn't been a new index yet today, which is weird. This requires someone with physical access to the machines to enter a pin with a keycard, so probably human error or issues. Ping me again if this is still unsolved in 12h.

**Comment by QuantumBadger** [comment]
Thanks -- will do.

**Comment by L-P** [comment]
Seems good now.

**Comment by QuantumBadger** [comment]
Yep, looks like it's updated. Thanks @mvdan!
