### ISSUE TITLE
NSFW subreddits do not load

### ISSUE THREAD

**Issue by achooie** [QuantumBadger/RedReader#388]
Try /r/gonwild (just animated polygons floating/rotating; satirically marked NSFW).

**Comment by ajs124** [comment]
Works for me: ![screenshot](http://i.imgur.com/vbEhgVS.png)

Maybe you don't have the "Behaviour → Posts → Show NSFW content" option activated?

**Comment by achooie** [comment]
Oh dang it, you're right. Sorry, I went through the settings pages multiple times, but I still missed something. 

Thanks!
