### ISSUE TITLE
CAPTCHA is not correctly shown

### ISSUE THREAD

**Issue by Airon90** [QuantumBadger/RedReader#393]
See screenshoot. You can't choose to show another CAPTCHA code
![screenshot_2016-09-16-13-03-17](https://cloud.githubusercontent.com/assets/139841/18712825/5e57a928-8010-11e6-82cd-6b8924b50b2e.png)

**Comment by QuantumBadger** [comment]
Looks like a reddit issue, but it would definitely be an idea to add a "new captcha" button.

**Comment by Airon90** [comment]
It seems that this  bug should be closed as CAPTCHA is not used anymore
