### ISSUE TITLE
Add comment swipe action to go back

### ISSUE THREAD

**Issue by QuantumBadger** [QuantumBadger/RedReader#398]
I.e. swiping should have the same effect as pressing the "back" button.

**Comment by QuantumBadger** [comment]
Added in Alpha 110.

**Comment by engelju** [comment]
Slightly confused, what is the option to enable this? (I'm on Alpha 111).

**Comment by QuantumBadger** [comment]
@engelju -- should be in Settings > Behaviour > Fling Comment (Left/Right) Action > Back :)
