### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Bragado** [QuantumBadger/RedReader#399]
Hi, I am sorry for doing this right here, but I wanna get in contact with you to ask you some questions so I can help creating a new functionality

**Comment by QuantumBadger** [comment]
No problem! You can reach me at the email address on the [Google Play](https://play.google.com/store/apps/details?id=org.quantumbadger.redreader) page, or drop me a PM on [reddit](https://www.reddit.com/user/quantumbadger). Or just comment here if that's more convenient :)

**Comment by Bragado** [comment]
Hi, first of all, thanks for respoding 
We are a small team of college students from third year and our teacher told us,
to choose an open source project to contribut.
Our job is to make a documentation of your project Red Reader, fix some bugs (and discover new ones) and create a new functionality.
I was wodering if you can help us with the documentation part, if so, I have some question I would like to now about:
- How this idea started and with who?
- Did you take any precautions with your development work?
- Most of the projects opensource use similiar process models, the most popular 
used, is probably "Incremental development and delivery", did you ever took attencion
to follow any process model, if so, which one and why did you choose it?
- Which are the main problems you ever faced with the project? 
- In your opinion, what should be done next with the project?

**Comment by QuantumBadger** [comment]
No problem :)

> How this idea started and with who?

Started by me a few years ago -- I was using another (paid-for) reddit app but grew tired of the bugs and UI issues, so I decided to write my own reddit client :)

> Did you take any precautions with your development work?

I do quite a bit of testing before each release, including on various legacy platforms using the Android emulator.

> Most of the projects opensource use similiar process models, the most popular used, is probably "Incremental development and delivery", did you ever took attencion to follow any process model, if so, which one and why did you choose it?

RedReader is too small a project to need a particular development model, but each release pretty much works like this:

* People continuously suggest new features.
* I pick out the most popular/useful ones to go into the release, and implement them over the course of a few months.
* The code gets merged in immediately (continuous integration), and an [alpha version](https://redreader.org/alpha/) gets built for nearly every commit.
* If other contributors submit pull requests during that time, I review them and they get merged in.
* Once all the stuff I've promised is done, I test all the major functionality on various platforms.
* Then, after a few days (to wait for alpha bug reports to come in) I make the release.

> Which are the main problems you ever faced with the project?

The first big problem I encountered was with the HoloEverywhere library. Back when the app was released (nearly 4 years ago now), Holo was quite new, and I needed to use HoloEverywhere for compatibility reasons. But actually getting it building was a nightmare, and there were a huge number of bugs (like dialogs getting created twice, and artifacts during ListView scrolling, and so on). The app uses Material Design now, so HoloEverywhere has been removed recently :)

The hardest feature to implement originally was the ability to swipe posts left/right in the post list, to perform customisable actions like voting, saving, or hiding. This used to be done with an invisible overlay on top of the ListView to intercept the touch events, and I spent ages dealing with ListView weirdness (like caching the rendered views and refusing to update them, performance issues, etc). I also spent a while getting the "physics" of the swipe correct, fine tuning the detection of swiping vs scrolling, and making minor UX tweaks. Recently I switched the post list over to a RecyclerView, and the code is now much simpler (and more robust).

> In your opinion, what should be done next with the project?

There's always more stuff to do than there is time available :)

* Better management of subreddit subscriptions (i.e. an editable list), and allow multireddits to be created and edited.
* Better support for saving images. The UI is currently hidden away, and it only works for a small number of images.
* Built-in support for YouTube videos (without bringing in any GPL-incompatible libraries)

And so on :)

**Comment by Bragado** [comment]
Hi man
I want to thank you again for the help you gave me last time
He made a report about model processes that you can find here:
https://github.com/Bragado/RedReader/tree/master/esofDocs
Our teacher gave us a nice grade so I really have to thank you about it
I wanna say something about the fisrt report. We will do pull request by the end of the semester (december) so if you like to keep any report just tell us what should we improve
Btw, you can already see what we are doing for this second report (it's still incomplete), and we come up with some questions, we are wonder if you can help us identify some of the Non-Functional requeriments. I'll try to do some questions to make it easier:
Do you have any concerns about performance? Did you do any tests to RedReader performance?
About security, how measures do you take to save users privacy? 
These are the common non functional requirements, if you can point us to another ones, it will be awesome
I have another question non related to the reports. We had one idea to create a new functionality. I am used to work with NFC for android and I find it a pretty awesome tecnology. Our idea was to share posts with others users using NFC. I know that you already use android been but it would be awesome to share a post with only one touch.

**Comment by QuantumBadger** [comment]
Looks good! I won't be looking to merge the report into the main repo, but I'd be happy to bring in any code changes you make (after a review).

Performance is pretty good I think. One area for improvement would be to stream gifv/mp4/webm videos instead of waiting for the download to complete. Probably not too hard to implement.

Privacy-wise, there's a ticket open about encrypting the on-disk storage. Maybe a "private mode" could be added to the app, where:

* Cache files are encrypted with an ephemeral key
* Change data and cache databases are never written to disk

That would be a pretty big change though.

The NFC thing sounds interesting, but would probably have quite a small number of end users. We'd also have to be careful about security and battery life.

See also the three suggestions at the end of my last comment :)
