### ISSUE TITLE
Checking notifications does not mark as read on web

### ISSUE THREAD

**Issue by evitalis** [QuantumBadger/RedReader#406]
I have been having an issue where I check direct messages, or post replies, on my phone but when signing in on the PC it shows everything as unread/new. Is this a setting I am missing or actual bug in the application?

**Comment by ajs124** [comment]
This might be an actual but, but please check #101 and #347 to see if it's either fixed already or a duplicate.

**Comment by QuantumBadger** [comment]
The app doesn't mark everything as read automatically -- if you click the three dots in the top right of the inbox, there's an option to "Mark all as read" :)
