### ISSUE TITLE
Images gets downloaded twice when using Opengur

### ISSUE THREAD

**Issue by Hund** [QuantumBadger/RedReader#408]
I use Opengur for images hosted on Imgur, the only issue is that RedReader downloads the image, and then parse the link to Opengur which also has to download the image.

This is a real killer on my limited data plan on my phone.

**Comment by QuantumBadger** [comment]
Thanks for the report. It's a known issue at the moment -- the app doesn't definitely know the link type until it's been downloaded. For imgur links though it can tell just by looking at the link, so definitely possible to fix.

**Comment by Hund** [comment]
Sounds good. :)

**Comment by QuantumBadger** [comment]
Fixed by @m3sv, and will be in the next version (v1.9.7). Alpha 99 is up now :)

https://redreader.org/alpha/
