### ISSUE TITLE
Share Images Directly

### ISSUE THREAD

**Issue by Nutomic** [QuantumBadger/RedReader#413]
When you click "share" on an image post, RedReader will only share the link to the image. If I want to share the image itself (eg in Whatsapp), I have to save the image, find it in a file browser, and then share it.

Instead, it would be great if the share action on image posts would directly share the image file.

**Comment by fhtagn** [comment]
My simple proposal keeps the "Share" entry to mean sharing the link, and adds "Share Image" if the post is an image [as per](https://github.com/QuantumBadger/RedReader/blob/master/src/main/java/org/quantumbadger/redreader/common/LinkHandler.java#L303).

**Comment by QuantumBadger** [comment]
Done by @fhtagn -- now in Alpha 97:

https://redreader.org/alpha/
