### ISSUE TITLE
Media downloads first before opening in external app

### ISSUE THREAD

**Issue by iripu** [QuantumBadger/RedReader#421]
I selected external browser for all kinds of media and links. When opening any picture or video, it shows the loading circle for sometime (probably downloads) before showing the open with pop-up for external browsers.

I am using the latest version with Android 4.2.2.

Awesome app by the way. It feels like the developer checked what's inside my mind and built an app based on that. Thank you for making it and sharing it.

**Comment by QuantumBadger** [comment]
Thanks for the report! This looks similar to #408.

**Comment by iripu** [comment]
You can check the extension in the url and then open it in external apps. e.g. http://www.abc.com/xyz.jpg OR http://www.abc.com/xyz.mp4 OR http://www.abc.com/xyz.webm etc..

**Comment by iripu** [comment]
And media hosting websites like imgur.com, gfycat.com and eroshare.com.

**Comment by QuantumBadger** [comment]
Fixed by @m3sv -- alpha 99 is up now:

https://redreader.org/alpha/

I'll leave this ticket open for the moment, to also cover opening in the internal browser.

**Comment by QuantumBadger** [comment]
> to also cover opening in the internal browser.

Done.
