### ISSUE TITLE
imgur galleries not loading [Add refresh button to internal browser]

### ISSUE THREAD

**Issue by uri** [QuantumBadger/RedReader#43]
On Nexus 4, 4.2.2. No imgur galleries are loading. Happened in last couple of updates.

![screenshot_2013-05-27-19-48-52](https://f.cloud.github.com/assets/676443/570065/adf19ec0-c728-11e2-9537-b36cead1eb0e.png)

**Comment by QuantumBadger** [comment]
The app now has native support for galleries, and doesn't use the browser for this.
