### ISSUE TITLE
nsfw tag hidden

### ISSUE THREAD

**Issue by 0ttoman** [QuantumBadger/RedReader#431]
With the newest update the red nswf tag is not shown in the overview, you can see it when viewing the comments though.

**Comment by QuantumBadger** [comment]
Thanks for the report. This works fine for me -- could you send a screenshot of it occurring? Also, do you have "Show NSFW content" enabled in the behaviour settings?

**Comment by 0ttoman** [comment]
I restarted my phone, changed some settings and compared it to the web version. And thought it could be possible because of the latest update.
Two separate posts removed the nsfw tag and I had an cached version of the commends. This resulted in said appearance.
Sorry for opening an false issue..

**Comment by QuantumBadger** [comment]
No problem, glad to hear it's working!
