### ISSUE TITLE
Markdown in quotes isn't rendered correctly

### ISSUE THREAD

**Issue by YtvwlD** [QuantumBadger/RedReader#433]
This:

```
> # headline
> 
> This is *some* text.
> 
>  * a thing
>  * another thing
```

yields

> headline
> 
> This is *some* text.
> \* a thing
> \* another thing

but should yield

> **headline**
> 
> This is *some* text.
> 
>  * a thing
>  * another thing

**Comment by YtvwlD** [comment]
[Here](https://www.reddit.com/r/de_EDV/comments/5oymys/user_mit_usuk_tastaturlayouts_wie_schreibt_ihr_am/dcx8xa9/) is an example.

**Comment by QuantumBadger** [comment]
Fixed in https://github.com/QuantumBadger/RedReader/commit/46852d0a95aa89e7dac8219f9b2ccec481f118b5 (alpha 198).
