### ISSUE TITLE
[Feature request] Share option in the internal browser 3 dot menu.

### ISSUE THREAD

**Issue by japanesephundroid** [QuantumBadger/RedReader#441]
There are different app options there than **View in Browser**. It would be great if both were available there.

For example **Awesome Pop-up Video** which I use to open twitter video links.

**Comment by Clubfan22** [comment]
This has been fixed with #449

**Comment by QuantumBadger** [comment]
@Clubfan22 has added this, and it should be in the latest alpha :) Does it fix the issue?

**Comment by QuantumBadger** [comment]
You beat me to it :) I'll wait for @japanesephundroid to confirm before closing.

**Comment by japanesephundroid** [comment]
It works :), thanks @Clubfan22 @QuantumBadger.
