### ISSUE TITLE
Show subreddit names for posts when viewing r/popular

### ISSUE THREAD

**Issue by guoguo12** [QuantumBadger/RedReader#445]
Check out [this announcement](https://www.reddit.com/r/announcements/comments/5u9pl5/introducing_rpopular).

**Comment by QuantumBadger** [comment]
Thanks, fixed here:

https://github.com/QuantumBadger/RedReader/commit/6c3e524e535eff50013df1dc3b44d6d9b783ee09

Should be in Alpha 108 in a few minutes.
