### ISSUE TITLE
Feature Request: Collapse original post

### ISSUE THREAD

**Issue by dylanrees** [QuantumBadger/RedReader#481]
I get a lot of good use out of the "toggle collapse" feature whenever I read threads with many comments.  However, it would be nice to also be able to collapse the original post.  One example of where this would be useful is on the /r/politics megathreads.  These are self-posts with dozens of links in them, and you have to scroll down for a long time before you're able to find any of the comments.

**Comment by QuantumBadger** [comment]
This has been added by @Clubfan22 in pull request #484 :)

**Comment by dylanrees** [comment]
I'm enjoying the feature!  So glad it was added!
