### ISSUE TITLE
Fullscreen video in "Internal Browser" does not work

### ISSUE THREAD

**Issue by japanesephundroid** [QuantumBadger/RedReader#504]
Before I describe this some info on my setup:
Gif Viewer: Internal viewer
Video Viewer: Internal VideoView
Use Internal Browser: Enabled
ROM: CyanogenMod 6.0.1 based

Any video not supported by RedReader is passed to the internal browser. This is handled as far as I know by **Android System WebView** (I have the official Google one from the Play store installed).
The fullscreen option is available but when I press it nothing happens.

I found someone describing a similar problem for a different app:
https://teamtreehouse.com/community/html5-video-wont-go-fullscreen-in-webview

and he links to a possible solution:
https://stackoverflow.com/questions/15768837/playing-html5-video-on-fullscreen-in-android-webview/16179544#16179544

**Comment by japanesephundroid** [comment]
@QuantumBadger does this happen to you as well? I wasn't sure if it's specific to my setup.

**Comment by Clubfan22** [comment]
As mentioned in the PR, big thanks to @japanesephundroid for providing a link to the solution!
I was able to test it on OxygenOS (the OS of OnePlus) Android 8.0 beta, but I think a lot more testing is needed, especially on custom ROMs and older Android versions.

**Comment by japanesephundroid** [comment]
No problem @Clubfan22, I remember submitting this, the solution part I did not - it was a while ago. The notification about this was kind of a surprise.

Anyway thanks to you too for the fix, I will test it once the alpha is up and report back.

**Comment by cprcrack** [comment]
Glad my sources helped you! And a good excuse to try RedReader :)

**Comment by QuantumBadger** [comment]
Merged in, should be preset in Alpha 146. Thank you @Clubfan22 and @cprcrack :) (and to @japanesephundroid  for investigating the fix)

**Comment by japanesephundroid** [comment]
Can confirm that it works on stock LG Android 7.0 :)
Thanks guys.
