### ISSUE TITLE
Is there a reason to have isIceCreamSandwichOrLater or isHoneyCombOrLater?

### ISSUE THREAD

**Issue by awells111** [QuantumBadger/RedReader#508]
If the minSdkVersion is 14, is there a reason to have isHoneyCombOrLater() and isIceCreamSandwichOrLater()?  HoneyComb is 11 and Ice Cream Sandwich is 14 but isn't anyone using the app always at 14 or above?

**Comment by awells111** [comment]
I created a pull request.  I apologize if this is the wrong way to go about it as I am fairly new to GitHub in general.

**Comment by QuantumBadger** [comment]
> If the minSdkVersion is 14, is there a reason to have isHoneyCombOrLater() and isIceCreamSandwichOrLater()?

This is old legacy code from when earlier versions of Android were supported by the app :)
