### ISSUE TITLE
Closing bracket not included in link

### ISSUE THREAD

**Issue by spagy** [QuantumBadger/RedReader#517]
i have mainly noticed this with links to wikipedia, just because wikipedia links frequently end with a closing bracket. for example if someone leaves a link in their comment like this https://en.wikipedia.org/wiki/42_(number) then the closing bracket isn't considered part of the link. the result is the following: [https://en.wikipedia.org/wiki/42_(number](https://en.wikipedia.org/wiki/42_(number ))

**Comment by QuantumBadger** [comment]
Duplicate of #392, which is fixed in the latest Alpha :)
