### ISSUE TITLE
Add support for v.reddit.com

### ISSUE THREAD

**Issue by Clubfan22** [QuantumBadger/RedReader#520]
[Per Reddit](https://www.reddit.com/r/RedReader/comments/6p4agf/vreddit_links_not_working/)

From what I've seen so far, *v.reddit.com* is Reddit's video host. When clicking on a post linking there. the website embeds the video into the OP. Currently, RedReader just opens the thread without showing the video.

An example for this behaviour can be found at: https://v.redd.it/smasrs6l7ebz

Technically, the video appears to be based on [https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP](DASH).

For RedReader, I think having an extra activity for reddit videos would be the way, similar to GIFs and imgur albums.

**Comment by QuantumBadger** [comment]
Fixed in Alpha 137 :)
