### ISSUE TITLE
Burmese Translation

### ISSUE THREAD

**Issue by amlwin** [QuantumBadger/RedReader#523]
Hello I am new to OSS. I want to contribute to this project. I want to translate String to Myanmar language. Please show me to step to take part. Thanks

**Comment by QuantumBadger** [comment]
Hi, thanks for helping out! I see you've added some strings here:

https://hosted.weblate.org/projects/redreader/strings/my/

You're doing it correctly, so please continue adding them on Weblate :) Every so often I'll bring the Weblate changes into the main codebase.

Please let me know if you have any questions!

**Comment by BannerCoe** [comment]
Thanks for ur helping hand
