### ISSUE TITLE
Navbar does not use primary dark/light color

### ISSUE THREAD

**Issue by cocobelgica** [QuantumBadger/RedReader#524]
Not really sure if this is intended, but his only happens when using the Night(low contrast) theme. Screenshot below for reference.

![Screenshot](http://i.imgur.com/84S7XNZ.png)

**Comment by QuantumBadger** [comment]
Works for me if I select "Primary (light)" for the navbar colour.

In this case, "Primary (dark)" is black (i.e. the same colour as the status bar at the top of the screen).

**Comment by cocobelgica** [comment]
I see, I was under the impression that the action bar is the primary dark. My bad, I'm closing this issue. Thanks for clarifying.
