### ISSUE TITLE
Numbered lists not rendered properly

### ISSUE THREAD

**Issue by guillermogf** [QuantumBadger/RedReader#529]
Markdown syntax allows to only use `1.` to create numbered lists, but will translate it to 1., 2.,... when parsing it. However, RedReader won't do that and the hole list ends up being just ones.

[Here's an example](https://reddit.com/comments/6leaqy/comment/djt8wo0). Open it on both the app and browser to see the difference, in case I didn't make myself clear.

I guess this isn't device specific, but here's my info:
RedReader v1.8.9.2.1 (BTW, you should check out [semantic versioning](https://semver.org))
Android 5.1.1
Xiaomi Mi4c

**Comment by QuantumBadger** [comment]
Thanks, definitely a bug.

AFAIK semantic versioning is mainly for components which expose APIs (like shared libraries), but I agree the version numbers here have gotten out of hand :)

**Comment by guillermogf** [comment]
> AFAIK semantic versioning is mainly for components which expose APIs

Well, it's true that if you have an API it is a must, but I think it can also benefit any kind of software, though you are right that for an Android app it is far from needed.

> but I agree the version numbers here have gotten out of hand :)

That was my main point, I was just suggesting it as a good alternative to avoid version numbers getting out of hand. But I don't want to diverge the issue, it's just that so many numbers make me cringe a little bit 😂

**Comment by splitowo** [comment]
https://github.com/splitowo/RedReader/commit/9f6ed427962b851d73e4a7c8718fc008c5ba0058
I have fixed this by making a change in `MarkdownParagraphGroup.java`, it now checks the previous parahraph to determine the count.
This caused `MarkdownParagraph.number` variable to be unused right now, but I guess it might be relevant to numbering links which is listed in TODO. That is why I left it for now.

Let me know if that is a good direction

**Comment by QuantumBadger** [comment]
Fixed in https://github.com/QuantumBadger/RedReader/commit/46852d0a95aa89e7dac8219f9b2ccec481f118b5 (alpha 198).
