### ISSUE TITLE
Gestures to exit gifs or internal Reddit videos

### ISSUE THREAD

**Issue by digital-mystik** [QuantumBadger/RedReader#533]
Would it be possible to have some sort of swipe function to go back to the current thread from a gif or internal video instead of having to use the back button?

**Comment by rupak0577** [comment]
@digital-mystik You mean like in the Youtube app to minimize the activity? I have been thinking about that myself because with slower connections, you cannot browse until the entire gif loads.

**Comment by digital-mystik** [comment]
@rupak0577 I was thinking something similar to Slide where you can go back from any video or gif by swiping from the left edge. I like how just tapping an image or some gifs can go back in RedReader, but having a swipe to exit videos etc would be pretty cool. 

Slide is open source as well but I'm not sure if that functionality could be implemented somehow as it uses Material Design.

**Comment by QuantumBadger** [comment]
In theory, tapping a video should cause it to close, unless you've enabled the media playback controls -- is that the case?

**Comment by Briscoooe** [comment]
Is anybody working on this? I'd be happy to try and pick it up if nobody else wants to

**Comment by QuantumBadger** [comment]
> Is anybody working on this? I'd be happy to try and pick it up if nobody else wants to

Not that I know of -- please feel free to take it on! Let me know if you have any questions.

**Comment by OraBB1t** [comment]
This. It would be great if this was added as some of us still use navigation bar instead of navigation gestures. I would suggest a **swipe down gesture** to return to thread from a image, video or a gif.
