### ISSUE TITLE
Keep posts marked as read for longer

### ISSUE THREAD

**Issue by wosc** [QuantumBadger/RedReader#547]
Some subreddits I only visit rarely, and then browse "top this month" or something simliar that aggregates a larger timespan. Unfortunately, RedReader currently forgets quite soon which posts I have already read, so I have to start all over again.

If I'm reading the source correctly, "mark as read" currently is stored for [PRUNE_AGE_MS](https://github.com/QuantumBadger/RedReader/blob/master/src/main/java/org/quantumbadger/redreader/reddit/prepared/RedditChangeDataManager.java#L45) which is hardcoded to one week -- way too short for my purpose, I'd probably need something like at least 90 days. Would it be possible to make that duration configurable, or do you foresee dire performance implications if those marks were to be kept around for a longer time? Thanks for your help!

**Comment by QuantumBadger** [comment]
Thanks for the suggestion!

Performance would be fine -- the reason for the limit was memory usage. The whole database is stored in RAM, to avoid doing a disk lookup for every single comment/post.

If we assume that each `RedditChangeDataManager.Entry` object takes up about 64 bytes on the heap, then you can fit data about ~15k posts and comments in 1MB. The `HashMap` (with string keys) will add some overhead as well, but generally quite manageable.

So I'd happily accept a patch to make this configurable, maybe with a limit on the number of entries (10k?) to avoid out-of-memory errors.

**Comment by wosc** [comment]
Excellent, thanks for the analysis! Restricting the total number of entries sounds sensible. I guess one probably looks at fewer than 10k posts over the course of a few months, so I'd go for, first prune entries older than the configured age threshold, and if we still have too many, prune oldest ones until we're down to 10k. (And I guess we could make the 10k configurable as well, only it probably would need quite a bit of explanatory text...)

I'll take a crack at this, but I'm new to Android development (doing mostly web things currently), so I'm not sure how that will go. ;)

**Comment by 2vek** [comment]
Really need this feature. Please release new version. Been waiting for quite some time.

**Comment by Cguy7777** [comment]
@QuantumBadger Looks like this is in and can be closed.
