### ISSUE TITLE
"Skip to front page" setting ignores "Tablet mode" setting

### ISSUE THREAD

**Issue by vjon** [QuantumBadger/RedReader#550]
If the "Skip to front page" setting is enabled, the app will open to the front page in a Single pane, even if:
- "Auto-detect" is selected for tablet mode and the device is a tablet-class screen size
- "Always" is selected for tablet mode

Pressing the back button to return to the main menu then activates dual-pane view as expected, until the next time the app is closed and re-opened.

Tested on the following devices:
- Google Pixel 2 running Oreo 8.0.0 ("Always" tablet mode option used for testing)
- Google Pixelbook running Chrome OS 62.0.3202.97 (Both tablet mode options used for testing)

**Comment by Cguy7777** [comment]
@QuantumBadger Looks like this has been fixed.
