### ISSUE TITLE
[Question] Is there a way to save a post link while INSIDE the post? 

### ISSUE THREAD

**Issue by Weej1** [QuantumBadger/RedReader#551]
Hi all, 

First time user and I do quite like the speed and neatness of the app. One thing I'm missing though is the ability to share the post I'm reading...or even a particular comment within the post. I used to use the official reddit app and frequently save comments I find funny to Google Keep or OwnNotes.

So! Is there a way to save a reddit post to other apps/places WHILE reading it?

**Comment by ajs124** [comment]
Sure, swipe from the side of the screen and click the share button to share the post.

For comments, long click.

**Comment by Weej1** [comment]
Oh wow! This is exactly what I needed! Thanks tons @ajs124 !

**Comment by doodhout** [comment]
@ajs124 or anyone, how can you share a link to a comment?

Long-press on a comment and choosing share, shares the first URL in the comment (when applicable) instead of the comment itself. It seems there is nothing I can do to circumvent this.
