### ISSUE TITLE
View messages you sent/received

### ISSUE THREAD

**Issue by ihailfromreddit** [QuantumBadger/RedReader#555]
Is there a way to view messages you sent/received in a conversation similar to what you can see at:

https://www.reddit.com/message/messages/

A way to see sent and received messages in a conversation view

**Comment by ihailfromreddit** [comment]
Sorry, this seems to be a duplicate of issue #443 (https://github.com/QuantumBadger/RedReader/issues/443)

**Comment by QuantumBadger** [comment]
Closing as duplicate of #443 :)
