### ISSUE TITLE
request: automatically save drafts of self-posts

### ISSUE THREAD

**Issue by ihailfromreddit** [QuantumBadger/RedReader#557]
more than once i wrote a long post or made an edit, and then accidently pushed back (ghost moves on my touchscreen) and the whole edit or post is lost

thread on reddit: https://www.reddit.com/r/RedReader/comments/7n1d1x/request_automatically_save_drafts_of_selfposts/

**Comment by fguibourt** [comment]
Hello @QuantumBadger can I work on this issue ? 
I have seen there is already something to save draft for comments. I can reuse this for self-posts.
Thanks in advance.
