### ISSUE TITLE
Suggestion: Hide visited posts

### ISSUE THREAD

**Issue by p3lim** [QuantumBadger/RedReader#558]
Kind of like how RES does this, where you can hide all posts that you've visited, or only show those you've already visited.

**Comment by asoback** [comment]
Is this what you were looking for? Posts are still visible after they have been clicked, until the next refresh.

**Comment by p3lim** [comment]
When a link/post is visited it should not show up the next time the subreddit is refreshed/reloaded.
If that's what your commit does, then yes.

**Comment by QuantumBadger** [comment]
Closing as fixed, thank you @asoback :)

**Comment by asoback** [comment]
Thank you! This is my first true contribution to an open source project! I look forward to making many more!
