### ISSUE TITLE
Long-pressing post content should open post context menu

### ISSUE THREAD

**Issue by contrapunctus-1** [QuantumBadger/RedReader#559]
First of all, thanks for making a great, freedom-respecting client like Red Reader! I'm using v1.9.8.3 from F-Droid.

Embarrassingly, I couldn't figure out how to edit my self-post. 🙂 I figured that long-pressing the post content should bring up the relevant context menu, as it does for comments, and it took me a while to realize that one has to long-press the link. I find this behavior inconsistent. Even in the settings, there's no option for configuring the behavior for long-pressing a self-post.

**Comment by achalpandeyy** [comment]
I found that if it's a text post then there is an Edit option but not for other types of posts (like images, videos etc)

**Comment by Cguy7777** [comment]
I just tried this, and can confirm that long-pressing the post content does not work on v1.9.8.3, but it works fine for me on v1.18.1. 

I think this was fixed awhile back; are you still experiencing this issue?

**Comment by contrapunctus-1** [comment]
I just checked, and yes, it seems to be resolved - long-pressing a self-post text opens the context menu, which includes the Edit operation.
