### ISSUE TITLE
[Feature Request] Allow links in comments to be opened externally

### ISSUE THREAD

**Issue by BasioMeusPuga** [QuantumBadger/RedReader#56]
Hey,

First of all, great job. Bowel movements are 20% more efficient with RedReader.

Could you please put in an option to open links in comments in an external browser/relevant app? The internal browser can't handle anything with video or a download link in it.
Right now it's not even possible to copy a link from a comment without copying the whole comment along.

Thanks.

**Comment by recheej** [comment]
@QuantumBadger Is this already implemented? I noticed there's already a 'View in Browser' option.

**Comment by sharkwouter** [comment]
> @QuantumBadger Is this already implemented? I noticed there's already a 'View in Browser' option.

Yes, it works well

**Comment by Cguy7777** [comment]
@QuantumBadger This can probably be closed.
