### ISSUE TITLE
Markdown: Sub-things in lists

### ISSUE THREAD

**Issue by Neui** [QuantumBadger/RedReader#562]
In lists, you can put additional text/paragraphs/code/sub lists to each entry by indenting with some amount of spaces. However, currently RedReader mostly interprets it as code.

[Example (section List) on Reddit](https://www.reddit.com/r/test/comments/7ratgg/testing_markdown_behaviors/). [Image on desktop web reddit](https://user-images.githubusercontent.com/1196130/35111900-b46111d0-fc7c-11e7-8ece-57dd1c7e86b0.PNG). [Image on RedReader](https://user-images.githubusercontent.com/1196130/35111951-e08a1a7c-fc7c-11e7-80f4-ffd4032141e0.png).

Tested on F-Droid RedReader 1.9.8.3 on Android 4.2.2 and RedReader git master on emulated x86 Android 4.2.2.

**Comment by QuantumBadger** [comment]
Fixed in https://github.com/QuantumBadger/RedReader/commit/46852d0a95aa89e7dac8219f9b2ccec481f118b5 (alpha 198).
