### ISSUE TITLE
Markdown: &#32; in superscript doesn't work correctly

### ISSUE THREAD

**Issue by Neui** [QuantumBadger/RedReader#563]
HTML entity `&#32;` is a space. However, on reddit, `^Some&#32;text` makes `some text` super-scripted (on desktop web reddit), but RedReader currently only makes the first word super-script.

[Example (section Superscript) on Reddit](https://www.reddit.com/r/test/comments/7ratgg/testing_markdown_behaviors/). [Image on desktop web reddit.](https://user-images.githubusercontent.com/1196130/35112449-5db19d30-fc7e-11e7-87fa-fa1a8a5a1b76.PNG). [Image on RedReader](https://user-images.githubusercontent.com/1196130/35112450-5dd4f10e-fc7e-11e7-9c3c-c7250f6f9deb.png).

This is for example used in [/r/TranscribersOfReddit  for their "advertisement"-text](https://www.reddit.com/r/TranscribersOfReddit/wiki/format/images/text).

Tested on F-Droid RedReader 1.9.8.3 on Android 4.2.2 and RedReader git master on emulated x86 Android 4.2.2.

**Comment by QuantumBadger** [comment]
Fixed in https://github.com/QuantumBadger/RedReader/commit/46852d0a95aa89e7dac8219f9b2ccec481f118b5 (alpha 198).
