### ISSUE TITLE
Markdown: Links with references

### ISSUE THREAD

**Issue by Neui** [QuantumBadger/RedReader#564]
With markdown you can have references like `[My text][MyURL]` and somewhen the latest `[MyURL]: http://example.org` is used. RedReader currently just displays as a paragraph with no links to be clicked on.

[Example (section Links) on Reddit][redditex]. [Example on desktop web reddit][desktopex]. [Example on RedReader][rrex].

[redditex]: https://www.reddit.com/r/test/comments/7ratgg/testing_markdown_behaviors/
[desktopex]: https://user-images.githubusercontent.com/1196130/35113062-7d9ef3ac-fc80-11e7-8a6f-9877a6aa2011.png
[rrex]: https://user-images.githubusercontent.com/1196130/35113064-7dcb6b9e-fc80-11e7-83ef-051ba1650054.png

Tested on F-Droid RedReader 1.9.8.3 on Android 4.2.2 and RedReader git master on emulated x86 Android 4.2.2.

**Comment by QuantumBadger** [comment]
Fixed in https://github.com/QuantumBadger/RedReader/commit/46852d0a95aa89e7dac8219f9b2ccec481f118b5 (alpha 198).
