### ISSUE TITLE
[Feature Request] Improve cache (parallel threads, data types priority)

### ISSUE THREAD

**Issue by Drugoy** [QuantumBadger/RedReader#571]
On my phone's screen I have an indicator of network bandwidth I/O and since I have been using RedReader for months now - I figured out how RedReader's cache work:
1. it seems to uses a single thread (or maybe two threads) to download the data.
2. it prioritizes images/videos over post comments.
3. it takes ~same time to download and save a heavy video/image as it takes to download and save a single post's comments.

As a result - sometimes I suffer from:
1. posts at top of the list haven't been cached (because they are text posts), while images from image posts from below of the list - they get cached just fine.
2. It takes the same time to download 1 gb of images/videos as it takes to download, say, just 5 mb of text.
What are the bottle necks here?
Clearly it's not the network/disk bandwidth.
It is probably either disk i/o rate which or the number of threads used to download things.
Does RedReader use any SQL base to store text data into a DB file?
How many threads/pipelines does the application use to download stuff?

So, please:
1. add settings to control cache priority over data types (images/videos first, text comments first, whole posts sequentially [go sequentially through all posts from the list, caching both things at once for them: the image/video and comments])
2. add a setting to choose the number of threads/pipelines to be used to cache things.

**Comment by QuantumBadger** [comment]
Thanks for the report. The app already prioritises things fairly intelligently, and uses multiple threads to download. I think we download up to 5 images at a time, and an unlimited number of reddit things (posts, comments) at a time.

Images are actually downloaded in a different thread pool to reddit requests -- we make a new thread for every reddit request, and have a fixed pool of 5 threads for everything else.

However, reddit imposes a restriction on API users that you can only download something once every two seconds. So if you want to precache 10 comments pages, you can do it, at the quickest, in 20 seconds.

Additionally, the reddit API has always been quite slow, particularly for logged-in users. Image hosting sites are likely quicker by comparison.

We save cached stuff directly to files on disk, not in a database.

Hope that answers your questions!

**Comment by Drugoy** [comment]
Thanks for the answers, but my personal experience shows that if I have a list of 100 items with 60 image posts and 40 text posts - in a minute I'll have loaded 50 images and 0 posts (even image posts won't be loaded, only their images get loaded), which bothers me much, since I use RedReader at home to cache some posts to read during my everyday commute to work, which is internetless.
That's why I asked you to introduce an option to control priority.
As for the number of threads/pipelines - it feels like the application doesn't use parallel downloads at all [I'm not claiming it to be so, it's just my personal perception], thus I asked to yield that setting into user-accessible option.
