### ISSUE TITLE
[Feature Request] Cache images from direct links from loaded comments

### ISSUE THREAD

**Issue by Drugoy** [QuantumBadger/RedReader#572]
People post links to direct images in comments.
Those images don't get cached unlike images from posts (if a post is an image) and unlike comments as text.

Would be nice if RedReader had an option to also cache images from the posts comments as well (that needs to be a separate option as there may be image spam in comments).

**Comment by QuantumBadger** [comment]
I've considered this in the past, and decided against it:

* It would cause a privacy issue -- someone could post a link to a tracking image in a comment, and get the IP address of everyone who viewed that comment page. This is also possible with post lists, but for various reasons I think that's less bad.
* It would cause excessive bandwidth and disk usage (potentially precaching hundreds of images per comment page, with maybe hundreds of comments pages per day for heavy users)
* As a result of the above point, image hosts might get angry with us :)

I suppose it could work if it was behind a preference which was off by default, but even then I think we may want to protect users from themselves in this case!

**Comment by Drugoy** [comment]
You are probably right.
