### ISSUE TITLE
Comments containing only '&nbsp;' look weird

### ISSUE THREAD

**Issue by wb9688** [QuantumBadger/RedReader#585]

**Comment by QuantumBadger** [comment]
Presumably by this you mean there should be more vertical space? Perhaps we can add a minimum comment height in pixels.

**Comment by wb9688** [comment]
@QuantumBadger: When there is a comment containing only `&nbsp;` there's a blank space between it and the next comment.

**Comment by QuantumBadger** [comment]
Fixed in #593 by @Briscoooe :)
