### ISSUE TITLE
[Feature Request] Support 18:9 Aspect Ratio

### ISSUE THREAD

**Issue by noranyan** [QuantumBadger/RedReader#589]
Hello Dev,

I have a Google Pixel 2 XL and there is a black stripe at the bottom of the screen when I use the app.

I think RedReader can take advantage of the empty space to display more information.

**Comment by QuantumBadger** [comment]
Thanks for the suggestion -- this has already been added to the latest Alpha, and will be in the next release :)

https://github.com/QuantumBadger/RedReader/commit/5d55a33f92fc4cb65d1ebb140ebd3afdbdf71b0c
