### ISSUE TITLE
Contributing a New logo

### ISSUE THREAD

**Issue by artjeck** [QuantumBadger/RedReader#596]
Hi Developers !
I am a Graphic Designers, I want to contribute a new logo for you application, before I start it , i need your permission first!

**Comment by QuantumBadger** [comment]
Thanks @artjeck, yes you have permission, but as @philipwhiuk says there is already an ongoing discussion about the logo design.

**Comment by artjeck** [comment]
Thanks for your feedback sir, it's okay 👍
