### ISSUE TITLE
Notifications are not really marked as "read"

### ISSUE THREAD

**Issue by Nonononoki** [QuantumBadger/RedReader#600]
How to reproduce: 
1. Get a notification
2. Tap on it
3. View notification in app (e.g. see the reply)

Expected behavior:
Notification marked as read, empty inbox

Actual behavior:
When I open Reddit on desktop I can still see that exact reply marked in my inbox.

**Comment by QuantumBadger** [comment]
This is the expected behaviour -- while in the inbox, open the three dots menu and select "Mark all as read" :)
