### ISSUE TITLE
NSFW thumbnails don't show up on searches

### ISSUE THREAD

**Issue by japanesephundroid** [QuantumBadger/RedReader#613]
This only used to happens when searching on:
Front Page
Popular Subreddits
All Subreddits
as I previously reported [here](https://www.reddit.com/r/RedReader/comments/8k2qa1/search_yields_no_nsfw_results_even_if_show_nsfw/dzh8e3e/) (I did not comment on the related [fix](https://github.com/QuantumBadger/RedReader/pull/591) because I wasn't sure if the issue was related).

Now it happens on any subreddit.

Try searching for nsfw or better yet nsfw:yes which only returns nsfw posts.
Any post tagged nsfw does not show a thumbnail.

This does not happen on the desktop version of reddit so its probably not a Reddit or RedReader settings issue.

**Comment by QuantumBadger** [comment]
I think we must be performing searches as a logged-out/anonymous user. Maybe related to the cookie changes in #591.

See also the following post: https://old.reddit.com/r/RedReader/comments/9lsxs3/unable_to_search_quarantined_subreddits_even/

**Comment by japanesephundroid** [comment]
> 
> 
> I think we must be performing searches as a logged-out/anonymous user. Maybe related to the cookie changes in #591.
> 
> See also the following post: https://old.reddit.com/r/RedReader/comments/9lsxs3/unable_to_search_quarantined_subreddits_even/

That should be it.

**Comment by QuantumBadger** [comment]
Authentication issue fixed here: https://github.com/QuantumBadger/RedReader/commit/076642bfae3e0ff000bb44d8fd57c460b0e57752

It turned out to be a subtle regression in #591 where we were using a different domain for search API calls.

Hopefully that fixes the issue for you -- please let me know if you still have issues with Alpha 167!

**Comment by japanesephundroid** [comment]
Thanks. It works 👍

**Comment by Cguy7777** [comment]
@QuantumBadger I think this can be closed. :-)

**Comment by QuantumBadger** [comment]
Thanks :) Closing this now.
