### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by Artholo** [QuantumBadger/RedReader#616]
Unable to login to account. 
Every time I type "." For .com it the app deletes the last 3 letters of my login. This is for the login section. I think its because my account name Is too long.

**Comment by QuantumBadger** [comment]
> Every time I type "." For .com it the app deletes the last 3 letters of my login

Sorry, I don't understand the problem. Reddit usernames can't contain "." as far as I know. Are you trying to log in with your email address?

**Comment by Artholo** [comment]
I feel like a moron. I was using my login app and it auto populated my email to the login. Please disregard my issue.

-------- Original Message --------

**Comment by QuantumBadger** [comment]
No worries :)
