### ISSUE TITLE
[feature] [markdown] Support official markdown spoiler tag

### ISSUE THREAD

**Issue by dtrauma** [QuantumBadger/RedReader#620]
As far as I can tell, while spoiler tags are supported, this doesn't encompass the new official markdown syntax with greater than/exclamation mark.

https://www.reddit.com/r/alttpr/comments/8dl0tb/til_reddit_now_has_an_official_spoiler_tag/

**Comment by QuantumBadger** [comment]
Thanks, we should definitely add this.

**Comment by gappleto97** [comment]
Sorry to be a bother, but are there any plans to implement this in the medium term?

**Comment by QuantumBadger** [comment]
Fixed in https://github.com/QuantumBadger/RedReader/commit/46852d0a95aa89e7dac8219f9b2ccec481f118b5 (alpha 198).
