### ISSUE TITLE
[Feature request] Gold indicator for posts

### ISSUE THREAD

**Issue by japanesephundroid** [QuantumBadger/RedReader#622]
Currently there is only support for comments.
Support for posts would be nice.

Example of post with gold:
https://www.reddit.com/r/soccer/comments/9jz7vk/chelsea_11_liverpool_sturridge_89/

**Comment by samyuyitung** [comment]
Hi, I would love to start contributing to RedReader, is this feature worth pursuing and can I pick it up?

**Comment by japanesephundroid** [comment]
.> 
> 
> Hi, I would love to start contributing to RedReader, is this feature worth pursuing and can I pick it up?

Hi, I am not the developer but he welcomes pull requests as he doesn't actively develop the app anymore.

This is not a top priority feature but it should be easy to do since support for comments already exists.

The feature most missing at the moment is [sound support for v.redd.it videos](https://github.com/QuantumBadger/RedReader/issues/617)

Basically sound for those links is separate (like Youtube) something RedReader currently doesn't support.

**Comment by japanesephundroid** [comment]
> 
> 
> Hi, I would love to start contributing to RedReader, is this feature worth pursuing and can I pick it up?

.> 
> 
> Hi, I would love to start contributing to RedReader, is this feature worth pursuing and can I pick it up?

Hi, I am not the developer but he welcomes pull requests as he doesn't actively develop the app anymore.

This is not a top priority feature but it should be easy to do since support for comments already exists.

The feature most missing at the moment is [sound support for v.redd.it videos](https://github.com/QuantumBadger/RedReader/issues/617).

**Comment by samyuyitung** [comment]
Cool, where in the subtitle do you think this gold label should go? Should it remain consistent with the comments and be placed after the points label?

**Comment by QuantumBadger** [comment]
Added in #631.
