### ISSUE TITLE
Allow copy text from a post main body.

### ISSUE THREAD

**Issue by nathanernest** [QuantumBadger/RedReader#637]
Comments can be coppied with a long press and selecting "copy text" but no such option is available for the main body of text from a post. Would be a great feature to have.

**Comment by Efreak** [comment]
There's a confusingly-labeled 'copy' item when long-pressing the post title, but it only copies the post url, not the contents. This *should* be renamed 'Copy post URL', or should be configurable in options (choose from url, title, content, or some combination)

To copy text post, reply to post, then long-press the original text in the lower half of the screen to get a selection. This *should* be available in the main post view as well.

*Should* meaning these are things the app does not do, but seem like good ideas to me. *[Shoooood](https://en.m.wikipedia.org/wiki/Semantic_satiation)*

**Comment by MichalFerencsik** [comment]
Hi @QuantumBadger , can I work on this issue?

**Comment by japanesephundroid** [comment]
> Hi @QuantumBadger , can I work on this issue?

Not QuantumBadger but he has said repeatedly that he welcomes pull requests as he does not have much time for the app now. He just pretty much only looks at pull requests and fixes critical bugs that break the app.

As this seems like a small fix and not a major feature that fundamentally changes the app, I doubt that he would have any objection to it.

**Comment by MichalFerencsik** [comment]
Thanks for your reply.
Pitty is that I already prepared change for this. 😌

Nevermind, I will take a look for something else. 🙂

**Comment by MichalFerencsik** [comment]
Also, @japanesephundroid, do you think that Issue#667 would be worth to try?

**Comment by japanesephundroid** [comment]
>Thanks for your reply.
>Pitty is that I already prepared change for this. 😌
>Nevermind, I will take a look for something else. 🙂

Just submit your change, I don't know what you understood from my reply put he will look at it eventually.

> Also, @japanesephundroid, do you think that Issue#667 would be worth to try?

Yes. It's a small change I think.

**Comment by QuantumBadger** [comment]
@MichalFerencsik Yes, please do feel free to submit a pull request and I'll take a look at it.

**Comment by QuantumBadger** [comment]
Thanks for the proposed change @MichalFerencsik, I've left a comment on the PR.

In the meantime, to copy self-text it's possible to long click the post title and select "properties". At the bottom of the properties dialog is the self text, which you can highlight and copy.

**Comment by Cguy7777** [comment]
@QuantumBadger This seems to have been implemented. :-)

**Comment by QuantumBadger** [comment]
Thanks @Cguy7777, closing :)
