### ISSUE TITLE
Language choices in settings are not well supported.

### ISSUE THREAD

**Issue by AlicesWu** [QuantumBadger/RedReader#642]
# Context  

- Device: Nexus 5  
- OS version: Android 7.1.1
- App version: 1.9.9 (latest commit on 29/11/2018)

# Describe the bug  

When I changed languages on RedReader, not all text changed properly. On the main menu of the RedReader, some texts did not change into corresponding language.

This kind of bug does not just appear for one language. I can only recognize  problems of Malaysia and Chinese.

![image-20181215215036756](https://github.com/AlicesWu/images_markdown/blob/master/image-20181215214834657.png?raw=true)

![image-20181215232210687](https://github.com/AlicesWu/images_markdown/blob/master/image-20181215232210687.png?raw=true)

# How to reproduce  

"Click on the button on the top right corner" -> "Select 'Settings' " -> "Select 'Appearance' " -> "Click on 'Language' " -> "Select the sixth choice (Malaysia) or the last second choice(Chinese)"

**Comment by QuantumBadger** [comment]
This is expected behaviour as the translations are crowdsourced and incomplete. If you're a native speaker, you can help add to the translations here: https://hosted.weblate.org/engage/redreader/
