### ISSUE TITLE
Permission denied error on every v.redd.it link

### ISSUE THREAD

**Issue by ajgoda90** [QuantumBadger/RedReader#651]
It seems every v.redd.it link on the app gets a 403 Permission Denied error. Here's a r/RedReader thread about it with examples linked: https://reddit.com/comments/alz9vq

Seems like some sort of API change on Reddit's part.

**Comment by larroy** [comment]
Still happening with 1.10

**Comment by QuantumBadger** [comment]
> Still happening with 1.10

@larroy I think you're seeing issue #752 which was fixed in v1.11 :)

**Comment by larroy** [comment]
Where can I get an update? I went to F-Droid and where no updates.

**Comment by QuantumBadger** [comment]
> Thank you! Where can I get an update? I went to F-Droid and where no updates.

I've noticed that the F-Droid app doesn't always list updates, even when they are available. It usually works after force stopping F-Droid and clearing its cache in the Android settings.

If that doesn't work, they have a v1.11 APK available here:

https://f-droid.org/en/packages/org.quantumbadger.redreader/

Direct link: https://f-droid.org/repo/org.quantumbadger.redreader_91.apk
