### ISSUE TITLE
Block Subreddit does not work.

### ISSUE THREAD

**Issue by psychobeans** [QuantumBadger/RedReader#653]
Subreddits blocked continue to appear on the front page, even after multiple reloads.

**Comment by ajgoda90** [comment]
When you say "front page" do you mean from the main menu of RedReader you press "Front Page" or "All Subreddits"? If you mean you press Front Page, then you're looking at a list of subreddits you're subscribed to. If you don't want to see those in Front Page, then unsubscribe from them. If you mean you see blocked subreddits when you click "All Subreddits" then it's a bug.

**Comment by Hariiiiiiii** [comment]
"Front page" brings you to r/hot, and the blacklist does not seem to apply here properly at all. "all subreddits" brings you to r/all/hot, and the subreddit applies here properly. You state that r/hot should just show the subreddits you are subscribed to, but I am not signed in to an account.

**Comment by ajgoda90** [comment]
> 
> 
> "Front page" brings you to r/hot, and the blacklist does not seem to apply here properly at all. "all subreddits" brings you to r/all/hot, and the blacklist applies here properly. You state that r/hot should just show the subreddits you are subscribed to, but I am not signed in to an account.

It's actually just reddit.com/hot, not r/hot as a subreddit, and yes, if you're not logged in, then reddit.com/hot(or/new, /top, etc) will show an assortment of "popular" posts. In fact you can find that same list on r/popular. The way the blocking works is specific to r/all. It works by the URL being "r/all-blockedsub1-blockedsub2". You can't do this kind of URL with other subs, only r/all. So back to the original issue, if @psychobeans means he clicked Front Page in the first menu, then this is just the way Reddit works.

**Comment by QuantumBadger** [comment]
Fixed in the next version (v1.18) thanks to @Cguy7777 :)
