### ISSUE TITLE
Unable to sign into an account when using 2FA

### ISSUE THREAD

**Issue by brainard52** [QuantumBadger/RedReader#656]
I have a generator-based 2FA set up for my account and I'm unable to sign in. I'm running the latest available on F-Droid.

**Comment by betsythefc** [comment]
I'm experiencing the same problem. When trying to sign in, I enter my username and password. The Password field clears without an error, and doesn't tell me to enter the 2FA.

**Comment by NikolaeVarius** [comment]
Same here

**Comment by QuantumBadger** [comment]
Thanks for the report. To handle logins, the app just sends you to reddit in a web browser, so we have very little control over the process.

Thankfully, enabling Javascript in the WebView seems to have fixed this. The fix should be in the next version 1.9.10, and also in Alpha 179 now.
