### ISSUE TITLE
Media downloaded rather than streamed

### ISSUE THREAD

**Issue by lol768** [QuantumBadger/RedReader#659]
Apologies if this has come up before, I did search first.

When I open a post such as https://reddit.com/comments/bakd6d and tap to view the video, RedReader performs a 57 MB download - presumably the whole video - before playing it.

Does it need to do this in its entirety before paying the video? Can't the file be streamed as it is played?

**Comment by QuantumBadger** [comment]
This was added in v1.15 :)
