### ISSUE TITLE
Cant login; wrong password.

### ISSUE THREAD

**Issue by DrDonkey** [QuantumBadger/RedReader#661]
Hello, I was searching for a good reddit client, and stumbled upon **RedReader**, browsed for a while(without logging in).

I liked it quite a lot. Now I am trying to login and I get wrong password while trying to log in.

Edit: I clicked on forget password, in the next screen clicked login, and input the information, still wrong password.

I can login in reddit in Firefox without any problem.

**Comment by DrDonkey** [comment]
https://www.reddit.com/r/RedReader/comments/b3ofx9/wrong_password/

**Comment by landry314** [comment]
me too. i log in on my android browser and it works flawlessly but i use the same credentials in redreader and it says "invalid email of password"
