### ISSUE TITLE
Export settings

### ISSUE THREAD

**Issue by Kusresa** [QuantumBadger/RedReader#667]
Please add a way to backup the app's settings and a way to import it back.

**Comment by TheJags** [comment]
Export/import settings without the root access, would be a great feature.

Thanks.

**Comment by lawson85** [comment]
+1

**Comment by L418467** [comment]
Great app. With more great options in the latest versions. Because it takes some time to setup, would be nice to have an option to export/import settings.

**Comment by QuantumBadger** [comment]
This is now added in the latest Alpha (277):

https://redreader.org/alpha/

Give it a go and let me know if it works for you!
