### ISSUE TITLE
press for Post Context Menu is super sensitive

### ISSUE THREAD

**Issue by applemyer** [QuantumBadger/RedReader#67]
I can't view individual posts at the moment because every tap brings up the post context menu. It also comes up occasionally while I'm scrolling through posts.

Refreshing seems to improve things, but isn't helpful when I'm interested in a cached post. 

The problem is exacerbated because 'view post' isn't an option in the menu (though 'view in external browser' is).

Perhaps a long press could be set to bring up the context menu?

**Comment by QuantumBadger** [comment]
Since switching to the RecyclerView (to be in v1.9.5), the default Android logic is used for this.
