### ISSUE TITLE
Minor issue on Spanish L10n in settings 

### ISSUE THREAD

**Issue by namportuhkee** [QuantumBadger/RedReader#678]
Under Behavior in Preferences, the second iteration of 
"Acción al desplazar comentario a la izquierda" 
should be
"Acción al desplazar comentario a la derecha"
(left/right swipe of comments) 

This will avoid some confusion for users configuring these settings. 

[Screenshot_20190824-213201_RedReader](https://user-images.githubusercontent.com/44806351/63645253-28f57300-c6b7-11e9-84c8-3cc73945c5cd.jpg)

**Comment by sharkwouter** [comment]
Redreader actually has nice web interface for submitting translations. This string can be found here: https://hosted.weblate.org/translate/redreader/strings/es/?q=desplazar&type=all&ignored=False&checksum=&offset=

**Comment by namportuhkee** [comment]
Ah thank you. And you're right this is an awesome platform, I'm a little ashamed that in 7 years working in software translation I've actually never even heard of weblate.
