### ISSUE TITLE
Notifications don't work

### ISSUE THREAD

**Issue by sharkwouter** [QuantumBadger/RedReader#683]
Notifications haven't worked for me for a while now, but I didn't find a bug report about it yet. There is a thread on Reddit about it from a while back: https://www.reddit.com/r/RedReader/comments/ai1b8v/i_dont_get_notifications_i_used_to_but_not_now/

I'm using a Nokia 8 Plus with Android 9, in case that helps.

**Comment by japanesephundroid** [comment]
I get this as well since upgrading to Oreo.
This is and Oreo (Android 8 and after) bug as far as I can tell.

You can see the exact error if you go into **Developer Options** and enable **Show notification channel warnings**.

The error you will get is this:
```
Developer warning for package
"org.quantumbadger.redreader"
Failed to post notification on channel "null"
See log for more details
```

The error seems to be related to the [Notification channels](https://developer.android.com/training/notify-user/channels) Android feature introduced on Android 8.

**Comment by QuantumBadger** [comment]
Thanks @japanesephundroid, it's a shame this just silently fails by default! Sounds like it should be a relatively simple fix though.

**Comment by japanesephundroid** [comment]
>Thanks @japanesephundroid, it's a shame this just silently fails by default! Sounds like it should be a relatively simple fix though.

No problem, it's probably no coincidence Google added added that option in the developer options, they expected this to happen but didn't want that message popping up to regular users.

I've seen this happen on a few other apps as well, it even happened with an app that has support for notification channels, probably some old function forgotten somewhere in the code.

**Comment by QuantumBadger** [comment]
Should be fixed in Alpha 181 -- please let me know if so!

https://redreader.org/alpha/

**Comment by japanesephundroid** [comment]
I just made a self post on the subreddit.

https://www.reddit.com/r/RedReader/comments/dd97y0/testing_notifications_fix_for_oreo_and_later_on/

When you or someone else replys there I will tell you if it works.

**Comment by sharkwouter** [comment]
I've replied to it. Does it work?

**Comment by QuantumBadger** [comment]
The app checks for new messages every 30 mins, so it might take a while for the notification to appear.

**Comment by japanesephundroid** [comment]
> I've replied to it. Does it work?

Not yet, QuantumBadger says to wait for 30 minutes so stay tuned. I gonna reply to you to test that notification.

**Comment by japanesephundroid** [comment]
Just got it now 👍

**Comment by QuantumBadger** [comment]
Thanks both :)
