### ISSUE TITLE
An option to hide post/comment scores

### ISSUE THREAD

**Issue by suhr** [QuantumBadger/RedReader#689]
Scores are nice for sorting but they affect your opinion about a post before you read it. Thus it would be nice to have an option to display posts and comments without scores.

**Comment by KelianB-IMTA** [comment]
Should we also default to sorting by new instead of best when enabling this? Otherwise you will still be influenced since you know the first posts / comments are the most upvoted.

**Comment by suhr** [comment]
No, let default sorting to be a separate option.

**Comment by neilweber** [comment]
Duplicate of #669.
