### ISSUE TITLE
Links do not work with reddit formatting

### ISSUE THREAD

**Issue by PurpleCodingWizard** [QuantumBadger/RedReader#693]
When using formatting like `*http://duckduckgo.com/*` or `**http://startpage.com**` 
Links are not properly rendered. The asterisks are visible at the start and the trailing asterisk is added to the link making it invalid.

Expected behavior: Link should be rendered with or without(preferred) markdown formatting.

Noticed this when none of the links from the [amputator bot](https://old.reddit.com/u/amputatorbot) appeared to work.
The website has no such issue.

![IMG_20191215_084941](https://user-images.githubusercontent.com/34276732/70857638-4a8a9c80-1eea-11ea-99e3-491f83eade99.jpg)

**Comment by QuantumBadger** [comment]
Fixed in https://github.com/QuantumBadger/RedReader/commit/46852d0a95aa89e7dac8219f9b2ccec481f118b5 (alpha 198).
