### ISSUE TITLE
ERR_CLEARTEXT_NOT_PERMITTED error when opening http:// links

### ISSUE THREAD

**Issue by buildist** [QuantumBadger/RedReader#696]
Example: first link in https://reddit.com/comments/ecdc9o/comment/fbbfu42

Apparently recent versions of the Android API block non-https pages from being loaded in web views, but there's a simple workaround: https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

**Comment by sharkwouter** [comment]
I've seen this as well. I was wondering what was causing it :/

**Comment by QuantumBadger** [comment]
Thanks for reporting this -- fixed in the latest alpha :)
