### ISSUE TITLE
High Battery Usage on 1.9.11

### ISSUE THREAD

**Issue by GreatGrizzly** [QuantumBadger/RedReader#697]
At 45 hours on a charge and 3.5 hours of RedReader usage, I expect around 7% battery usage, which is consistent with other apps. However, I am seeing 35% usage on OxygenOS Android 8, and my current LineageOS 16, Android 9. I am using a OnePlus A5000 device on Tmobile.

![Screenshot (Dec 21, 2019 10_38_57 AM)](https://user-images.githubusercontent.com/15824566/71311693-a2d80780-23de-11ea-9fcb-97c140b98dde.png)

**Comment by QuantumBadger** [comment]
Thanks for the report!

Where did you get the "45 hours per charge" figure from? Doing some quick calculations based on those numbers, it looks like RR does pretty well (better than Amazon, and about the same as Firefox):

RedReader: [10 hours/charge](https://www.wolframalpha.com/input/?i=%28100%2F35%29+%C3%97+3.5+hours) (or [10% lost per hour](https://www.wolframalpha.com/input/?i=35%2F+%283.5+hours%29))
Amazon Shopping: [8.5 hours/charge](https://www.wolframalpha.com/input/?i=%28100%2F8%29+%C3%97+40+minutes) (or [12% lost per hour](https://www.wolframalpha.com/input/?i=8%2F+%2840+minutes%29))
Firefox: [10.5 hours/charge](https://www.wolframalpha.com/input/?i=%28100%2F5%29+%C3%97+31+minutes) (or [9.7% lost per hour](https://www.wolframalpha.com/input/?i=5%2F+%2831+minutes%29))

The majority of RR's battery usage is likely precaching images and comments, which can be disabled in the settings (under "Cache").

**Comment by QuantumBadger** [comment]
Just found this article, which claims that the OnePlus 5 can last about 11 hours while browsing on WiFi:

https://www.androidauthority.com/oneplus-5-battery-life-review-786111/

Basically I think everything's fine here, and you're seeing the expected battery life for your device :)

**Comment by GreatGrizzly** [comment]
@QuantumBadger Disabling caching improved the battery significantly.
