### ISSUE TITLE
[Feature request] Open Reddit links with Red Reader

### ISSUE THREAD

**Issue by Gaazoh** [QuantumBadger/RedReader#699]
When encountering a link to Reddit when browsing the internet, or beeing sent one, I see no option to open the link with Red Reader, either externally by allowing to open the link with Red Reader or by copying the link and pasting it somewhere inside the app.

It would be a nice feature to have, so you don't have to deal with Reddit's mobile website.

**Comment by mvdan** [comment]
I've encountered similar issues recently. I could swear this used to work years ago.

**Comment by QuantumBadger** [comment]
That's weird, it still works for me on the latest alpha:

https://github.com/QuantumBadger/RedReader/blob/master/src/main/AndroidManifest.xml#L62

It likely depends on which app you click the link from -- if you come across a link while browsing the web, it's unlikely to send out an intent for that, but if you e.g. click on a link in an email client, RedReader should handle it.

**Comment by mvdan** [comment]
Yeah, the last few times it's happened from links on the web, which then open the site - which annoyingly reminds me every time to install their app.

I wonder if there is a way to force Firefox to route those to this app.

**Comment by mvdan** [comment]
Ah, I just found the solution! The latest Firefox Preview on Android (3.2.0) has a setting I never noticed, "open links in apps". It works like a charm!

@QuantumBadger I think you can close this issue. If a browser doesn't have that feature, you can always point them to Firefox.

**Comment by QuantumBadger** [comment]
@mvdan Perfect, thanks for the update! I'll close this ticket.

**Comment by chocmake** [comment]
Would someone mind clarifying how this is meant to behave? As in Firefox for Android (Fennec fork at least) when enabling 'Open links in app' and clicking the 'Open' button that Reddit suggests it says no app found.

While if I instead click Share within Firefox and select RedReader as the destination app RedReader reports 'You must be logged in to do that'. Yet pasting the URL in RedReader's 'Find Location' field works fine, which is confusing.
