### ISSUE TITLE
Gone from Play Store

### ISSUE THREAD

**Issue by KaKi87** [QuantumBadger/RedReader#717]
What happened ?

**Comment by QuantumBadger** [comment]
Thanks for letting me know! I had absolutely no idea this had happened -- Google haven't contacted me, and in the Google Play Developer Console the app still shows up as published/visible.

Guess I'll have to contact them to find out...

**Comment by KaKi87** [comment]
Okay, in the meantime, could you tell me how do I make a search query on RedReader ? Thanks !

**Comment by Cguy7777** [comment]
That's odd, I just searched for RedReader on Google Play and it appears like normal for me. Maybe it's a country-specific thing? I'm in the US.

@KaKi87 You can search in the app by going to a subreddit and selecting **Search** in the three-dot menu, or by selecting **Custom Location** on the start screen and changing **Subreddit** to Search.

**Comment by QuantumBadger** [comment]
Thanks, works for me now too, it must have been a temporary issue.

**Comment by KaKi87** [comment]
I'm in France and this is still happening for me.

**Comment by matozoid** [comment]
Google Play search for "redreader" and "red reader" only finds other reddit apps in The Netherlands.

**Comment by KaKi87** [comment]
I directly tried the README's link : not working.

**Comment by QuantumBadger** [comment]
Looks like it's a widespread issue: https://9to5google.com/2020/03/02/play-store-disappearing-apps/

**Comment by QuantumBadger** [comment]
I've done what they suggested (made minor changes to the app description). If the article's accurate then the app should be available again soon :)

**Comment by KaKi87** [comment]
It worked, I can see the app again. Thanks
