### ISSUE TITLE
Search in NSFW subreddit not working

### ISSUE THREAD

**Issue by SuperMeepBoy** [QuantumBadger/RedReader#720]
- [x] I am running the latest version of RedReader (1.9.11)
- [x] I made sure no similar issue is currently opened

**Problem description**
:x: When I search in a NSFW subreddit I get no results.
:heavy_check_mark: When I do in a non-NSFW subreddit I get results
:heavy_check_mark: When I search in /r/all with a keyword that would return NSFW results, I get results and I believe I have NSFW results showing up in it.
:question: Using Anonymous profile, it does work correclty. Is it intended that I cannot do that with other profiles ?

**Expected behaviour**
Searching in NSFW subreddit should get me results.

**Current behaviour**
Searching in NSFW subreddit gets me no results.

**Step to reproduce**
1/ Go to a NSFW subreddit
2/ Search something that should get your results
3/ No results appear

**Context**
RedReader version: 1.9.11
OS version: LinageOS 15.1 (Android 8.1.0)

I saw a similar issue from 2018 (https://github.com/QuantumBadger/RedReader/issues/613).

**Comment by Cguy7777** [comment]
Do you have **Show NSFW content** enabled in the Behaviour settings? In the current version of the app it just silently fails to load NSFW posts. There will be a proper error message in the next release.

**Comment by SuperMeepBoy** [comment]
@Cguy7777 Yes I have **Show NSFW content** enabled.

To test it I tried this on many subreddits :

1/ Go to a NSFW subreddit
2/ Find a word which is usally used on these subreddits
3/ Search with this word
4/ No results appear

**Comment by Cguy7777** [comment]
If you're logged in, are you sure that "include not safe for work (NSFW) search results in searches" is enabled in your Reddit account settings? I just tested on my phone, and having that disabled was the only way I could reproduce the issue (with **Show NSFW content** enabled in the app).

(I'm also running RedReader 1.9.11 and Android 8.1)

**Comment by SuperMeepBoy** [comment]
@Cguy7777 I checked on my laptop in my user settings. It is explicilty written that I allowed NSFW results to be shown on Reddit including search results.

**Comment by SuperMeepBoy** [comment]
@Cguy7777 Searching with Anonymous in the app does make NSFW results show up tho. Is that the only way to do it ?

**Comment by drcouzelis** [comment]
You were correct, I did not have "include not safe for work (NSFW) search results in searches" selected on reddit.com. Doing so immediately resolved the issue. I am now able to see NSFW search results as expected. 

In my opinion this issue can be closed. Thank you!
