### ISSUE TITLE
Crash on login attempt

### ISSUE THREAD

**Issue by Wilker-a** [QuantumBadger/RedReader#722]
version 1.9.11 as of now, via Android 5.1.1 and acquired from F-Droid.

the application crashes and reboots immediately after loading the login page, making it impossible to login.

the same issue happens in Slide for some reason (perhaps this info is relevant?)

**Comment by QuantumBadger** [comment]
Thanks for the report. This is probably an issue with your Android ROM -- a lot of the crashes in RedReader are actually segfaults in the system WebView.

Android 5.1.1 is fairly old -- is it possible to upgrade your device to a more recent version?

**Comment by Wilker-a** [comment]
i actually have the default webview  disabled in favor of Bromite SystemWebView hoping it would treat some privacy issues...

and no, i can't update it unless i jailbreak my phone which doesn't seem like an option right now :(

**Comment by QuantumBadger** [comment]
Okay -- to look into this further I'd need a logcat from the time of the crash. I think it's just the alternative WebView though -- does it still crash if you disable it?

**Comment by Wilker-a** [comment]
i can't disable it without uninstalling or having to download the updates for Android WebView all again :\ data caps are an issue here and are quite limited and often fails, so i don't think i can try it until the next cycle...

**Comment by QuantumBadger** [comment]
Closing this as it's now possible to log in with an external browser.
