### ISSUE TITLE
External sites in the sidbar dont open

### ISSUE THREAD

**Issue by darthsithius** [QuantumBadger/RedReader#723]
![redreader_error](https://user-images.githubusercontent.com/36110938/77619734-ddfa5180-6f5e-11ea-894e-47133b2338b9.jpeg)

This is the error i'm getting for all external links in the sidebar except wikipedia.

**Comment by QuantumBadger** [comment]
Thanks for the report. This is the same as #696 -- the fix should be present in the next release.
