### ISSUE TITLE
Loading color-space images is slow, gray checkerboard, high CPU usage

### ISSUE THREAD

**Issue by nyanpasu64** [QuantumBadger/RedReader#726]
Some images uploaded to Reddit have embedded custom color spaces. When I open one of these images in redreader, it loads slowly.

Once the image is finished downloading, the canvas is set to a gray checkerboard (#528). Sometimes a random square loads first. Them the right column loads slowly, one square at a time, from bottom up. Then each column from right to left loads from bottom up, with long pauses between columns. During this process, RedReader burns CPU according to OS Monitor.

When the loading progress hits the "randomly loaded" square, it speeds up momentarily.

A 4000x3000 image takes about 5 seconds, whereas a 2000x2000 image takes only 1 second. A 1100x1600 image takes half a second. 1800x5617 takes half a second despite large height (but has few columns).

I don't know if the loading time is quadratic in the number of square tiles. The more tiles there are, the longer pause after each right-side square is loaded, or each column.

If I use the Moto screenshot-editing tool (which activates secondary display or something) while the image is loading, the image ends up with holes of missing image data, stuck as checkerboard.

Example links:

- jpg (3024x4032, 6.35 seconds): https://www.reddit.com/user/nyanpasu64/comments/fv1h7s/funny_color_spacejpg/
- png (3024x4032, 6.4 seconds): https://www.reddit.com/user/nyanpasu64/comments/fv1hdy/funny_color_spacepng/
- Wide (10k by 1k, 8 seconds): https://www.reddit.com/user/nyanpasu64/comments/fv1qkh/wide_104x3_display_p3_color_profile/
- Tall (1k by 10k, 8 seconds): https://www.reddit.com/user/nyanpasu64/comments/fv1qtj/tall_103x4_display_p3_color_profile/
- Square (4k by 4k, 9.2 seconds): https://www.reddit.com/user/nyanpasu64/comments/fv1zem/4000x4000jpg/

According to GIMP, these images have color profile:

> Display P3
> Copyright: Copyright Apple Inc., 2017

RedReader 1.9.11 F-Droid
Moto G5 Plus, Android 8.1.0

**Comment by QuantumBadger** [comment]
Thank you for the detailed report!

All those images load in under one second for me (300ms-ish) on an Xperia XA2 running LineageOS (Android 9). However I do see this behaviour with Android 8 on an aging Xperia Z.

Perhaps this is an issue with Android's image APIs, resolved in Android 9?

As far as I can see, the tiles on the bottom/right edges load very slowly, but the rest of the tiles load nice and quickly. We use two different code paths for these two cases:

https://github.com/QuantumBadger/RedReader/blob/master/src/main/java/org/quantumbadger/redreader/views/imageview/ImageTileSourceWholeBitmap.java#L91

The thing taking all the time is probably Android's `canvas.drawBitmap()` function -- I'm guessing that it's doing a colour space conversion, whereas `createScaledBitmap()` doesn't need to (at least until we [call into OpenGL](https://github.com/QuantumBadger/RedReader/blob/master/src/main/java/org/quantumbadger/redreader/views/glview/program/RRGLTexture.java#L65)).

**Comment by nyanpasu64** [comment]
Is there anything you'll do about this bug, and is there anything I should test or work on now?

**Comment by QuantumBadger** [comment]
Fixed here: https://github.com/QuantumBadger/RedReader/commit/5bf9811b4c6a2a9607e130452481a007a04b39d5

Also made the tiles load in a predictable order: https://github.com/QuantumBadger/RedReader/commit/2bd5db49431e3406f34c70a7f0631b22133c8952

And avoided smoothing the checkerboard when rendering: https://github.com/QuantumBadger/RedReader/commit/4f240b4f22af95ddc34d60a0b3c5ce5464b73096

Still working on a couple of related bits, which are to avoid squashing the checkerboard at the right/bottom edges, and to do the bitmap scaling in one step rather than two.

**Comment by QuantumBadger** [comment]
> Still working on a couple of related bits, which are to avoid squashing the checkerboard at the right/bottom edges, and to do the bitmap scaling in one step rather than two.

Fixed (and other optimisations added).

**Comment by nyanpasu64** [comment]
How do I test this fix or install a fixed version of the app? The CI system doesn't seem to export .apk artifacts.

**Comment by QuantumBadger** [comment]
The latest alpha builds are available here, build 191 should have this fix in:

https://redreader.org/alpha/

The alpha installs alongside the main app and shouldn't interfere with it.
