### ISSUE TITLE
Add button to "Copy subreddit URL" when viewing a subreddit?

### ISSUE THREAD

**Issue by nyanpasu64** [QuantumBadger/RedReader#727]
Right now, when you visit a subreddit, you can't copy the URL by long-pressing the black bar on the top of the scroll view. Neither can you open the toolbar's 3-dot menu to copy the URL. Can you add a way to copy subreddit URL?

Right now you can copy a subreddit URL from the home screen, just not the subreddit itself.

**Comment by lawson85** [comment]
+1
