### ISSUE TITLE
Backup custom location?

### ISSUE THREAD

**Issue by John3** [QuantumBadger/RedReader#735]
Hi

There is a way to export the custom location? (Pinned subreddits)

thx

**Comment by duggalsu** [comment]
It would be great to have an option to export/import pinned subreddits on new app install, when not logged in to reddit i.e. for anonymous accounts.

**Comment by QuantumBadger** [comment]
The ability to backup all the preferences at once is now added in the latest Alpha (277):

https://redreader.org/alpha/

Give it a go and let me know if it works for you!
