### ISSUE TITLE
[Feature Request] Option to hide toolbar added in 1.10 release

### ISSUE THREAD

**Issue by troyengel** [QuantumBadger/RedReader#742]
Hello, thanks for all the work from contributors. Myself and some others unfortunately do not like the new toolbar which has no option to disable it's presence, a feature request on behalf of a handful of Reddit users (who I don't know :) ).

* https://old.reddit.com/r/RedReader/comments/gz8k66/version_110_released/ftob3rm/
* https://www.reddit.com/r/RedReader/comments/h7ljxf/how_do_i_get_rid_of_this_new_toolbar/

We would like an new option to disable this new toolbar from displaying, thank you.

**Comment by jgkamat** [comment]
I personally use the side swipe method of getting to these functions, so for me this toolbar is taking up space for no benefit

**Comment by troyengel** [comment]
Thank you! :)

**Comment by QuantumBadger** [comment]
No problem :) I've added two new preferences for this:

* "Hide post list header toolbar"
* "Hide comment list header toolbar"

Should be in Alpha 199:

https://redreader.org/alpha/
