### ISSUE TITLE
Preference labels do not wrap

### ISSUE THREAD

**Issue by Cguy7777** [QuantumBadger/RedReader#750]
The labels for RedReader's preferences are cut off when there is not enough space to display them on one line. This is most noticeable when the system font size is larger than normal.

Tested on both 1.10 and the current codebase ([latest commit when I tested](https://github.com/QuantumBadger/RedReader/commit/3fe213395cbf8f38b82db9806a84a82fc9884167)) on API 27 (example below) and API 16.

![Screenshot_1593405873](https://user-images.githubusercontent.com/44722506/85973999-f46adb80-b999-11ea-9af3-43bed75da918.png)

**Comment by QuantumBadger** [comment]
Thanks! Looks potentially tricky to fix. The "right" way would be to migrate to `androidx.preference.PreferenceFragmentCompat` rather than using the deprecated APIs we currently use, although that's not a straightforward task.
