### ISSUE TITLE
Many (all?) v.reddit videos do not play in-app

### ISSUE THREAD

**Issue by Scorch-Mechanic** [QuantumBadger/RedReader#752]
Android 7.1.2 on a first generation Pixel XL
RedReader 1.10 from F-Droid 

Error message is "The server responded with a permission denied error."

Example erroring video (which played fine in an external browser): https://v.redd.it/x3bwv0v39c851/DASH_720.mp4?source=fallback

Comments thread for the video: https://reddit.com/r/aww/comments/hjmrfa/cute_cubs/

**Comment by Scorch-Mechanic** [comment]
Example thread with a v.redd.it video that does play in-app: https://reddit.com/r/HumansBeingBros/comments/hjlbh3/construction_workers_washing_off_a_blind_womans/

**Comment by QuantumBadger** [comment]
Thanks for the report! I released v1.11 last night which should fix this:

https://old.reddit.com/r/RedReader/comments/hjiylf/version_111_released/

**Comment by gappleto97** [comment]
Out of curiosity, what was the underlying issue?

**Comment by QuantumBadger** [comment]
> Out of curiosity, what was the underlying issue?

Reddit changed the name of the audio/video files, and was giving us a 403 error (rather than e.g. a 404 or a redirect) when we tried to access the old paths.

**Comment by happysmash27** [comment]
Can you post the update on F-Droid?

**Comment by QuantumBadger** [comment]
Apps on F-Droid are posted by the F-Droid developers, rather than by app developers directly. When I did the release a few days ago I tagged v1.11 on git, so they should hopefully build it soon.

**Comment by Lekensteyn** [comment]
For others wondering what changed, this patch should have addressed the issue: https://github.com/QuantumBadger/RedReader/commit/9874909b61e3a1f0c1fc21ce0db7a73b94c30309

F-Droid has already picked up and built a new version: https://gitlab.com/fdroid/fdroiddata/-/commit/4c62726490d4362450b6ad3caa5186276ea1aa3d / https://f-droid.org/wiki/page/org.quantumbadger.redreader/lastbuild_91
but the package has not been signed and published yet. Hopefully that should [happen][1] within a few days.

 [1]: https://f-droid.org/wiki/index.php?title=deploy&action=history
