### ISSUE TITLE
Permission Denied Errors virwing v.Reddit links

### ISSUE THREAD

**Issue by streetraider** [QuantumBadger/RedReader#753]
On version 1.10 different v.reddit links are giving me a permission denied error. Not all v.reddit links are throwing the error, but a majority of them are. 

Specific link I'm getting the error: https://v.redd.it/i6pnfsdhtm851/DASH_720.mp4?source=fallback

**Comment by joaofauvel** [comment]
Same here. The v.reddit works on external app.

**Comment by nullzel** [comment]
Came here to post this. Please fix, I love your open source Reddit reader.

**Comment by QuantumBadger** [comment]
Thanks for the report guys, but this is a duplicate of #752 :)

I fixed it and uploaded the update two days ago, but I'm waiting for Google's app approval process.

**Comment by QuantumBadger** [comment]
If anyone wants the update sooner, it's available here:

https://github.com/QuantumBadger/RedReader/releases/tag/v1.11
