### ISSUE TITLE
Some strings are not available for translation on weblate

### ISSUE THREAD

**Issue by B0pol** [QuantumBadger/RedReader#754]
For example, "Use Custom Tabs" was created in 2018-07-08 according to strings.xml, but it isn't available on weblate: French is 100% translated on weblate, but the app isn't.

**Comment by QuantumBadger** [comment]
Thanks for the report. I think this is now fixed:

https://hosted.weblate.org/languages/fr/redreader/search/?offset=1&q=tabs&sort_by=-priority%2Cposition&checksum=

Strings added today are now available:

https://hosted.weblate.org/languages/fr/redreader/search/?offset=1&q=subreddit_link_copied_to_clipboard&sort_by=-priority%2Cposition&checksum=

Please let me know if you notice this again with any other strings.
