### ISSUE TITLE
[bug] Preferences Menu stops functioning

### ISSUE THREAD

**Issue by JerellDR** [QuantumBadger/RedReader#76]
The "Post Context Menu Items" and "Post Toolbar Items"  menu freezes while checking/unchecking preference items.  I've been able to reproduce the bug in the "Post Context Menu Items" menu by tapping on any of the preferences at or below "save image". It was reproduced in the "Post Toolbar Items" menu by clicking on any preference items below "save".  The cancel and OK buttons still function properly when the menu is frozen. Backing out and re-entering the menu unfreezes the menu.

The phone it was tested on was running the Tweaked 3.2 Rom based on Android 2.3.6.

**Comment by QuantumBadger** [comment]
HoloEverywhere was abandoned in v1.9.0, and so hopefully this doesn't occur any more.
