### ISSUE TITLE
Lost password

### ISSUE THREAD

**Issue by C077eeGuy** [QuantumBadger/RedReader#769]
Hallo GitHub,

I stored my reddit password on a Keepass database and for some reasons I don know the database is empty. Luckily my reddit accounts were the only things saved there by that time. While creating my accounts I was asked to leave a e-mailadress and I thought naaaaa security over convenience and didn't connected the accounts to the e-mailadress. Is there a way I can restore my passwords for RedReader?

Big thank you in advance.

**Comment by QuantumBadger** [comment]
Hey!

Unfortunately (in this case) RedReader doesn't store your password, and so there's no way to recover it directly. Basically, the login process is handled via the reddit website, and reddit give us a randomly-generated access token which we store, so RedReader never actually sees what your password is.

If you're still logged into the app, it might be worth sending a message to one of the reddit admins from your account, and maybe they'll help out.

Sorry I couldn't help more, let me know if you have any other questions!
