### ISSUE TITLE
Some text has not been translated into Chinese

### ISSUE THREAD

**Issue by sjl872964789** [QuantumBadger/RedReader#783]
**Describe the bug**
Some text has not been translated into Chinese

**Context**
 - Device: [MI CC 9e]/[PIXEL XL]
 - OS version: [MIUI 10.2.10]/[Android 10.0]
 - App version: [1.12]

**Expected behavior**
The text is translated correctly

**Screenshots**
screen1:
<img src="https://user-images.githubusercontent.com/15941953/91156624-ef56ae00-e6f6-11ea-8e6e-7999d9b684dd.png" width="300" height="600"/>

screen2:
<img src="https://user-images.githubusercontent.com/15941953/91156657-fbdb0680-e6f6-11ea-80a0-26cd277301d9.png" width="300" height="600"/>

screen3:
<img src="https://user-images.githubusercontent.com/15941953/91156671-fe3d6080-e6f6-11ea-8bbd-a477f143e0da.png" width="300" height="600"/>

screen4:
<img src="https://user-images.githubusercontent.com/15941953/91156730-0eedd680-e6f7-11ea-89f4-bd5b06d0af58.png" width="300" height="600"/>

screen5:
<img src="https://user-images.githubusercontent.com/15941953/91156781-1d3bf280-e6f7-11ea-887e-e962902005e8.png" width="600" height="300"/>

screen6:
<img src="https://user-images.githubusercontent.com/15941953/91156795-21681000-e6f7-11ea-9398-c4ac64e63ef2.png" width="300" height="600"/>

screen7:
<img src="https://user-images.githubusercontent.com/15941953/91156880-380e6700-e6f7-11ea-8f8c-121fd4a2f044.png" width="300" height="600"/>

screen8:
<img src="https://user-images.githubusercontent.com/15941953/91156888-3a70c100-e6f7-11ea-9d82-f8b717ba1903.png" width="300" height="600"/>

screen9:
<img src="https://user-images.githubusercontent.com/15941953/91157065-71df6d80-e6f7-11ea-96b2-32b8cf315783.png" width="300" height="600"/>

screen10:
<img src="https://user-images.githubusercontent.com/15941953/91157070-74da5e00-e6f7-11ea-8310-b62a6fc5d816.png" width="300" height="600"/>

screen11:
<img src="https://user-images.githubusercontent.com/15941953/91157079-773cb800-e6f7-11ea-8eea-3d2718ccd242.png" width="600" height="300"/>

screen12:
<img src="https://user-images.githubusercontent.com/15941953/91157086-799f1200-e6f7-11ea-8fc7-385743846164.png" width="300" height="600"/>

screen13:
<img src="https://user-images.githubusercontent.com/15941953/91157094-7c016c00-e6f7-11ea-8cda-67cd3613b663.png" width="600" height="300"/>

**Comment by QuantumBadger** [comment]
Thank you for the detailed report. Translations are submitted by the community, and so they may be incomplete in some places:

https://hosted.weblate.org/projects/redreader/#languages

Almost all the text for Simplified Chinese has been translated, and will be in version 1.13. However Traditional Chinese is less complete.

If you are a fluent speaker, you can add the missing translations directly using the link above :)
