### ISSUE TITLE
Many images / gifs / videos stopped working

### ISSUE THREAD

**Issue by noughtmare** [QuantumBadger/RedReader#786]
They redirect to the internal or even the external browser which does work, but that is not nice.

Examples (from the current front page):
* https://old.reddit.com/r/interestingasfuck/comments/iwc4o5/this_incredible_wood_carving/
* https://old.reddit.com/r/PublicFreakout/comments/iw2ym5/what_the_fuck_is_wrong_with_the_police_officers/

It seems all v.redd.it, i.imgur.com and gfycat.com media are affected.

It started in the last couple of days. I have tried downgrading to version 1.12, but that didn't help.

**Comment by QuantumBadger** [comment]
Thanks for the report, but both links work fine for me. Have you run out of storage maybe?

Which device/OS are you using? If you're able to send me the relevant bit of the logcat that would be useful.

**Comment by noughtmare** [comment]
I'm using a Nexus 5 with the [crDroid custom ROM (Android 10)](https://forum.xda-developers.com/google-nexus-5/development/rom-crdroid-v5-4-t3931587). I still have more than 10GB free, so that can't be it.

Here is the relevant log: https://gist.github.com/noughtmare/f741624d3cc5fafea57366ad7074844d

**Comment by QuantumBadger** [comment]
Thanks for the extra details. If you encounter this again, there's a setting in the app which allows you to play videos in VLC if it's installed, which might work better.
