### ISSUE TITLE
Some links redirect to non http links resulting in errors

### ISSUE THREAD

**Issue by japanesephundroid** [QuantumBadger/RedReader#787]
Example:
https://www.reddit.com/r/LiverpoolFC/comments/iwj260/player_ratings_survey_chelsea_0_2_liverpool_fc/

Follow the "Link to survey" link at the start of the self text.

It redirects to a non http link and gives the following error:

```
Webpage not available

The webpage at intent://forms.gle/?????????????????#Intent;package=com.google.android.gms;action=com.google.firebase.dynamiclinks.VIEW_DYNAMIC_LINK;scheme=https;S.browser_fallback_url=https://docs.google.com/forms/d/e/???????????????????/viewform%3Fusp%3Dsend_form;end; could not be loaded because:

net::ERR_UNKNOWN_URL_SCHEME
```

There are also many examples of this on the Spotify subreddit:
https://www.reddit.com/r/spotify/

Opening any Spotify playlist link gives a similar error.

Using "View in External Browser" correctly passes the link to the Spotify app (or whatever app is set to open that link).

**Comment by QuantumBadger** [comment]
Thanks for the report. It could be a security issue to send out random intents from the web, but maybe if we detect an `intent://` scheme, we could parse out the `S.browser_fallback_url` field at the end of that URL and just go there.

**Comment by japanesephundroid** [comment]
Thanks.

Did not know what intent links were, I thought it was a bug, seeing as the external app handles the link fine.

Does the site actually redirect to an intent link?

What is the security issue exactly?

**Comment by QuantumBadger** [comment]
> Does the site actually redirect to an intent link?

Yeah, I think it detects that you're running Android, and attempts to redirect you to a native app.

> What is the security issue?

Assuming that any intent is allowed, it could mean websites could launch local apps with parameters of their choosing, or send intents to the system with RedReader's permissions. It's likely that there are apps which respond to intents in insecure ways, maybe allowing for arbitrary code execution (e.g. a terminal app which accepts a "launch this shell script" intent).

> maybe if we detect an intent:// scheme, we could parse out the S.browser_fallback_url field at the end of that URL and just go there.

From the following post, it looks like it's easy to do by parsing it as an intent:

https://support.google.com/docs/thread/12941044?hl=en

               if (url.startsWith("intent://")) {
                   val intent = Intent.parseUri(url, Intent.URI_INTENT_SCHEME)
                   if (intent != null) {
                       val fallbackUrl = intent.getStringExtra("browser_fallback_url")
                       return if (fallbackUrl != null) {
                           webView.loadUrl(fallbackUrl)
                           true
                       } else {
                           false
                       }
                   }
               }

**Comment by japanesephundroid** [comment]
Thanks 👍
