### ISSUE TITLE
Error message, server did not accept request for unknown reason

### ISSUE THREAD

**Issue by shom13** [QuantumBadger/RedReader#801]
Ver: 1 14
Android release: 10
Android SDK: 29

![e10fb034-7f5b-47b6-9f78-47cb336b7576.jpg](https://user-images.githubusercontent.com/61466421/97915396-6ce20e80-1d77-11eb-870b-2329b7819b3d.jpg)

**Comment by QuantumBadger** [comment]
Closing this for now as there's not enough info to do anything. Please could you:

* Add details from the "More detail" dialog
* Give a description of what you were trying to do
