### ISSUE TITLE
Disabling the comments button does not work properly on the current codebase

### ISSUE THREAD

**Issue by Cguy7777** [QuantumBadger/RedReader#817]
@QuantumBadger Not sure if this is known, but on the current codebase ([most recent commit as I write this](https://github.com/QuantumBadger/RedReader/commit/1666325648074ace16c58db6e0cca588f282dd16)), the comments button on listed posts is shown even if disabled, although it's non-functional. I suspect this has to do with layout changes for the new inline images.

**Comment by QuantumBadger** [comment]
Oops, well spotted, thanks! Yeah this was caused by the inline image changes, I've put in a fix here: https://github.com/QuantumBadger/RedReader/commit/35f779c09a04b5db6c782ebd8bd9de230791c870
