### ISSUE TITLE
GIF handling

### ISSUE THREAD

**Issue by averageapps** [QuantumBadger/RedReader#82]
I think the gif player which is used in RedReader is less than optimal. (The rest of the app is really great, though!)

Android´s built-in WebView can play animated gifs since API level 8 and as much as I saw, it works very well and is generally easy to implement. (see http://droid-blog.net/2011/10/17/tutorial-how-to-play-animated-gifs-in-android-part-3/)

Have you thought about using a WebView instead of the current method or would there be a problem with this solution?

**Comment by QuantumBadger** [comment]
As of v1.9.0/1, mp4 files are used rather than GIFs on imgur/gfycat/streamable.
