### ISSUE TITLE
error when marking inbox read

### ISSUE THREAD

**Issue by nutpantz** [QuantumBadger/RedReader#824]
Exception: com.fasterxml.jackson.core.JsonParseException
Unrecognized token 'Accepted': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (org.quantumbadger.redreader.common.datastream.MemoryDataStreamInputStream); line: 1, column: 14]
  com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1851)
  com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:717)
  com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3588)
  com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2683)
  com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:865)
  com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:757)
  org.quantumbadger.redreader.jsonwrap.JsonValue.parse(JsonValue.java:79)
  org.quantumbadger.redreader.jsonwrap.JsonValue.parse(JsonValue.java:35)
  org.quantumbadger.redreader.cache.CacheRequestJSONParser.lambda$onDataStreamAvailable$0$CacheRequestJSONParser(CacheRequestJSONParser.java:83)
  org.quantumbadger.redreader.cache.-$$Lambda$CacheRequestJSONParser$CoWRvlpdcQxraxuZij3DycnyNeE.run(lambda)
  org.quantumbadger.redreader.common.CachedThreadPool$Executor.run(CachedThreadPool.java:83)
  java.lang.Thread.run(Thread.java:818)

**Comment by QuantumBadger** [comment]
Thanks for the report, this has been fixed in the next version v1.16:

https://github.com/QuantumBadger/RedReader/commit/3c238971fe6d9fbf4ef19e63e1bbeb00b79cd1e5
