### ISSUE TITLE
Cache errors on latest Alpha 259 

### ISSUE THREAD

**Issue by japanesephundroid** [QuantumBadger/RedReader#825]
The app keeps throwing cache errors mostly when directly opening image links in comments

`
Title: Unexpected Storage Error
Message: An unknown internal error has occurred, related to the cache storage. You are probably running out of space.
URL: https://staticg.sportskeeda.com/editor/2019/03/1e0b6-15519602067019-800.jpg
Exception: java.io.IOException
Failed to create dirs: /data/user/0/org.quantumbadger.redreaderalpha/cache/rr_cache_files/41/0
org.quantumbadger.redreaderalpha.cache.CacheManager$WritableCacheFile.onWriteFinished(CacheManager.java:356)
org.quantumbadger.redreaderalpha.cache.CacheDownload$2.onSuccess(CacheDownload.java:292)
org.quantumbadger.redreaderalpha.http.okhttp.OKHTTPBackend$2.executeInThisThread(OKHTTPBackend.java:197)
org.quantumbadger.redreaderalpha.cache.CacheDownload.performDownload(CacheDownload.java:159)
org.quantumbadger.redreaderalpha.cache.CacheDownload.doDownload(CacheDownload.java:99)
org.quantumbadger.redreaderalpha.cache.CacheDownloadThread.run(CacheDownloadThread.java:38)
`

The cache error box also shows up momentarily when opening comments and then disappears.

Cache time indicator shows up twice on top of subreddits.
![Screenshot_2020-12-17-00-41-46](https://user-images.githubusercontent.com/20865454/102415636-30a1ff00-4001-11eb-8603-eca54de60550.png)

When I started noticing this problems I cleared all cache in the new internal app dialog.
After waiting a while I went to the Android **App info** >  **Storage** dialog and the cache was still showing up at around 1 GB, about the same as what the internal dialog was showing me. I also cleared cache there but the problem persisted.

I noticed a lot of cache fixes in the new Alphas so I guess there were bugs/regressions introduced with them.

**Comment by QuantumBadger** [comment]
Thanks for reporting this. I think the following will fix it: https://github.com/QuantumBadger/RedReader/commit/f2de60e49422d46a747115fde627aa29f167c810

Please could you let me know if Alpha 260 works correctly for you?

**Comment by japanesephundroid** [comment]
Thanks.

So far it does with some very basic testing, none of the issues I reported above reappear.

I will report back if I see any issues after a more prolonged usage.

**Comment by japanesephundroid** [comment]
I have tested the app for a while now, the cache issues seem to have been fixed.

👍

**Comment by QuantumBadger** [comment]
Perfect, thanks! I'll close this ticket, if you notice any more problems please let me know.

**Comment by japanesephundroid** [comment]
> Perfect, thanks! I'll close this ticket, if you notice any more problems please let me know.

ΟΚ
