### ISSUE TITLE
Using device's gesture navigation, image viewer breaks after attempting back gesture

### ISSUE THREAD

**Issue by marcel263** [QuantumBadger/RedReader#827]
![redreader115glitch-edit](https://user-images.githubusercontent.com/76437842/102793511-ee324680-43a1-11eb-8edf-7bccb73db998.gif)

RedReader 1.15. updated Samsung device running Android 10 and OneUI 2.5 

Steps to reproduce

- Have Image viewer set to "Internal viewer (OpenGL)"
- Open any image in the app
- Attempt to make the back gesture - stop it by returning finger to the starting position
- Interact with the image, e.g. zooming or panning. 

Result: Image disappears

Expected:

 Image should not disappear

**Comment by equeim** [comment]
@QuantumBadger This should be fixed now.

**Comment by QuantumBadger** [comment]
Thanks @equeim! I'll close this ticket once I've updated the changelog.

**Comment by equeim** [comment]
@QuantumBadger Also #1143 and #1157

**Comment by QuantumBadger** [comment]
Thanks! I've closed the tickets.

**Comment by marcel263** [comment]
Confirmed fixed, thank you for the work
