### ISSUE TITLE
Streamable link not picked up and the WebView version incorrectly fills the screen 

### ISSUE THREAD

**Issue by japanesephundroid** [QuantumBadger/RedReader#831]
As title.

Post and streamable link.
https://www.reddit.com/r/nba/comments/klsr5l/boban_and_his_lil_bro_luka/
https://streamable.com/tiskzc

When playing the video in WebView and switching to fullscreen, the video fills the screen instead of keeping the correct aspect radio.

**Comment by QuantumBadger** [comment]
Thanks for reporting this. Looks like Streamable are sending us the wrong mimetype (`application/octet-stream` rather than `video/mp4`).

I've put in a workaround, does Alpha 265 fix this for you?

**Comment by japanesephundroid** [comment]
Yes it does 👍

Thanks
