### ISSUE TITLE
Unable to share image via thirdparty apps (such as ShareDR)

### ISSUE THREAD

**Issue by nascentt** [QuantumBadger/RedReader#843]
I use ShareDR as a replacement for the android native share system (as that's just horrible).
[ShareDR](https://play.google.com/store/apps/details?id=com.rejh.sharedr&hl=en_GB&gl=US) shows a share dialog (which is faster and static) and seems to work for me for every app I try it with except redreader.  Unfortunately sharing images from redreader is something i do dozens of times a day.

I reached out to the dev of sharedr and his response was "I've reached out to the [redreader] developer but I don't think I've heard back yet. It's not something I can change, it's up to other apps to fix the issue on their end."

Unfortunately, I don't know exactly what needs to change.  But it's specific to the "share image" option in redreader.

**Comment by QuantumBadger** [comment]
Thanks, yeah I got a (very detailed and helpful) email from the dev a few days ago, it sounds like an Android bug with a simple workaround.

I'll add the fix when I get a free moment, once that's done I'll post a link to the latest Alpha build so you can make sure it fixes the issue.

**Comment by QuantumBadger** [comment]
Should be in Alpha 269 here: https://redreader.org/alpha/

**Comment by nascentt** [comment]
Incredible, it works! Thank you so much!

**Comment by QuantumBadger** [comment]
No problem, thanks for testing :)
