### ISSUE TITLE
Edit indicator no longer shows up

### ISSUE THREAD

**Issue by happysmash27** [QuantumBadger/RedReader#847]
Something changed in Reddit's APIs, and now RedReader does not indicate any edited comments as edited. See, for example, [this thread](https://old.reddit.com/r/amathenedit/comments/lle9zg/) on desktop vs RedReader. In desktop, they all have the asterisk, while on RedReader they no longer do.

**Comment by QuantumBadger** [comment]
Thanks for reporting this! I've added a fix, it should be in Alpha 271 (and the next release of the app).
