### ISSUE TITLE
Feature request: disable infinite scroll by default

### ISSUE THREAD

**Issue by ddevault** [QuantumBadger/RedReader#850]
Better for the user's mental health and would make RedReader more socially responsible.

**Comment by QuantumBadger** [comment]
Thanks for the suggestion! It's an interesting idea, however I think most users would find this frustrating as a default, and I can see it leading to lots of complaints.

You're probably aware, but we do have this as an option already ("Restrict post count", under Behaviour) which users can turn on if they like.
