### ISSUE TITLE
System logging should be checked

### ISSUE THREAD

**Issue by Cguy7777** [QuantumBadger/RedReader#851]
@QuantumBadger Currently, a lot of information is written to the system log; some of this information represents a potential data leak to apps with the ability to read that log (see [SC-10](https://developer.android.com/docs/quality-guidelines/core-app-quality#SC-10)).

Potential solutions:
- Use ProGuard to strip logging calls from the release builds.
- Create custom methods for logging: in the debug build these would simply pass arguments to `Log`, and in the release build they would ignore or reduce logging requests. (Alternatively, a preference for logging could be added, instead of relying on build type alone.)

**Comment by QuantumBadger** [comment]
Thanks for raising this! As far as I know, apps on Android can't access other apps' log output, and the log isn't saved to disk, therefore I don't think anyone would be vulnerable due to this.

I'm happy that we clean it up anyway though, and just remove any potentially sensitive messages. I think the only sensitive information which gets put in logcat is which URLs get downloaded, and I've removed most of them in the linked commit.

However most of these will end up there anyway due to Android's activity start logging, e.g.:

```
03-05 17:51:27.093 1392-1579/system_process I/ActivityManager: START {dat=https://oauth.reddit.com/r/all/.json cmp=org.quantumbadger.redreader/.activities.PostListingActivity u=0} from pid 2137
```

That's logged by Android itself, but maybe we could consider moving the URL out of the "data" field and into some other field in the intent, if that hides it? Potentially overkill though :)

**Comment by Cguy7777** [comment]
Thanks for the quick response! I agree that this probably isn't a major issue, but it seems like good practice to check it just to be safe.

I've gone through the source, and found several other potentially sensitive logs:

- `AlbumListingActivity`: [Album Url](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/activities/AlbumListingActivity.java#L68), [Album size](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/activities/AlbumListingActivity.java#L206)
- `AlbumAdapter`: [Thumbnail Url](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/adapters/AlbumAdapter.java#L166)
- `LinkHandler`: Imgur Image Ids ([1](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/common/LinkHandler.java#L693), [2](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/common/LinkHandler.java#L708), [3](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/common/LinkHandler.java#L725)); Imgur Album Ids ([1](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/common/LinkHandler.java#L808), [2](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/common/LinkHandler.java#L824), [3](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/common/LinkHandler.java#L842))
- `PostListingFragment`: Comment Urls ([1](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/fragments/PostListingFragment.java#L981), [2](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/fragments/PostListingFragment.java#L1007)); Media Urls ([1](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/fragments/PostListingFragment.java#L1040), [2](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/fragments/PostListingFragment.java#L1051), [3](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/fragments/PostListingFragment.java#L1061), [4](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/fragments/PostListingFragment.java#L1072), [5](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/fragments/PostListingFragment.java#L1098), [6](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/fragments/PostListingFragment.java#L1121))
- `OKHTTPBackend`: Urls ([1](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/http/okhttp/OKHTTPBackend.java#L170), [2](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/http/okhttp/OKHTTPBackend.java#L200))
- `NewMessageChecker`: [Number of messages](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/receivers/NewMessageChecker.java#L130)
- `RedditChangeDataManager`: Usernames ([1](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/reddit/prepared/RedditChangeDataManager.java#L111), [2](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/reddit/prepared/RedditChangeDataManager.java#L138), [3](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/reddit/prepared/RedditChangeDataManager.java#L160), [4](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/reddit/prepared/RedditChangeDataManager.java#L169))
- `RedditPreparedPost`: [Thumbnail Url](https://github.com/QuantumBadger/RedReader/blob/088b0277f68139f0610348fa038c36dca2959574/src/main/java/org/quantumbadger/redreader/reddit/prepared/RedditPreparedPost.java#L1358)

**Comment by QuantumBadger** [comment]
@Cguy7777 Thanks for going through those! There are a few useful log messages in there, so probably worth making them only log in debug mode as you originally mentioned. For now I think it should be sufficient to just wrap them with `if(BuildConfig.DEBUG) {}` (or add a function `General.isSensitiveDebugLoggingEnabled()` which returns `BuildConfig.DEBUG`).
