### ISSUE TITLE
[Feature Request] Option to change where Youtube links open

### ISSUE THREAD

**Issue by Guririn** [QuantumBadger/RedReader#866]
The official Youtube app is the last thing I want to use for Youtube. It would be nice to at least be able to choose an ad free option like Vanced, NewPipe or adblocked Firefox.

**Comment by japanesephundroid** [comment]
You can change which app opens for Youtube links by:
Youtube app info > Open by default > Clear defaults
or
Youtube app info > Open by default > Open supported links > Don't open in this app

You can then set the default with the app you want to open the Youtube link - say NewPipe:
NewPipe app info > Open by default > Open supported links > Open in this app

This is on my Android version mind you (8.0) things may have moved around on your version
