### ISSUE TITLE
AMP reddit links open in internal browser

### ISSUE THREAD

**Issue by Gaazoh** [QuantumBadger/RedReader#869]
**Issue**

Opening an AMP link to Reddit content loads the Reddit page in the internal browser.

**Expected behavior**

The linked content should be loaded natively by Red Reader

**Reproduction steps**

* Navigate to a post or comment containing an AMP link to other Reddit Content, such as this comment: https://www.reddit.com/r/196/comments/nkysy0/average_raverageredditor_user_complaining_about/gzgl1bd/
* Follow the link (https://www.google.com/amp/s/amp.reddit.com/r/antifastonetoss/comments/fcck5a/the_definitive_guide_to_why_stonetoss_is_a_nazi/)
* Link opens in internal browser

**Version used**

Red Reader 1.16 on android 10

**Comment by QuantumBadger** [comment]
Thanks! Added in Alpha 280:

https://redreader.org/alpha/
