### ISSUE TITLE
Allow custom text selection actions in Android 11

### ISSUE THREAD

**Issue by scubajeff** [QuantumBadger/RedReader#872]
After version 11, Android changes package visibility behavior, to allow other apps, like translator, to add action when user select text in RedReader, please add the following to RedReader's manifest:
```
<queries>
 <intent>
   <action android:name="android.intent.action.PROCESS_TEXT" />
   <data android:mimeType="text/plain" />
 </intent>
</queries>
```
Please refer to https://developer.android.com/training/package-visibility/use-cases#custom-text-selection-actions

**Comment by QuantumBadger** [comment]
Thanks for the suggestion! I've put this in the manifest in Alpha 279:

https://redreader.org/alpha/

Please feel free to give it a go and let me know how it goes.
