### ISSUE TITLE
when saving media to download, audio is not included

### ISSUE THREAD

**Issue by Wyld-One** [QuantumBadger/RedReader#873]
audio not saving with video for v.redd.it in MP4 file

works fine with internal viewer, not with web or VLC.

**Comment by sobornostea** [comment]
I also have the same issue ! Is there anything we can do ?

**Comment by QuantumBadger** [comment]
There's some discussion of this in  #532, unfortunately Reddit stores the video and audio streams as separate files, so to fix this we'd have to mux them together into a single file. It's something I'm hoping to add in future!

**Comment by QuantumBadger** [comment]
I've fixed this in the latest alpha :) Will be in v1.18.
