### ISSUE TITLE
Reddit broke on Android JellyBean/KitKat

### ISSUE THREAD

**Issue by ElementW** [QuantumBadger/RedReader#881]
As [announced on /r/redditsecurity](https://www.reddit.com/r/redditsecurity/comments/oeyuom/tls_protocol_and_ciphersuite_modernization/) (without any prior warning, thanks a lot admins), Reddit now only supports TLS 1.2 network encryption.

This means JellyBean/KitKat can't access Reddit any more as their SSL/TLS stack don't have TLS 1.2 enabled, and RedReader just throws errors everywhere.

However starting from API 16 (JB) the Android-bundled OpenSSL actually does support and there is a way to enable it [as evidenced by this StackOverflow question](https://stackoverflow.com/questions/28943660/how-to-enable-tls-1-2-support-in-an-android-application-running-on-android-4-1); this could be used to keep JB/KK support at minimal cost.

**Comment by lawson85** [comment]
I think you should be looking to install a custom ROM, because Lots of apps are going to end support including Google play services

**Comment by QuantumBadger** [comment]
Thanks! I've put in a fix for this, which will be in Alpha 287 and v1.17.3.

**Comment by ElementW** [comment]
@QuantumBadger Thanks for the fix.

@lawson85 Bold of you to assume "lots of apps" is relevant here, because it is not. RR doesn't depend on Play Services, and Google Play isn't the only app distribution platform RR is on. If RedReader wants to stop supporting JB/KK then the gradle build files just need to specify a higher required SDK version, and this issue be closed. And my use of an older Android version is none of your business considering this didn't happen.
