### ISSUE TITLE
[Feature Request] Mute bot/AutoModerator

### ISSUE THREAD

**Issue by cricketer** [QuantumBadger/RedReader#882]
I would like to be able to mute certain bot account unless they comment directly on my posts/comments.

The bot AutoModerator is a plague, it's top stickied comment of every thread in [r/anime_tittes](https://old.reddit.com/r/anime_titties/), spamming the same message over and over. I'm tired of having to scroll down and past it.

**Comment by QuantumBadger** [comment]
I've added a preference to collapse stickies by bots, should be in the next version :)
