### ISSUE TITLE
Readreader Alpha 288 keeps crushing when entering any view that contains posts (Front Page, All Subreddits, specific subreddits etc)

### ISSUE THREAD

**Issue by japanesephundroid** [QuantumBadger/RedReader#883]
I am guessing this has something to do with this:
https://github.com/QuantumBadger/RedReader/commit/adc377d8e76ab655e5561afaf3e3e0b4bbefe73f

After cleaning the app settings the views work now, but obviously I don't want to to that since I have a lot of tweaked settings, after restoring the settings backup from Titanium Backup the crush still happens.

**Comment by japanesephundroid** [comment]
The related logcats I could find are these:

```
[07-11 15:55:03.355 1314:3881 I/ActivityManager]
START u0 {dat=https://oauth.reddit.com/... cmp=org.quantumbadger.redreaderalpha/.activities.PostListingActivity} from uid 10250

[07-11 15:55:03.384 1314:13259 D/InputDispatcher]
Focus left window: Window{244c88a u0 org.quantumbadger.redreaderalpha/org.quantumbadger.redreaderalpha.activities.MainActivity}

[07-11 15:55:03.517 1314:1496 D/InputDispatcher]
Focus entered window: Window{8504578 u0 org.quantumbadger.redreaderalpha/org.quantumbadger.redreaderalpha.activities.PostListingActivity}

[07-11 15:55:03.561 1314:8692 W/ActivityManager]
  Force finishing activity org.quantumbadger.redreaderalpha/.activities.PostListingActivity

[07-11 15:55:03.567 1314:8692 W/ActivityManager]
  Force finishing activity org.quantumbadger.redreaderalpha/.activities.MainActivity

[07-11 15:55:03.575 1314:8692 D/InputDispatcher]
Focus left window: Window{8504578 u0 org.quantumbadger.redreaderalpha/org.quantumbadger.redreaderalpha.activities.PostListingActivity}

[07-11 15:55:03.644 1314:1632 D/InputDispatcher]
Focus entered window: Window{c03ca33 u0 Application Error: org.quantumbadger.redreaderalpha}

[07-11 15:55:03.646 1314:1632 I/ActivityManager]
Showing crash dialog for package org.quantumbadger.redreaderalpha u0
```

**Comment by QuantumBadger** [comment]
Thanks for the report @japanesephundroid, yes this is probably Proguard related.

Also thank you for the logcat. Do you see a stack trace anywhere nearby, with the text "FATAL EXCEPTION"? It should look a bit like the trace in the following issue:

https://github.com/QuantumBadger/RedReader/issues/884

**Comment by japanesephundroid** [comment]
Also Redreader shows up in Titanium Backup as:
**Redreader Alpha 288 Alpha 288**
for some reason. Let me check for the "FATAL EXCEPTION".

**Comment by japanesephundroid** [comment]
No "FATAL EXCEPTION", anything else I can look for?

**Comment by QuantumBadger** [comment]
> No "FATAL EXCEPTION", anything else I can look for?

Hmm, do you see anything above the line saying "Force finishing activity org.quantumbadger.redreaderalpha/.activities.PostListingActivity"?

Other text to look for is "beginning of crash" and "Caused by".

**Comment by QuantumBadger** [comment]
I've put a potential fix in Alpha 289, please could you let me know if it works for you? (You may need to force stop and manually refresh F-Droid to make it detect the update).

**Comment by japanesephundroid** [comment]
> Other text to look for is "beginning of crash" and "Caused by".

No, nothing.

> I think this is just because the app name is "RedReader Alpha 288", and the version is "Alpha 288", so Titanium Backup concatenates them together.
👍

**Comment by japanesephundroid** [comment]
> I've put a potential fix in Alpha 289, please could you let me know if it works for you? (You may need to force stop and manually refresh F-Droid to make it detect the update).

It works now with this new fix 👍.

Is the shrinkRecources flag not needed?

**Comment by QuantumBadger** [comment]
Perfect, thanks for testing!

> Is the shrinkRecources flag not needed?

It should be fine to turn it off. I mainly turned Proguard on because I wanted to shrink the code (which had gone over the size limit of 65k method references). Shrinking the resources (images etc) only saved about 100kB and wasn't strictly necessary.
