### ISSUE TITLE
Block Subreddit doesn't work for FrontPage feed.

### ISSUE THREAD

**Issue by voteforplush** [QuantumBadger/RedReader#891]
/r/MakeMeSuffer is the name of my existence on Reddit, can't block it with RR.

I ran into it while using RR as I usually do, scrolling through FrontPage, oh there's a beautiful image of someone who's popped a zit the size of a quarter and there are gobs of white goop everywhere. So I long pressed on the tab of the listing, and set RR to block that subreddit. 

Unfortunately that really didn't do anything at all, and I don't understand why. Today an image of the inside of a woman's skull, bright red, scalp cut open, on a surgery table kissed my vision. I checked, maybe the cache got reset? Nope, it's still blocked. Why do I still see it? 

And yes, I know I can choose to blur out NSFW flagged content, but I'd rather keep that off and just block MakeMeSuffer as it's the only offender.

Version: 1.17.3, downloaded via F-Droid on OnePlus 7 Pro.

**Comment by QuantumBadger** [comment]
Fixed in the next version (v1.18) thanks to @Cguy7777 :) Basically the setting only applied to /r/all previously, whereas now it also applies to /r/popular and the front page.
