### ISSUE TITLE
New "Saved/shared videos from v.redd.it now have audio attached" feature does not work

### ISSUE THREAD

**Issue by japanesephundroid** [QuantumBadger/RedReader#927]
The [new video save feature](https://github.com/QuantumBadger/RedReader/commit/67ee5208785f3623d6efea2b58befbd62d9827b5) does not work on my phone.

Below is the bug report readout:
```
Error report -- RedReader vAlpha 295

Manufacturer: LGE
Model: LG-US996
Product: elsa_nao_us
Android release: 8.0.0
Android SDK: 26

-------------------------------
Title: Video generation failed
Message: Failed to combine the video and audio tracks into a single file.
URL: https://v.redd.it/ajxpx00ti6381/DASH_480.mp4
Exception: java.lang.IllegalStateException
null
  java.util.ArrayList$Itr.remove(ArrayList.java:873)
  org.quantumbadger.redreaderalpha.common.-$$Lambda$MediaUtils$PeFvZvB_DZqJbZ7lpM_CP2qrpv8.run(lambda:39)
  java.lang.Thread.run(Thread.java:764)
```

Tried it with multiple videos. They all give out the same error.

**Comment by QuantumBadger** [comment]
Thanks for reporting this! I've added a potential fix here: https://github.com/QuantumBadger/RedReader/commit/ebea3b16efabcdec7fa1f829b6da50523a91e55c

@japanesephundroid Could you try this again with Alpha 296 please?

**Comment by japanesephundroid** [comment]
Fixed 👍

**Comment by QuantumBadger** [comment]
Perfect, thanks for testing :)

**Comment by japanesephundroid** [comment]
No problem, thanks for the quick fix.
