### ISSUE TITLE
Alphas no longer install on Android 11

### ISSUE THREAD

**Issue by Efreak** [QuantumBadger/RedReader#928]
RedReader alphas have not being installing via fdroid, so I finally tried to install manually today by downloading from the website, and got the same results. The result of my investigation follows:

<details>
<summary>RedReader 296 does not install because it has no version 2 signature</summary>

```
gts6lwifi:/data/local/tmp $ pm install RedReader_Alpha_296.apk
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Scanning Failed.: No signature found in package of version 2 or newer for package org.quantumbadger.redreaderalpha]
```

</details>

 [_Apps that target Android 11 (API level 30) that are currently only signed using APK Signature Scheme v1 must now also be signed using APK Signature Scheme v2 or higher. Users can't install or update apps that are only signed with APK Signature Scheme v1 on devices that run Android 11._](https://developer.android.com/about/versions/11/behavior-changes-11#minimum-signature-scheme)
<details>
<summary>Version 196 is not signed correctly</summary>

```
✦ ❯ apksigner verify RedReader_Alpha_294.apk
WARNING: META-INF/com/android/build/gradle/app-metadata.properties not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/services/com.fasterxml.jackson.core.JsonFactory not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.

~
✦ ❯ apksigner verify RedReader_Alpha_296.apk
DOES NOT VERIFY
ERROR: Target SDK version 30 requires a minimum of signature scheme v2; the APK is not signed with this or a later signature scheme
WARNING: META-INF/com/android/build/gradle/app-metadata.properties not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/services/com.fasterxml.jackson.core.JsonFactory not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
```
</details>

I believe the issue was introduced in commit 278015e1ed8358b3d30744c46eb8ba31dccf6f6e  where the SDK version was increased to 30, but no extra signature was added.

**Comment by QuantumBadger** [comment]
Thanks for reporting this! Fixed in Alpha 297.
