### ISSUE TITLE
Allow sponsoring on GitHub

### ISSUE THREAD

**Issue by mvdan** [QuantumBadger/RedReader#930]
I use the app on a daily basis, and I would love to contribute continuously too.

GitHub Sponsors is fairly easy to set up, pretty popular, and they cover payment processing fees for you. If a user donates $5 a month, you get 100% of it.

Any other donation method is also of course an option, though I'd suggest also supporting github directly :)

**Comment by QuantumBadger** [comment]
@mvdan That's very generous, thank you :) I'm considering setting this up.

@Cguy7777 Since you contribute so much these days, would you be interested in being added to the "sponsor-able developers" screen for the project too?

**Comment by Cguy7777** [comment]
@QuantumBadger Sure, I would love to try it. No pressure to set it up though, I'll be happy either way. :-)

**Comment by QuantumBadger** [comment]
@Cguy7777 No problem -- if you set up a GitHub sponsor profile then I can add you to `FUNDING.yml`.

**Comment by Cguy7777** [comment]
@QuantumBadger My profile is ready to go.

**Comment by QuantumBadger** [comment]
This should all be sorted now -- I've set up [a profile](https://github.com/sponsors/QuantumBadger), and added a Sponsor button to the repo with both of our links.

**Comment by mvdan** [comment]
All done then - thanks!
