### ISSUE TITLE
[Feature Request] Custom location search suggestions

### ISSUE THREAD

**Issue by willhansen** [QuantumBadger/RedReader#934]
Using the "custom location" button in the main menu, it would be convenient if the dropdown suggestions could suggest all subreddits containing the typed string.  Maybe with some fuzzy pattern matching thrown in if easy.  

Often-times, I'm looking for new subreddits, so typing in "game", I would be happy with suggestions like "boardgames" or "gaming".

It wouldn't even need to get the list of subreddits in realtime, just download the full list of subreddits in the background every week or so.

**Comment by QuantumBadger** [comment]
Full subreddit search added in Alpha 302.
