### ISSUE TITLE
callback compatibility issue when initialing method

### ISSUE THREAD

**Issue by PSDroid2022** [QuantumBadger/RedReader#963]
We confirm a callback compatibility issue which might threaten the robustness of your app and give a detailed suggestion for you.

In ''BaseActivity", you super the framework API "<android.app.Activity: void onRequestPermissionsResult(int,java.lang.String[],int[])>" in "onRequestPermissionsResult" method as shown in following. But actually, this method is added in API level 23 ([https://developer.android.google.cn/reference/android/app/Activity?hl=en#onRequestPermissionsResult(int,%20java.lang.String[],%20int[])](https://developer.android.google.cn/reference/android/app/Activity?hl=en#onRequestPermissionsResult(int,%20java.lang.String%5B%5D,%20int%5B%5D))).

```java
@Override
	public final void onRequestPermissionsResult(
			final int requestCode,
			@NonNull final String[] permissions,
			@NonNull final int[] grantResults) {

		super.onRequestPermissionsResult(requestCode, permissions, grantResults);

		final PermissionCallback callback
				= mPermissionRequestCallbacks.remove(requestCode);

		if(callback == null) {
			return;
		}

		if(permissions.length != 1) {
			throw new RuntimeException("Unexpected permission result");
		}

		if(grantResults[0] == PackageManager.PERMISSION_GRANTED) {
			callback.onPermissionGranted();
		} else {
			callback.onPermissionDenied();
		}
	}

```
So when the app try to initial related Toast on devices level 21 and 22, your app will run with an unpredictable results. So we suggest you add an "if(SDK_INT>22)", " @TargetApi(Build.VERSION_CODES.M)" or change your app miniSDK from 16 to 23 to fix this potential issue.
By the way, "@TargetApi(Build.VERSION_CODES.M)" will be deleted by Android compiler when extracting APKs, so it seems like a not good way to solve those issues.

**Comment by QuantumBadger** [comment]
Thanks for the report, however this isn't a bug. `super.onRequestPermissionsResult()` is called from within `BaseActivity.onRequestPermissionsResult()`, which is only called on Android versions greater than M, because it's the system which calls that method. We run Lint on every commit using GitHub Actions, which notifies us if there are genuine problems of this kind.

**Comment by PSDroid2022** [comment]
Ok，actually we also find this issue in other repository, and developers confirmed this issues because this method will be automatically called when system sends a "request permission" intent. Refer https://github.com/enricocid/Music-Player-GO/issues/383 and https://github.com/mwarning/trigger/issues/73.

**Comment by QuantumBadger** [comment]
If the system is calling that method, then by definition it must be safe to call the super version of that method. `BaseActivity.onRequestPermissionsResult()` is only called as a result of overriding the superclass version of the method, which means that, if it's called, the superclass method must exist.
