### ISSUE TITLE
TalkBack: announce relative level of comments within a thread

### ISSUE THREAD

**Issue by codeofdusk** [QuantumBadger/RedReader#965]
Using TalkBack, there currently is no way to tell (without context) if a given comment is a reply to OP, a reply to a top-level comment, etc. (not sure if this is represented visually as I'm totally blind).

As a possible solution, TalkBack could report the relative "level" of each comment. For instance, replies to OP are at level 1, replies to comments on OP are at level 2, replies to those replies are at level 3, etc. The [Dystopia](https://reddit.com/r/dystopiaforreddit) client on iOS implements this behaviour when VoiceOver, the iPhone's screen reader, is enabled.

**Comment by QuantumBadger** [comment]
Thanks for the suggestion, I've now added this! It should be present in Alpha 306 later today, and also in the next version of the app (1.19).

**Comment by codeofdusk** [comment]
@QuantumBadger This is working fairly well!

Might it be possible, though, to map "level 1" to your "top level", making level 2 replys to "top comments", level 3 replys to those replys, etc?
