### ISSUE TITLE
Accessibility: add a user setting for more concise labels

### ISSUE THREAD

**Issue by codeofdusk** [QuantumBadger/RedReader#971]
At the moment, accessibility labels in RedReader are quite verbose, making quick scrolling and navigation inefficient for advanced users. For instance, the text "age:" and "domain:" before the respective elements can often be inferred, and other meta information can easily be abbreviated without loss of context for experienced Redditors.

To mitigate this, add a preference, disabled by default, in accessibility settings called "use concise language when possible". For some accessibility values, maintain a `concise` variant. When building labels, if the user preference is activated and a `concise` variant for a given accessibility element exists, use it in place of the original. Otherwise, use the original string (in other words, not all accessibility items need `concise` variants).

The following `concise` values should be defined and used whenever the new setting is enabled in place of the regular versions:

``` xml
	<string name="accessibility_subtitle_flair_withperiod_concise">[%s].</string>
	<string name="accessibility_subtitle_nsfw_withperiod_concise">NSFW.</string>
	<string name="accessibility_subtitle_points_withperiod_concise" tools:ignore="PluralsCandidate">%d up.</string>
	<string name="accessibility_subtitle_author_withperiod_concise">u/%s.</string>
	<string name="accessibility_subtitle_subreddit_withperiod_concise">r/%s.</string>
	<string name="accessibility_subtitle_domain_withperiod_concise">%s.</string>
	<string name="accessibility_subtitle_selfpost_withperiod_concise">Self.</string>
	<string name="accessibility_subtitle_comment_collapsed_concise">Collapsed.</string>
	<string name="accessibility_subtitle_author_submitter_withperiod_concise">u/%s, OP.</string>
	<string name="accessibility_subtitle_author_moderator_withperiod_concise">u/%s, mod.</string>
	<string name="accessibility_subtitle_author_submitter_moderator_withperiod_concise">u/%s, OP and mod.</string>
	<string name="accessibility_subtitle_author_submitter_admin_withperiod_concise">u/%s, OP and admin.</string>
	<string name="accessibility_subtitle_controversiality_withperiod_concise">Controversial.</string>
	<string name="accessibility_subtitle_upvote_ratio_withperiod_concise" tools:ignore="PluralsCandidate">%d percent up.</string>
	<string name="accessibility_comment_indent_level_concise" tools:ignore="PluralsCandidate">l%d.</string>
```

**Comment by QuantumBadger** [comment]
Thanks! I'll add a preference for this.
