### ISSUE TITLE
Allow sorting search results

### ISSUE THREAD

**Issue by aguslr** [QuantumBadger/RedReader#99]
It'd be great if the search results could be sorted by relevance, new, hot, top, etc. This is possible in the website and I miss it in the app.

By the way, great app. Love the work!

**Comment by mvy** [comment]
Hi! 

I thought I'd add a bump to this issue. The search without the ability to sort is barely useless. 
Every time I search for something in my subreddits, I want to look a comments that are new, and rarely the most popuplar/upvoted. 

M'vy

**Comment by QuantumBadger** [comment]
Thanks to chaitan94 this has just been added and will be in the next version :)

https://github.com/QuantumBadger/RedReader/pull/203
